### ISSUE TITLE
PostgreSQL 10 翻訳

### ISSUE THREAD

**Issue by koizumistr** [pgsql-jp/jpug-doc#1009]
## 問題点

PotgreSQL 10がリリースされました。

**Comment by koizumistr** [comment]
git diff --stat REL9_6_5 REL_10_0 doc/src/sgml/ 

 doc/src/sgml/.gitignore                            |   11 +-
 doc/src/sgml/Makefile                              |  221 +-
 doc/src/sgml/acronyms.sgml                         |   10 +
 doc/src/sgml/adminpack.sgml                        |    2 +-
 doc/src/sgml/advanced.sgml                         |   31 +-
 doc/src/sgml/amcheck.sgml                          |  273 ++
 doc/src/sgml/backup.sgml                           |  113 +-
 doc/src/sgml/bgworker.sgml                         |   36 +-
 doc/src/sgml/biblio.sgml                           |  123 +-
 doc/src/sgml/brin.sgml                             |   26 +-
 doc/src/sgml/btree-gin.sgml                        |    3 +-
 doc/src/sgml/btree-gist.sgml                       |    8 +-
 doc/src/sgml/catalogs.sgml                         | 1125 ++++++-
 doc/src/sgml/charset.sgml                          |  384 ++-
 doc/src/sgml/citext.sgml                           |    5 +
 doc/src/sgml/client-auth.sgml                      |  198 +-
 doc/src/sgml/config.sgml                           |  608 +++-
 doc/src/sgml/contrib.sgml                          |    2 +-
 doc/src/sgml/custom-scan.sgml                      |   42 +-
 doc/src/sgml/datatype.sgml                         |  172 +-
 doc/src/sgml/ddl.sgml                              | 1328 +++++---
 doc/src/sgml/dfunc.sgml                            |   30 +-
 doc/src/sgml/dml.sgml                              |    4 -
 doc/src/sgml/docguide.sgml                         |  626 +---
 doc/src/sgml/ecpg.sgml                             |   36 +-
 doc/src/sgml/event-trigger.sgml                    |    1 +
 doc/src/sgml/extend.sgml                           |   62 +-
 doc/src/sgml/external-projects.sgml                |   32 +-
 doc/src/sgml/fdwhandler.sgml                       |   57 +-
 doc/src/sgml/file-fdw.sgml                         |   68 +-
 doc/src/sgml/filelist.sgml                         |   19 +-
 doc/src/sgml/fixrtf                                |   46 -
 doc/src/sgml/func.sgml                             | 1353 ++++++--
 doc/src/sgml/generate-errcodes-table.pl            |    4 +-
 doc/src/sgml/generic-wal.sgml                      |    2 +-
 doc/src/sgml/gin.sgml                              |  349 +-
 doc/src/sgml/high-availability.sgml                |  192 +-
 doc/src/sgml/indexam.sgml                          |   96 +-
 doc/src/sgml/indices.sgml                          |   17 +-
 doc/src/sgml/information_schema.sgml               |   41 +-
 doc/src/sgml/install-windows.sgml                  |  155 +-
 doc/src/sgml/installation.sgml                     |  310 +-
 doc/src/sgml/jadetex.cfg                           |   89 -
 doc/src/sgml/json.sgml                             |    2 +-
 doc/src/sgml/keywords.sgml                         |   51 +-
 doc/src/sgml/libpq.sgml                            |  326 +-
 doc/src/sgml/lobj.sgml                             |    2 +-
 doc/src/sgml/logical-replication.sgml              |  592 ++++
 doc/src/sgml/logicaldecoding.sgml                  |   79 +-
 doc/src/sgml/maintenance.sgml                      |   32 +-
 doc/src/sgml/mk_feature_tables.pl                  |   14 +-
 doc/src/sgml/monitoring.sgml                       |  828 ++++-
 doc/src/sgml/mvcc.sgml                             |   10 +-
 doc/src/sgml/pageinspect.sgml                      |  272 +-
 doc/src/sgml/parallel.sgml                         |  199 +-
 doc/src/sgml/perform.sgml                          |  234 +-
 doc/src/sgml/pgbuffercache.sgml                    |    5 +-
 doc/src/sgml/pgcrypto.sgml                         |   24 +-
 doc/src/sgml/pgfreespacemap.sgml                   |    5 +-
 doc/src/sgml/pgrowlocks.sgml                       |    7 +
 doc/src/sgml/pgstandby.sgml                        |    2 +-
 doc/src/sgml/pgstatstatements.sgml                 |   38 +-
 doc/src/sgml/pgstattuple.sgml                      |  118 +-
 doc/src/sgml/pgvisibility.sgml                     |    5 +-
 doc/src/sgml/planstats.sgml                        |  141 +-
 doc/src/sgml/plhandler.sgml                        |    2 +-
 doc/src/sgml/plperl.sgml                           |    5 +-
 doc/src/sgml/plpgsql.sgml                          |   93 +-
 doc/src/sgml/plpython.sgml                         |   71 +-
 doc/src/sgml/pltcl.sgml                            |  293 +-
 doc/src/sgml/postgres-fdw.sgml                     |   41 +-
 doc/src/sgml/postgres.sgml                         |    4 +-
 doc/src/sgml/protocol.sgml                         | 1678 +++++++++-
 doc/src/sgml/queries.sgml                          |   10 +-
 doc/src/sgml/query.sgml                            |    2 +-
 doc/src/sgml/recovery-config.sgml                  |   26 +-
 doc/src/sgml/ref/allfiles.sgml                     |   17 +-
 doc/src/sgml/ref/alter_aggregate.sgml              |    3 +-
 doc/src/sgml/ref/alter_collation.sgml              |   56 +
 doc/src/sgml/ref/alter_database.sgml               |    4 +
 doc/src/sgml/ref/alter_default_privileges.sgml     |   17 +-
 doc/src/sgml/ref/alter_domain.sgml                 |   16 +-
 doc/src/sgml/ref/alter_extension.sgml              |    2 +-
 doc/src/sgml/ref/alter_function.sgml               |   13 +-
 doc/src/sgml/ref/alter_opfamily.sgml               |    7 +-
 doc/src/sgml/ref/alter_policy.sgml                 |    7 +-
 doc/src/sgml/ref/alter_publication.sgml            |  165 +
 doc/src/sgml/ref/alter_role.sgml                   |   12 +-
 doc/src/sgml/ref/alter_sequence.sgml               |   62 +-
 doc/src/sgml/ref/alter_statistics.sgml             |  117 +
 doc/src/sgml/ref/alter_subscription.sgml           |  229 ++
 doc/src/sgml/ref/alter_system.sgml                 |    3 +-
 doc/src/sgml/ref/alter_table.sgml                  |  210 +-
 doc/src/sgml/ref/alter_type.sgml                   |   63 +-
 doc/src/sgml/ref/alter_user.sgml                   |    4 +-
 doc/src/sgml/ref/analyze.sgml                      |    7 +-
 doc/src/sgml/ref/checkpoint.sgml                   |    4 +-
 doc/src/sgml/ref/clusterdb.sgml                    |    2 +-
 doc/src/sgml/ref/comment.sgml                      |   10 +-
 doc/src/sgml/ref/copy.sgml                         |   19 +-
 doc/src/sgml/ref/create_access_method.sgml         |    3 +-
 doc/src/sgml/ref/create_cast.sgml                  |    6 +-
 doc/src/sgml/ref/create_collation.sgml             |   82 +-
 doc/src/sgml/ref/create_database.sgml              |   30 +-
 doc/src/sgml/ref/create_foreign_table.sgml         |   26 +
 doc/src/sgml/ref/create_function.sgml              |   16 +-
 doc/src/sgml/ref/create_group.sgml                 |    2 +-
 doc/src/sgml/ref/create_index.sgml                 |   31 +-
 doc/src/sgml/ref/create_language.sgml              |   15 +-
 doc/src/sgml/ref/create_opclass.sgml               |    5 +
 doc/src/sgml/ref/create_policy.sgml                |  224 +-
 doc/src/sgml/ref/create_publication.sgml           |  219 ++
 doc/src/sgml/ref/create_role.sgml                  |   42 +-
 doc/src/sgml/ref/create_schema.sgml                |    2 +-
 doc/src/sgml/ref/create_sequence.sgml              |   36 +-
 doc/src/sgml/ref/create_server.sgml                |   14 +-
 doc/src/sgml/ref/create_statistics.sgml            |  185 ++
 doc/src/sgml/ref/create_subscription.sgml          |  290 ++
 doc/src/sgml/ref/create_table.sgml                 |  358 +-
 doc/src/sgml/ref/create_transform.sgml             |   12 +-
 doc/src/sgml/ref/create_trigger.sgml               |  177 +-
 doc/src/sgml/ref/create_type.sgml                  |    2 +-
 doc/src/sgml/ref/create_user.sgml                  |    2 +-
 doc/src/sgml/ref/create_user_mapping.sgml          |   14 +-
 doc/src/sgml/ref/create_view.sgml                  |    7 +-
 doc/src/sgml/ref/createdb.sgml                     |    8 +-
 doc/src/sgml/ref/createlang.sgml                   |  291 --
 doc/src/sgml/ref/createuser.sgml                   |   21 +-
 doc/src/sgml/ref/delete.sgml                       |   11 +-
 doc/src/sgml/ref/drop_aggregate.sgml               |   10 +-
 doc/src/sgml/ref/drop_foreign_data_wrapper.sgml    |    2 +-
 doc/src/sgml/ref/drop_foreign_table.sgml           |    2 +-
 doc/src/sgml/ref/drop_function.sgml                |   41 +-
 doc/src/sgml/ref/drop_language.sgml                |    1 -
 doc/src/sgml/ref/drop_operator.sgml                |    8 +-
 doc/src/sgml/ref/drop_policy.sgml                  |    3 +-
 doc/src/sgml/ref/drop_publication.sgml             |  105 +
 doc/src/sgml/ref/drop_server.sgml                  |    2 +-
 doc/src/sgml/ref/drop_statistics.sgml              |   96 +
 doc/src/sgml/ref/drop_subscription.sgml            |  130 +
 doc/src/sgml/ref/droplang.sgml                     |  288 --
 doc/src/sgml/ref/explain.sgml                      |   16 +
 doc/src/sgml/ref/grant.sgml                        |   51 +-
 doc/src/sgml/ref/import_foreign_schema.sgml        |    4 +-
 doc/src/sgml/ref/initdb.sgml                       |   28 +-
 doc/src/sgml/ref/insert.sgml                       |   64 +-
 doc/src/sgml/ref/load.sgml                         |   11 +-
 doc/src/sgml/ref/pg_basebackup.sgml                |  154 +-
 doc/src/sgml/ref/pg_ctl-ref.sgml                   |  251 +-
 doc/src/sgml/ref/pg_dump.sgml                      |   86 +-
 doc/src/sgml/ref/pg_dumpall.sgml                   |   48 +
 .../{pg_receivexlog.sgml => pg_receivewal.sgml}    |   73 +-
 doc/src/sgml/ref/pg_recvlogical.sgml               |   40 +-
 .../ref/{pg_resetxlog.sgml => pg_resetwal.sgml}    |   56 +-
 doc/src/sgml/ref/pg_restore.sgml                   |   40 +-
 doc/src/sgml/ref/pg_rewind.sgml                    |    6 +-
 .../sgml/ref/{pg_xlogdump.sgml => pg_waldump.sgml} |   34 +-
 doc/src/sgml/ref/pgbench.sgml                      |  108 +-
 doc/src/sgml/ref/pgtestfsync.sgml                  |    6 +-
 doc/src/sgml/ref/pgtesttiming.sgml                 |   16 +-
 doc/src/sgml/ref/pgupgrade.sgml                    |  143 +-
 doc/src/sgml/ref/prepare.sgml                      |    2 +-
 doc/src/sgml/ref/psql-ref.sgml                     |  538 ++-
 doc/src/sgml/ref/reindexdb.sgml                    |    4 +-
 doc/src/sgml/ref/revoke.sgml                       |    2 +-
 doc/src/sgml/ref/security_label.sgml               |    4 +-
 doc/src/sgml/ref/set_transaction.sgml              |    6 +-
 doc/src/sgml/ref/truncate.sgml                     |    8 +
 doc/src/sgml/ref/update.sgml                       |   22 +-
 doc/src/sgml/ref/vacuum.sgml                       |    4 +-
 doc/src/sgml/ref/vacuumdb.sgml                     |    2 +-
 doc/src/sgml/reference.sgml                        |   17 +-
 doc/src/sgml/regress.sgml                          |   25 +-
 doc/src/sgml/release-10.sgml                       | 3498 ++++++++++++++++++++
 doc/src/sgml/release-7.4.sgml                      |   20 +-
 doc/src/sgml/release-8.0.sgml                      |   18 +-
 doc/src/sgml/release-8.1.sgml                      |   18 +-
 doc/src/sgml/release-8.2.sgml                      |    8 +-
 doc/src/sgml/release-8.3.sgml                      |    8 +-
 doc/src/sgml/release-8.4.sgml                      |   12 +-
 doc/src/sgml/release-9.0.sgml                      |    8 +-
 doc/src/sgml/release-9.1.sgml                      |    4 +-
 doc/src/sgml/release-9.2.sgml                      |   48 +-
 doc/src/sgml/release-9.3.sgml                      |   52 +-
 doc/src/sgml/release-9.4.sgml                      |   54 +-
 doc/src/sgml/release-9.5.sgml                      |   52 +-
 doc/src/sgml/release-9.6.sgml                      |   48 +-
 doc/src/sgml/release-old.sgml                      |   12 +-
 doc/src/sgml/release.sgml                          |    6 +-
 doc/src/sgml/runtime.sgml                          |  322 +-
 doc/src/sgml/sepgsql.sgml                          |    6 +-
 doc/src/sgml/spgist.sgml                           |   68 +-
 doc/src/sgml/spi.sgml                              |  510 ++-
 doc/src/sgml/sql.sgml                              | 2148 ------------
 doc/src/sgml/sslinfo.sgml                          |    4 +-
 doc/src/sgml/storage.sgml                          |   22 +-
 doc/src/sgml/syntax.sgml                           |   27 +-
 doc/src/sgml/test-decoding.sgml                    |    2 +-
 doc/src/sgml/textsearch.sgml                       |   83 -
 doc/src/sgml/trigger.sgml                          |  132 +-
 doc/src/sgml/tsearch2.sgml                         |  203 --
 doc/src/sgml/typeconv.sgml                         |   50 +-
 doc/src/sgml/user-manag.sgml                       |   36 +
 doc/src/sgml/uuid-ossp.sgml                        |    2 +-
 doc/src/sgml/wal.sgml                              |   32 +-
 doc/src/sgml/xfunc.sgml                            |  435 ++-
 doc/src/sgml/xindex.sgml                           |    2 +-
 doc/src/sgml/xml2.sgml                             |   10 +-
 doc/src/sgml/xplang.sgml                           |    9 +-

**Comment by KenichiroTanaka** [comment]
担当者リストのwikiです。

https://github.com/pgsql-jp/jpug-doc/wiki/ドキュメント翻訳担当リスト10

**Comment by smatsudajp** [comment]
予定通り、10.1がリリースされましたね。まずは気にせず、10.0を出すことに注力しますか。
変更されたファイルは以下。
charset.sgml
client-auth.sgml
maintenance.sgml
recovery-config.sgml
release-10.sgml
release-9.2.sgml
release-9.3.sgml
release-9.4.sgml
release-9.5.sgml
release-9.6.sgml
ref/grant.sgml
ref/prepare_transaction.sgml
リリースノート以外は大した修正ではないですが、リリースノートは追加分以外にタグが大幅に修正されていて、翻訳作業的には嫌な感じ。
パッと見、従来＜productname＞PostgreSQL＜／＞となっていた部分が、＜productname＞PostgreSQL＜／productname＞に変わっているみたいなのが大量にありますが、この修正、どういう意味があるのでしょうか。

**Comment by tatsuo-ishii** [comment]
このあたりの話ですね。
https://www.postgresql.org/message-id/flat/20171018.090908.1654875320266791258.t-ishii%40sraoss.co.jp#20171018.090908.1654875320266791258.t-ishii@sraoss.co.jp

**Comment by smatsudajp** [comment]
なるほど…遠くない将来、すべての＜／＞を＜／hoge＞に変える、ってことですか。
原文の変更点が終了タグの変更だけなのか、それ以外の変更があるのかを段落ごとに判別するツール、
訳文の＜／＞を自動的に＜／hoge＞に変換するツール、
が欲しいところですね。
そうでなくても、改版時の翻訳で、改行位置を変えただけなのか、語句の挿入・削除があるのかを確認するのに苦労しているので。

**Comment by tatsuo-ishii** [comment]
ツールについては、スレッドを追っていくと出てきます。

**Comment by koizumistr** [comment]
https://www.google.co.jp/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwiQwrH_yqHZAhWJv7wKHTBDAUcQFggvMAE&url=https%3A%2F%2Fwww.postgresql.org%2Fmessage-id%2Fattachment%2F50068%2Fsgml2xml.pl&usg=AOvVaw0h1iT-etMPFtMq4fvVZWkN
でしょうか。perlの5.10以上だったかが必要だったので、このためにperlの新しい版をインストールしました。

**Comment by koizumistr** [comment]
10.2とリンクしておくとちょっと嬉しいかな、と。
#1169

**Comment by koizumistr** [comment]
先ほど #1184 をマージしました。 #1182 の貢献者云々の話が残っていますが、訳としてはあれで10.0は終わりかな、と。

**Comment by koizumistr** [comment]
対象は #1180 に完全に移ったと思いますので、こちらはクローズします。
