### ISSUE TITLE
forward DNS lookup の訳し方 

### ISSUE THREAD

**Issue by pengbo0328** [pgsql-jp/jpug-doc#1026]
## 問題点

https://www.postgresql.jp/document/9.6/html/auth-pg-hba-conf.html

上記、「pg_hba.conf ファイル」の address レコードの翻訳について、

  forward DNS lookup => 正引きDNS検索

のほうが正しいと思います。

また、 「 both directions 」は逆引き、正引きの意味だと思います。

以下は、英語・日本語ドキュメントの内容です。

If there is a match, then a forward name resolution (e.g., forward DNS lookup) is performed on the host name to check whether any of the addresses it resolves to are equal to the client's IP address. If both directions match, then the entry is considered to match.

もし一致するものがあった場合は、解決された、どのアドレスもクライアントのIPアドレスと等しいか否かをチェックするために（例えば、前方一致のDNS検索のような）ホスト名の前方一致の名前解決が実行されます。 もし前方、後方の両方向で一致した場合は、エントリは一致するものとみなされます。

**Comment by smatsudajp** [comment]
報告ありがとうございます。
client-auth.sgmlですね。
現在、バージョン10の翻訳作業中なので、変更分の翻訳のついでに直すのが良いと思います。
9.6のマニュアルを修正して、再発行する余裕があるかどうかは別途検討。

**Comment by koizumistr** [comment]
#1176 で対応しました。あちらがマージされたのでこちらも完了。
