### ISSUE TITLE
26.2.6. レプリケーションスロットの誤訳

### ISSUE THREAD

**Issue by tom-sato** [pgsql-jp/jpug-doc#1029]
## 問題点

26.2.6. レプリケーションスロット
https://www.postgresql.jp/document/9.6/html/warm-standby.html#streaming-replication-slots

> In lieu of using replication slots, it is possible to prevent the removal of old WAL segments using wal_keep_segments, or by storing the segments in an archive using archive_command.
> レプリケーションスロットを使用しない場合、古いWALセグメントの削除を防ぐためには、wal_keep_segmentsを使用するか、アーカイブarchive_commandを使用します。

「アーカイブarchive_commandを使用します」という訳が誤っています。以下の訳でいかがでしょうか？

レプリケーションスロットを使用しない場合、wal_keep_segmentsを使用するか、archive_commandを使用してセグメントをアーカイブに格納することによって古いWALセグメントの削除を防ぐことが可能です。

**Comment by smatsudajp** [comment]
報告ありがとうございます。ソースはhigh-availability.sgmlです。
「使用しない場合」もちょっと違和感があります。直訳すると「レプリケーションスロットを使う代わりに、wal_keepsegmentsを使う、あるいはarchive_command...を使用してセグメントをアーカイブに保存することによっても、古いWALセグメントの削除を防ぐことができます」という感じかと思います。これで良いんじゃないかな…
また同じ段落の最後の文も誤訳してますね。
「現時点でレプリケーションスロットを使用する他の目的はありません（there is currently no way to do this using replication slots）」ですが、正しくは「現時点でレプリケーションスロットを使って同じことをする方法はありません」という感じです。

**Comment by tatsuo-ishii** [comment]
次の行で"often"が訳抜けしていますね。

次の段落の訳も微妙なので、まとめてpull requestを出しておきます。

**Comment by koizumistr** [comment]
#1181で対応されたので、こちらは閉じます。
