### ISSUE TITLE
dead tupleの訳について

### ISSUE THREAD

**Issue by koizumistr** [pgsql-jp/jpug-doc#1145]
## 問題点

dead tupleが

- 不要なタプル
- 無効なタプル
- dead（タプル）

と訳されているようです。

## 背景

pgstattuple.sgmlを訳していて気付きました。

## 解決方法

どれかに揃えるべきかと。

live tupleは「有効なタプル」と訳しているようなので、live<->deadで、有効<->無効が一番良いかなと思います。

## 注意点

there is no live tuple version
の場合はliveが修飾しているのはtupleではなかったりしますか？

**Comment by tatsuo-ishii** [comment]
「不要タプル」はちょっと意味が違うような気がしますし、やはり「無効タプル」ですかね。

"there is no live tuple version"では、lveが修飾しているのはversionだと思います。

**Comment by koizumistr** [comment]
デッドタプル
というのもあるようです。

**Comment by koizumistr** [comment]
- 論理的には削除されたが、物理的には（まだ）削除されていないタプル
- 更新されたために不要となったタプル

のことを dead tuple と言っているようですので、「不要」とか「削除された」とかは避けた方が良いのかな、と思いました。ということで「無効」の根拠が補強されたかな、と。

**Comment by KenichiroTanaka** [comment]
そうですね。私も無効なタプルが良いように思います。

**Comment by koizumistr** [comment]
#1172 がマージされましたのでこちらは完了ですね。
