### ISSUE TITLE
cipher suiteの訳について

### ISSUE THREAD

**Issue by koizumistr** [pgsql-jp/jpug-doc#1178]
## 問題点

cipher suiteの訳について、
- 暗号スイート
- 暗号スィート
の両方があります。

## 背景

本文書内では「暗号スィート」が多数派です。
が、世間的には「暗号スイート」の方が一般的かと思います。Googleによると
- "暗号スイート"		約 9,460 件
- "暗号スィート"	約 79 件
です。

## 解決方法

世間一般に合わせた方が良いのではないでしょうか。

## 注意点

suiteは他にもあるでしょうが、ここでは「暗号」スイートだけを問題にしています。

**Comment by tatsuo-ishii** [comment]
言語の発音に近いカタカナは「スウィート」だと思います。その点では、「スイート」も「スィート」も微妙に違う点では同じなので、多数派に合わせて「スイート」で良いと思います。

**Comment by koizumistr** [comment]
マージされましたのでクローズ。
