### ISSUE TITLE
userの訳語統一

### ISSUE THREAD

**Issue by ester41** [pgsql-jp/jpug-doc#1207]
## 問題点

userの訳語が統一されていません。

## 背景

$ grep -rn "ユーザ" ./ | wc -l
    2592
$ grep -rn "ユーザー" ./ | wc -l
    27
$

## 解決方法

http://www.jp.freebsd.org/man-jp/docs/guideline.html を確認すると、ユーザに寄せるべきかと思われます。

## 注意点

特になしです。

**Comment by koyhoge** [comment]
近年は単語末尾の長音は「ー」をつけるのが一般的になりつつあるという印象です。

http://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kijun/naikaku/gairai/honbun06.html
https://pc.watch.impress.co.jp/docs/2008/0725/ms.htm

**Comment by ester41** [comment]
調べてみました。
JISZ8301の付随書GのG.6.2.2に長音の記載がありますね。
http://kikakurui.com/z8/Z8301-2011-01.html
長音記号を付ける方が一般的ですが、
学術用語で統一が困難な場合は省略しても構わないそうです。

長音を除いた単語の調査を行ってみます。

**Comment by noborus** [comment]
#2617 で全体的な方針の話をしているので、こちらはクローズします。
