### ISSUE TITLE
queryの訳語統一

### ISSUE THREAD

**Issue by ester41** [pgsql-jp/jpug-doc#1208]
## 問題点

queryの訳語が統一されていません。

## 背景

$ grep -rn "クエリ" ./ | wc -l
    244
$ grep -rn "クエリー" ./ | wc -l
    24
$

## 解決方法

http://www.jp.freebsd.org/man-jp/docs/guideline.html を確認すると、クエリに寄せるべきかと思われます。

## 注意点

特になしです。

**Comment by koizumistr** [comment]
「問い合わせ」にするのが正しいのではという気もします。

**Comment by ester41** [comment]
例で1つ上げると、
https://github.com/pgsql-jp/jpug-doc/blob/doc_ja_10/doc/src/sgml/func4.sgml#L1857
の「パラレルクエリー」といったところが大半なので、「問い合わせ」に変換するのは合わない気がします。
#1207 で長音に合わせる方が良いのかもしれないとのことなので、このIssueはクローズ致します。
