### ISSUE TITLE
論理レプリケーションとロジカルレプリケーションの混在

### ISSUE THREAD

**Issue by nori-shinoda** [pgsql-jp/jpug-doc#1240]
## 問題点
 logical-replication.sgml 内で論理レプリケーションとロジカルレプリケーションが混在しています。
 下記１か所のみ「ロジカルレプリケーション」になっています。
 
## 解決方法
　現状「典型的なロジカルレプリケーションの利用例には、以下のようなものがあります。」
　修正「典型的な論理レプリケーションの利用例には、以下のようなものがあります。」

**Comment by tatsuo-ishii** [comment]
ありがとうございます。修正pull requestを出しておきました。

https://github.com/pgsql-jp/jpug-doc/pull/1243

**Comment by nori-shinoda** [comment]
対応ありがとうございます。
