### ISSUE TITLE
親テーブルに対する文レベルトリガの挙動の翻訳

### ISSUE THREAD

**Issue by azarakko** [pgsql-jp/jpug-doc#1325]
## 問題点

doc/src/sgml/trigger.sgml　より

~~~

<!--
    A statement that targets a parent table in an inheritance or partitioning
    hierarchy does not cause the statement-level triggers of affected child
    tables to be fired; only the parent table's statement-level triggers are
    fired.  However, row-level triggers of any affected child tables will be
    fired.
-->
継承あるいはパーティション階層において、親テーブルをターゲットとする文は、影響を受けた子テーブルの行レベルトリガを発動しません。
すなわち、親テーブルの行レベルトリガのみが発動します。
しかし、影響を受けた子テーブルの行レベルトリガは発動します。

~~~

上記訳文ですが、
以下訳文の方が正しいのではないでしょうか。

継承あるいはパーティション階層において、親テーブルをターゲットとする文は、影響を受けた子テーブルの**文**レベルトリガを発動しません。
すなわち、親テーブルの**文**レベルトリガのみが発動します。
しかし、影響を受けた子テーブルの行レベルトリガは発動します。

**Comment by harukat** [comment]
コメントありがとうございます。
これは指摘の通りですね。
修正適用を進めておきます。

**Comment by harukat** [comment]
本ご指摘の内容を反映いたしました。
ありがとうございます。issueをクローズします。

**Comment by KenichiroTanaka** [comment]
azarakkoさん
田中@JPUG-DOCです。

他にメールなどご連絡できる手段が無かったのでISSUESから失礼します。

PostgreSQLマニュアルへの名前掲載可否を確認したくご連絡しました。

PostgreSQLの普及において日本語ドキュメントは極めて重要です。
JPUG-DOCではドキュメントの翻訳運営に貢献いただいた方のお名前を
感謝の意を込めて記載しています。

記載のイメージは以下の通りです。

https://www.postgresql.jp/document/pg10doc/html/jpug-doc.html

そこでJPUG-DOCではTYPOの報告も重要な貢献と考え、お名前をマニュアルへ
記載したいと考えています。

もし、よろしければ下記のwikiを直接編集いただくか、本ISSUESへコメントを
いただけませんでしょうか。

・記載するお名前
・会社名を付与される場合は会社名

https://github.com/pgsql-jp/jpug-doc/wiki/ドキュメント翻訳担当リスト11#貢献者リスト

会社名を付与する場合は会社への確認も併せてお願いします。

お忙しいと思いますがお返事をお待ちしています。
