### ISSUE TITLE
synchronous_standby_names の説明で typo

### ISSUE THREAD

**Issue by hotta** [pgsql-jp/jpug-doc#1387]
## 重要度: （低）（高/中/低から選んでください）

低

## 問題点

https://www.postgresql.jp/document/10/html/runtime-config-replication.html#GUC-SYNCHRONOUS-STANDBY-NAMES

２パラグラフ目に typo がありましたのでご報告します。

s/サブスクリプションの接続情報でで設定でき/サブスクリプションの接続情報で設定でき/

**Comment by koizumistr** [comment]
指摘ありがとうございます。「でで」というのがもう一か所ありましたので、併せて #1403 で 修正してみました。

**Comment by noborus** [comment]
マージされているので、クローズさせて頂きます。
