### ISSUE TITLE
「9.26.3 バックアップ制御関数」関数名の誤植

### ISSUE THREAD

**Issue by nori-shinoda** [pgsql-jp/jpug-doc#1453]
## 問題点
9.26.3 の冒頭に「・・・およびpg_wal_location_diffは除く」とありますが、
「・・・およびpg_wal_lsn_diffは除く」の間違いと思われます。

## 背景
PostgreSQL 10で関数名が変更された分の修正漏れと思われます。

## 解決方法
「pg_wal_lsn_diffは除く」に変更します。

## 注意点
　なし

**Comment by tatsuo-ishii** [comment]
ご指摘ありがとうございます。pull request 1454で対応しました。

**Comment by koizumistr** [comment]
#1454 
リンクにしてみました。
