### ISSUE TITLE
コンパイルが遅い

### ISSUE THREAD

**Issue by tatsuo-ishii** [pgsql-jp/jpug-doc#1463]
## 問題点

PostgreSQL 11からコンパイルが高速になり、日本語ドキュメントのコンパイルの遅さがだいぶ目立つようになりました。

手元の環境では、

PostgreSQL オリジナル: 0:34
日本語マニュアル: 3:23

と大差が出ています。30秒台とは言いませんが、せめて1分以内くらいだと嬉しいですね。

## 解決方法

XMLに移行？

**Comment by noborus** [comment]
#1465 で対応してみました。

3分の1ぐらいになったと思いますが、何故かfooterの処理時間が掛かっているので、必要なければ
```
make "XSLTPROCFLAGS= --stringparam  suppress.footer.navigation '1'"
```
で抑制するとさらに早くなります（リリース時は必要だと思いますのでデフォルトでは抑制していません）。

以下解説。
既に全部XMLになっていて、xsltproc の実行時間がほぼ全てです。
xsltproc は --profile を付けて実行するとプロファイルがとれます。
```
/usr/bin/xsltproc --profile --path . --stringparam pg.version '11.1'  stylesheet.xsl postgres.sgml 2>xprof-ja.log
```
これでオリジナルと比較してみたら href.targetの処理時間に大幅に違いがありました。
そこで範囲を絞って特定して置き換えています。
HTMLの結果のdiffには違いは出ませんでした。
同様にfooter.navigationが遅いですが、これはdocbookのデフォルトのまま使用しているので、元がローカライズすると遅くなるのだと思います。

**Comment by tatsuo-ishii** [comment]
#1465で1:16位になりました。助かります！

**Comment by KenichiroTanaka** [comment]
#1465 でかなり早くなったと思います。斉藤さんありがとうございました。
現時点バージョンでひとまず十分だと思います。
本Isuusesはクローズします。（もし,クローズNGでしたら再オープンください）
