### ISSUE TITLE
"speculative"の訳語

### ISSUE THREAD

**Issue by tatsuo-ishii** [pgsql-jp/jpug-doc#1471]
## 問題点

「表28.4 wait_eventの説明」で

28.2 speculative token | 推論的挿入ロックを獲得するのを待っています。

と、speculativeを「推論的」と訳していますが、これは「投機的」の間違いではないでしょうか？もともとこれは、INSERT ... ON CONFLICT DO UPDATEの文脈で使われるロックの話で、
「とりあえずINSERTしてみて失敗したらUPDATEする」という機能に関連していることを考えると、speculativeは「投機的」と訳すのが適当と思います。

**Comment by koizumistr** [comment]
speculativeは他の所ではどう訳しているのかな、と思ったのですが、ここでしか出てきていないんですよねぇ。

**Comment by koizumistr** [comment]
対応するPRはマージ済みですので、クローズします。
