### ISSUE TITLE
config.sgmlに未翻訳のブロックがありました。

### ISSUE THREAD

**Issue by noborus** [pgsql-jp/jpug-doc#1515]
## 問題点

https://github.com/pgsql-jp/jpug-doc/blob/7d3728e83614cd0f0d4c91b0aad98ab717f3f28b/doc/src/sgml/config3.sgml#L128-L150

からのブロックが未翻訳で見逃されていました。

**Comment by tatsuo-ishii** [comment]
済みません。 #1518で対応しました、

**Comment by noborus** [comment]
対応ありがとうございました。クローズします。
