### ISSUE TITLE
xlog から wal への翻訳漏れ

### ISSUE THREAD

**Issue by nori-shinoda** [pgsql-jp/jpug-doc#1533]
## 問題点
　以下の２点は PostgreSQL 10  による xlog から wal への変換漏れと思われます。

　25.3.1. 
      pg_switch_xlogを使用して手作業でセグメント切り替え 
　（原文：　Also, you can force a segment switch manually with pg_switch_wal）
      ↓
      pg_switch_xlogを使用して手作業でセグメント切り替え

   53.4
      次の列は切り替えたXLOGの位置(text型)です。
　（原文：　and the second column is the WAL location where the switch happened (type text). ）
      ↓
      次の列は切り替えたWALの位置(text型)です。

**Comment by noborus** [comment]
ありがとうございます。 #1535 で修正しました。
修正の反映までは少し時間がかかります。
