### ISSUE TITLE
typo：pg_resetwalの記述にpg_clogが残っている

### ISSUE THREAD

**Issue by U-ikki** [pgsql-jp/jpug-doc#1544]
## 問題点
https://github.com/pgsql-jp/jpug-doc/blob/doc_ja_11_4/doc/src/sgml/ref/pg_resetwal.sgml
`pg_xact`への修正が漏れており、`pg_clog`のままになっている。
リポジトリで検索したが、該当箇所はpg_resetwalのみでした。

なお、本家のページは修正されているので、日本語版のみの問題です。

## 背景

省略

## 解決方法

省略

## 注意点

省略

**Comment by KenichiroTanaka** [comment]
Ueharaさん、ご報告ありがとうございます。
ご指摘の通りですので修正します。

**Comment by KenichiroTanaka** [comment]
以下のPRを出しています。
https://github.com/pgsql-jp/jpug-doc/pull/1545

**Comment by koizumistr** [comment]
#1545 がマージされましたのでクローズします。

報告ありがとうございました。

**Comment by KenichiroTanaka** [comment]
Kazuki Ueharaさん

田中@JPUG-DOCです。

他にメールなどご連絡できる手段が無かったのでISSUESから失礼します。

PostgreSQLマニュアルへの名前掲載可否を確認したくご連絡しました。

PostgreSQLの普及において日本語ドキュメントは極めて重要です。
JPUG-DOCではドキュメントの翻訳運営に貢献いただいた方のお名前を
感謝の意を込めて記載しています。

記載のイメージは以下の通りです。

https://www.postgresql.jp/document/pg10doc/html/jpug-doc.html

JPUG-DOCでは今回指摘いただいた記載ミスの報告も重要な貢献と考え、お名前を
マニュアルへ記載したいと考えています。

もし、よろしければ下記のwikiを直接編集いただくか、本ISSUESへコメントを
いただけませんでしょうか。

・記載するお名前
・会社名を付与される場合は会社名

https://github.com/pgsql-jp/jpug-doc/wiki/ドキュメント翻訳担当リスト11#貢献者リスト

会社名を付与する場合は会社への確認も併せてお願いします。

お忙しいと思いますがお返事をお待ちしています。

**Comment by U-ikki** [comment]
田中さま

ご連絡ありがとうございます。
wikiを直接編集させていただきました。

PostgreSQL文書は、いつも利用させていただくばかりでしたが、少しでもお役に立つことができてよかったです。

**Comment by KenichiroTanaka** [comment]
早速のご連絡ありがとうございました。
いただいている内容で11.5公開時に掲載させていただきます。

また、PostgreSQL12の翻訳もそろそろ始まりますので、もし、
よろしければご参加ください。
