### ISSUE TITLE
図中に出てくる単語の本文側の翻訳

### ISSUE THREAD

**Issue by KenichiroTanaka** [pgsql-jp/jpug-doc#1563]
## 問題点
図に日本語を加えることは難しいので行わない方針だったと思いますが、マニュアル本文で図で使われている用語を（）で書くかを議論したいです。

## 背景
PostgreSQL12よりマニュアルに図が含まれるようになりました。
例）
https://www.postgresql.org/docs/12/gin-implementation.html

## 解決方法

A.図があるページでは必ず図に出てくる単語は（）で記載する
　→該当のドキュメントに図があることや、（）で記載すべき単語をチェックする方法はあるのか？

B.翻訳者の気付いた限り（）で記載する
　→統一感が無くなる。場合によっては混乱を招く？

C.（）で原文を記載する対応は行わない
　→ドキュメントとして不親切？

と３案くらい思いつきました。
方針は揃えておく必要があると思います。

## 注意点
（注意点、懸念事項を書いてください）

**Comment by harukat** [comment]
ひとまず B. で良いのではないでしょうか。
翻訳者が参入しやすくするためにも「こうしなければならない」は減らしたいので。
統一感、一貫性に類する対応は後から一括して行えば良いですし。

**Comment by tatsuo-ishii** [comment]
Cに一票。元々図に書き込めるテキストの量は限られているので、翻訳がなくても十分わかると思います。もし図に書き込むテキストが増えてきたら、それは原文に移動するはずで、そうしないのだとしたらそれは翻訳ではなく原文の問題であり、「わかりにくい」などのフィードバックを本家にコミュニティに行うべき。

**Comment by harukat** [comment]
これは、図中に pending list と書かれている場合に、本文で「新しいタプルを、待機中の項目リスト（pending list）に挿入します。」と書くという話ですよね？

**Comment by tatsuo-ishii** [comment]
> これは、図中に pending list と書かれている場合に、本文で「新しいタプルを、待機中の項目リスト（pending list）に挿入します。」と書くという話ですよね？
そうなんですか？図中に(コメント)を入れる話かと思っていました。
もしそうなら、Bに賛成です。

**Comment by noborus** [comment]
>> これは、図中に pending list と書かれている場合に、本文で「新しいタプルを、待機中の項目リスト（pending list）に挿入します。」と書くという話ですよね？

> そうなんですか？図中に(コメント)を入れる話かと思っていました。
> もしそうなら、Bに賛成です。

はい。今回、図が追加されたので、本文は変更されていなかったですが、本文に図中の用語を補った変更を入れました。

「図に出てくる用語を必ず（）で記載する。」と言うよりは、
「図にしか出てこない用語がある場合に、その用語が本文で別の用語を使用していた場合には、同じものを指していることが分かるように（）で補うべし」
ということでルール化すべきと思っています。

ルール化といっても気づいた人が気づいた時に、「図にしかない用語だから（）入れてね♡」と指摘しましょうと言う話です。

**Comment by KenichiroTanaka** [comment]
みなさま、コメントありがとうございます。
私もBが良いと思いますので、ひとまず、こちらの方針で進めましょう。

**Comment by koizumistr** [comment]
すみません。UEFIを誤爆してOSの再インストールに手こずっていていたので、完全に出遅れました。反対意見はないです。


> もし図に書き込むテキストが増えてきたら、それは原文に移動するはずで、そうしないのだとしたらそれは翻訳ではなく原文の問題であり、「わかりにくい」などのフィードバックを本家にコミュニティに行うべき。

これはこれで別の話なのだと思いますが、その通りだと思います。図中にだけある文字列は検索できないですし。

**Comment by KenichiroTanaka** [comment]
小泉さん、コメントありがとうございます。
皆様にひと通りご意見いただけましたので方針Bとして
このissuesはクローズします。
