### ISSUE TITLE
PDF、EPUB版の公開

### ISSUE THREAD

**Issue by noborus** [pgsql-jp/jpug-doc#157]
## 背景

9.1まで ( http://www.postgresql.jp/document/9.1/index.html )は、PDF版も公開されていましたが、現在は公開されていません。
ビルドに必要な環境を整えれば、現在はPDF版、EPUB版のビルドが可能になっています。

## 問題点

オフラインでの使用等PDFやEPUBの方が適している場合もあります。

## 解決方法

環境を整えPDF版、EPUB版を公開出来るようにする。

**Comment by noborus** [comment]
PDF、EPUBは作成できていますが、PDFの改善をする PR #526 を送りました。 
作成したサンプルは以下です。
PDF
http://noborus.github.io/pgsql-jp/jpug-doc/9.5.1/pdf/postgresql-9.5-A4-fop.pdf
EPUB
http://noborus.github.io/pgsql-jp/jpug-doc/9.5.1/epub/postgresql-9.5.epub

**Comment by noborus** [comment]
PDF改善がマージされたので、公開場所が用意されればcloseします。

とりあえず
https://pgsql-jp.github.io/jpug-doc/9.5.1/
に置こうかと思ってますが、どうでしょうか？

また、ファイル名はどうしましょうか？
本家では postgresql-9.5-A4.pdf となっているようですが。9.5.1にして置きましょうか？

**Comment by tatsuo-ishii** [comment]
postgresql-9.5.1-A4.pdf に一票。

**Comment by KenichiroTanaka** [comment]
>とりあえず
>https://pgsql-jp.github.io/jpug-doc/9.5.1/
>に置こうかと思ってますが、どうでしょうか？

はい、ひとまず上記によろしくお願いします。

また、ファイル名は石井さんからもいただいているとおりpostgresql-9.5.1-A4.pdf で良いと思います。

**Comment by noborus** [comment]
了解しました。ありがとうございます。以下に置きました。

## PDF
https://pgsql-jp.github.io/jpug-doc/9.5.1/postgresql-9.5.1-A4.pdf

## EPUB
https://pgsql-jp.github.io/jpug-doc/9.5.1/postgresql-9.5.1.epub

**Comment by noborus** [comment]
公開されていました。ありがとうございます。
CLOSEします。
