### ISSUE TITLE
対訳集のGit管理

### ISSUE THREAD

**Issue by noborus** [pgsql-jp/jpug-doc#158]
## 背景

翻訳の用語をなるべく統一するように用語集がwikiで管理されていたが、GitHubのGitでの管理にして欲しい。

## 問題点

wikiサイトを見にいく必要があり、ツールで使用したい場合は保存して加工する必要があり、使用しづらい

## 解決方法

GitHubに用語集のレポジトリを作成し、一般的なフォーマット(候補:CSV)で管理する。

**Comment by KenichiroTanaka** [comment]
現在リポジトリ作成依頼の再打診を行っています。

**Comment by KenichiroTanaka** [comment]
以下のgitリポジトリを作成してもらいました。

https://github.com/pgsql-jp/taiyaku

以降、対訳に関するissueはこちらのリポジトリで管理しましょう。
チケットはクローズしようと思います。
