### ISSUE TITLE
ソースコードのトップにREADME.mdを用意する

### ISSUE THREAD

**Issue by noborus** [pgsql-jp/jpug-doc#159]
## 背景

https://github.com/pgsql-jp/jpug-doc/ には、本家のREADMEが表示されているが、日本語ドキュメントの説明が表示されている方が望ましい。

## 問題点

* 本家のREADMEが表示されいて誤解されかねない
* 日本語ドキュメントの説明がない

## 解決方法

README.mdを用意してソースコードのトップに追加する。

**Comment by KenichiroTanaka** [comment]
README.md 案です。



#PostgreSQLドキュメントの日本語翻訳プロジェクト

本リポジトリは日本PostgreSQLユーザ会の文書・書籍分科会で活動している
PostgreSQLの日本語への翻訳を行っているプロジェクトのリポジトリです。

##初めて参加される方はこちらをご覧ください。
https://github.com/pgsql-jp/jpug-doc/wiki/JPUG-DOCの翻訳活1動への参加方法(初めての方向け)

##関連リポジトリ

*対訳表
本プロジェクトの公式対訳表です。

https://github.com/pgsql-jp/taiyaku

**Comment by koizumistr** [comment]
つまらないことですが、
https://github.com/pgsql-jp/jpug-doc/wiki/JPUG-DOCの翻訳活1動への参加方法(初めての方向け)
ではなく
https://github.com/pgsql-jp/jpug-doc/wiki/JPUG-DOCの翻訳活動への参加方法(初めての方向け)
なのではないかと。

**Comment by koizumistr** [comment]
#PostgreSQL文書の日本語翻訳プロジェクト
← PostgreSQL X.X.X文書 となっていますので

本リポジトリは**PostgreSQL**（← http://www.postgresql.org/ へのリンクにする）の**文書**（← http://www.postgresql.org/docs/manuals/ へのリンクにする）を**日本語に翻訳**（←  http://www.postgresql.jp/document/ へのリンクにする）しているプロジェクトのリポジトリです。
このプロジェクトは**日本PostgreSQLユーザ会**（← http://www.postgresql.jp/ へのリンクにする）の**文書・書籍分科会**（← http://www.postgresql.jp/wg/jpugdoc/ へのリンクにする）の活動の一つです。

な感じでしょうか。
この後に、「皆さん、是非参加してください」とか入れたいところですけど。で、初めて参加される方はにつなげる、と。

**Comment by koizumistr** [comment]
ふと思ったのですが、ここのWikiのHome（https://github.com/pgsql-jp/jpug-doc/wiki）にも同じような記載をしたらどうでしょうか。

**Comment by KenichiroTanaka** [comment]
ありがとうございます。

全部いただきます。

**Comment by KenichiroTanaka** [comment]
ひとまずwiki側に登録してみました。

https://github.com/pgsql-jp/jpug-doc/wiki

**Comment by KenichiroTanaka** [comment]
https://github.com/pgsql-jp/jpug-doc/pull/461
でPR作成

**Comment by koizumistr** [comment]
#461 にコメントしました。wiki側については指摘はないです。

**Comment by KenichiroTanaka** [comment]
PRをマージしたのでCLOSEします。
