### ISSUE TITLE
CREATE TABLE文 PARTITION BY 句の説明部分

### ISSUE THREAD

**Issue by nori-shinoda** [pgsql-jp/jpug-doc#1596]
## 問題点
ref/create_table.sgml のPARTITION BY の説明部分が以下の状態になっています。

下記日本語は PostgreSQL 10 の説明のように見えます。

> オプションの<literal>PARTITION BY</literal>句により、テーブルのパーティショニングの戦略を指定できます。

一方で PostgreSQL 11 の英文がコメントアウトされずにそのまま出力されています。

> Range and list partitioning require a btree ...

**Comment by noborus** [comment]
ご指摘ありがとうございます。

遅くなりましたが、12の方で修正されるように作業中です。
 #1652

**Comment by nori-shinoda** [comment]
ありがとうございます。よろしくお願いします。

**Comment by noborus** [comment]
12.0で修正されて公開されていますのでクローズします。
ありがとうございました。
