### ISSUE TITLE
12.2対応を目指して

### ISSUE THREAD

**Issue by koizumistr** [pgsql-jp/jpug-doc#1636]
## 問題点
REL_12_2のタグが打たれました。12対応が終わったら12.1をとばして、12.2対応をするべきかと。

## 背景

（報告の理由、根拠を書いてください）

## 解決方法

（解決方法を書いてください）

## 注意点

（注意点、懸念事項を書いてください）

**Comment by koizumistr** [comment]
git diff --stat REL_12_0 REL_12_2 doc/src/sgml/はこんな感じです。

bgworker.sgml                      |    2 +-
bloom.sgml                         |    4 +-
catalogs.sgml                      |   48 +-
client-auth.sgml                   |  134 +-
config.sgml                        |  397 ++--
datatype.sgml                      |    8 +-
ddl.sgml                           |  102 +-
extend.sgml                        |    2 +-
func.sgml                          |    9 +-
high-availability.sgml             |    8 +-
indices.sgml                       |   19 +
legal.sgml                         |    6 +-
libpq.sgml                         |    8 +-
monitoring.sgml                    |    8 +-
parallel.sgml                      |    4 +-
perform.sgml                       |   19 +-
postgres-fdw.sgml                  |    6 +
rangetypes.sgml                    |   37 +-
ref/alter_default_privileges.sgml  |   30 +-
ref/alter_subscription.sgml        |    3 +-
ref/alter_table.sgml               |   42 +-
ref/copy.sgml                      |   34 +-
ref/create_index.sgml              |    5 +
ref/create_table.sgml              |    2 +
ref/drop_index.sgml                |    5 +
ref/insert.sgml                    |    2 +-
ref/prepare.sgml                   |    2 +-
ref/refresh_materialized_view.sgml |    4 +-
ref/reindex.sgml                   |    5 +
ref/security_label.sgml            |    2 +-
ref/select.sgml                    |    8 +
ref/set_role.sgml                  |    2 +-
ref/truncate.sgml                  |    3 +
release-12.sgml                    | 2591 ++++++++++++++++++++++-
rules.sgml                         |   32 +-
runtime.sgml                       |    5 +-
trigger.sgml                       |   18 +-

**Comment by KenichiroTanaka** [comment]
私も12.1を飛ばして12.2に対応する、で良いと思います。
diffの結果共有ありがとうございます。

**Comment by KenichiroTanaka** [comment]
12.3が5/14に出る予定です。
12.2も飛ばして12.3スタートでどうでしょうか。

**Comment by koizumistr** [comment]
はい、（12.3がそのくらいの時期に出るのなら）12.3が出たら12.3の訳に着手でいいと思います。
私も10日弱で12.2をやるほど、12.2に強い思い入れがあるわけではありませんので。

**Comment by koizumistr** [comment]
#1668 を立てましたので、こちらは閉じてしまいます。
