### ISSUE TITLE
version 12.0                       planner-stats.html

### ISSUE THREAD

**Issue by sakata-tetsuo** [pgsql-jp/jpug-doc#1637]
## 問題点
以下の原文に対する訳に不備があると思います。

> When estimating with functional dependencies, the planner assumes that conditions on the involved columns are compatible and hence redundant. 

> 関数従属性による見積もりでは、プランナは関係する列は両立で、冗長であると見なします。 

## 背景

- 原文にある conditions が訳文では落ちているので、compatible (両立と訳している)の意味が伝わらない
- 同じく hence が訳出されていない

## 解決方法

conditions と hence とを入れた、以下のような訳文が良いと思われる。

> 関数従属性を含めた(コスト)見積もりでは、プランナは複数の条件(式)が同時に成り立つ、つまり冗長であるとみなします。それらの条件が同時に成り立たなければ、正しい見積もり(値)は0行となりますが、その可能性は考慮されません。

## 注意点

（注意点、懸念事項を書いてください）

- 訳語を変えたことにより、指摘箇所の次の文も修正が必要となります。上記の訳例を見てください

**Comment by tatsuo-ishii** [comment]
ご指摘ありがとうございます。ただ、提案の訳文では原文にある"on the involved columns"が訳出されていないので、以下のような訳ではいかがでしょう？

関数従属性を含めた(コスト)見積もりでは、プランナは関係する列に対する複数の条件(式)が同時に成り立つ、つまり冗長であるとみなします。

**Comment by sakata-tetsuo** [comment]
検討いただき、ありがとうございました。
ご指摘のとおり、改善案では"on the involved columns"が落ちていましたので、石井さんがお書きになった訳文の方が良いと思います。

また、『(コスト)』と『(式)』のように括弧を付けて補った箇所については、§14.2全体を見回してみると他の箇所では使われていません。無いほうが訳文として一貫していますから、落としたほうが良いと考えます。

**Comment by tatsuo-ishii** [comment]
では以下で修正します。

関数従属性を含めた見積もりでは、プランナは関係する列に対する複数の条件が同時に成り立つ、つまり冗長であるとみなします。

**Comment by sakata-tetsuo** [comment]
石井さま、
文案の修正＆コミット、ありがとうございます。
きれいに修正していただいたので、本Issueはクローズします。
