### ISSUE TITLE
version 12.0                       planner-stats.html

### ISSUE THREAD

**Issue by sakata-tetsuo** [pgsql-jp/jpug-doc#1638]
## 問題点

14.2.2.2. 多変量N個別値計数　における、以下の訳文が誤訳に見えます。

- 原文： Estimates of the number of distinct values when combining more than one column 
- 訳文：一つ以上の列を組み合わせての異なる値の数の見積もりは、

## 背景

"more than one column"は「一つ以上の列」ではなく、「1つより多い列」の意味になります。

## 解決方法

例えば、以下のように訳します。

> 二つ以上の列を組み合わせての異なる値の数の見積もりは、

## 注意点

（注意点、懸念事項を書いてください）

上記の訳例は、「二つ以上」という意訳になっていますので、ドキュメント翻訳の全体的な方針が直訳であれば、適宜見直す必要があります。

**Comment by tatsuo-ishii** [comment]
ご指摘ありがとうございます。ご提案の訳でpull requestを出しておきます。

**Comment by sakata-tetsuo** [comment]
返信、ありがとうございます。PRを出してくださるとのこと、承知しました。
このissueとしては、クローズします。引き続き、よろしくお願いいたします。
