### ISSUE TITLE
accessorの訳語

### ISSUE THREAD

**Issue by noborus** [pgsql-jp/jpug-doc#1656]
## 問題点

accessor の訳語が統一されていない
主に「accessor operators」

* func.sgmlでは「アクセッサ演算子」
* json.sgmlでは「アクセサ演算子」

参考にlibpqでは accessor functionsは「アクセス用関数」

## 背景

12.0で追加された分が揃ってなかった

## 解決方法

「accessor operators」については統一したい。

**Comment by tatsuo-ishii** [comment]
Google検索の結果を見ると、圧倒的に「アクセサ」が多いですね(224万 vs. 34万)。アクセサで良いと思います。

**Comment by koizumistr** [comment]
どちらか一方に思い入れがある訳でないですが、"アクセッサ演算子"で検索するとfunc.sgmlがほぼ唯一の例のようです、、、

ということで、石井さんと同じくアクセサに一票。

**Comment by noborus** [comment]
石井さん、小泉さんありがとうございます。
では、json.sgmlはpull requestのままにして、func.sgmlの方を修正します。
