### ISSUE TITLE
これから先のリリースでは tag ではなく branch にしませんか?

### ISSUE THREAD

**Issue by koyhoge** [pgsql-jp/jpug-doc#167]
現在 pg943doc を本番環境に配置する作業を行っていますが、現状の pg943doc tag のものでは不具合がいくつかあることが分かりました。この場合 tag になっていると、それに対する修正をコミットできないので、今後のリリースでは tag ではなく branch にして欲しいです。

**Comment by noborus** [comment]
tagからbranchを新たに作成することで対応出来ないでしょうか？
```
$ git branch ブランチ名 タグ名
```
もし修正が必要になった場合は、tagからさかのぼってbranchを作成すればよいので、あらかじめbranchを作成していなくても大丈夫と考えていました。
これで対応出来ない場合はあらかじめbranchにしておく運用にしておく必要がありますね。

**Comment by koyhoge** [comment]
あーなるほど、修正が必要になったときにはじめて branch にすれば良いという方針だったのですね。それならそれでも良いかなぁ。

**Comment by koyhoge** [comment]
ということでクローズ。
