### ISSUE TITLE
microsecondsの訳がミリ秒になっている

### ISSUE THREAD

**Issue by HUUTFJ** [pgsql-jp/jpug-doc#1712]
## 問題点

pgbenchのページ内に存在する「トランザクション毎のログ処理」の章において、以下の文章の翻訳が間違っています。

>  timeはトランザクションの合計消費時間をミリ秒単位で示します。

ミリ秒単位で出力されると記載されていますが、実際はマイクロ秒単位で出力されます。

## 背景

原文は以下のようになっています：

> time is the total elapsed transaction time in microseconds, 

また`pgbench.c`を確認したところ、`INSTR_TIME_GET_MICROSEC()`を用いてトランザクション毎のレイテンシを計算しています（3565行目あたり）。

## 解決方法

上記文章で「ミリ秒」としているところを「マイクロ秒」に変更してください。

**Comment by noborus** [comment]
報告ありがとうございます。
#1714 で修正を送りました。
