### ISSUE TITLE
JPUG公開HTML版に不要なファイルが存在する

### ISSUE THREAD

**Issue by oknj** [pgsql-jp/jpug-doc#1723]
## 問題点

PostgreSQL12の日本語ドキュメントに11以前のページが残っています。
https://www.postgresql.jp/document/12/html/recovery-config.html

11以前のドキュメントから、右上の「他のバージョンの文書」ナビを使うことで到達することができます。
12のドキュメントの目次などからは到達できないようです。

**Comment by KenichiroTanaka** [comment]
反応が遅くなり申し訳ないです。
確かに旧バージョンのドキュメントが残っているようです。
対応します。

**Comment by KenichiroTanaka** [comment]
他にも以下のファイルが残っていましたので削除しました。
ご指摘ありがとうございました。

archive-recovery-settings.html
pgverifychecksums.html
recovery-config.html
recovery-target-settings.htmla
standby-settings.html

**Comment by KenichiroTanaka** [comment]
大塚さん
田中です。

メールアドレスが分からなかったのでISSUESから失礼します。

日本語ドキュメント改善にご協力頂きありがとうございます。
本バージョンの翻訳活動期間中にISSUES/PRをいただきましたので
PostgreSQL12に貢献いただいた方としてお名前を掲載させて頂きたいと考えています。

もし、よろしければ本メールへご返信をお願いします。

また、掲載内容（所属）について以前の内容と異なる場合はその旨お知らせください。

お忙しいと思いますがお返事をお待ちしています。
以上です。

**Comment by oknj** [comment]
ご対応いただき、ありがとうございました。
貢献者への掲載内容については、個別にメールいたしました。
よろしくおねがいします。

**Comment by KenichiroTanaka** [comment]
返信ありがとうございます。
一通り対応が完了しましたので本issueはクローズします。
