### ISSUE TITLE
不要なisが残っている

### ISSUE THREAD

**Issue by KuroHaya** [pgsql-jp/jpug-doc#1779]
## 問題点

9.25.の表9.63において、関数`pg_jit_available()`の説明が以下のようになっています。冒頭のisは不要ではないでしょうか？

```
is JITコンパイルがこのセッションで可能か？(第31章参照) jitがfalseなら、falseを返します。
```

## 背景

一つ上の行では冒頭にisがついていません。

```
pg_is_other_temp_schema(oid) | boolean | スキーマが他のセッションの一時スキーマかどうか？
```

## 解決方法

冒頭のisを削除してください。

**Comment by noborus** [comment]
ご報告ありがとうございます。

この問題は現在作業中の 12.4の変更と共に修正されていました。
https://github.com/pgsql-jp/jpug-doc/pull/1765/files

**Comment by KuroHaya** [comment]
確認しました。こちらはcloseとしておきます。
