### ISSUE TITLE
PQserverVersionにおいて<synopsis>タグの場所がずれている

### ISSUE THREAD

**Issue by HUUTFJ** [pgsql-jp/jpug-doc#1967]
## 問題点

ページ「状態接続関数」内の`PQserverVersion`に関するページがインライン表記？になっています。

https://www.postgresql.jp/document/12/html/libpq-status.html

ソースを確認したところ、この関数の説明だけ\<synopsis>内に記載されていました。

```sgml
<synopsis>
サーバのバージョンの整数表現を返します。
int PQserverVersion(const PGconn *conn);
</synopsis>
```

https://github.com/pgsql-jp/jpug-doc/blob/doc_ja_13/doc/src/sgml/libpq.sgml#L3053

念のため大元のマニュアルを確認しましたが、説明は\<synopsis>タグの外に記載されています。

```sgml
      <para>
       Returns an integer representing the server version.
<synopsis>
int PQserverVersion(const PGconn *conn);
</synopsis>
```

https://github.com/postgres/postgres/blob/master/doc/src/sgml/libpq.sgml#L2346

## 背景

PostgreSQL 12版マニュアルを読んでいた際に表示がおかしいことに気が付きました。

## 解決方法

関数に関する説明を\<synopsis>タグから外すべきだと思います。

```sgml
サーバのバージョンの整数表現を返します。

<synopsis>
int PQserverVersion(const PGconn *conn);
</synopsis>
````

**Comment by KenichiroTanaka** [comment]
ご指摘ありがとうございます。
いただいる通りタグのミスです。修正します。

**Comment by KenichiroTanaka** [comment]
ドキュメント不備のご指摘をいただきありがとうございました。
もし、よろしければドキュメント品質向上に貢献された方としてお名前をPostgreSQL13のドキュメントに
記載させていただければと考えています。

よろしければ下記のwikiを直接編集いただくか、本ISSUESへ返信を
いただけませんでしょうか。

・記載するお名前
・会社名を付与される場合は会社名

https://github.com/pgsql-jp/jpug-doc/wiki/ドキュメント翻訳担当リスト13.1#貢献者リスト

会社名を付与する場合は会社への確認も併せてお願いします。

**Comment by KenichiroTanaka** [comment]
ドキュメントの修正はマージされましたのでクローズします。
※HUUTFJさん、引き続きお名前掲載の件はご連絡をお待ちしています。
