### ISSUE TITLE
log_line_prefixの翻訳に一部誤り？

### ISSUE THREAD

**Issue by HUUTFJ** [pgsql-jp/jpug-doc#2007]
## 問題点

log_line_prefixの解説に「オプション名の%の後か前に数字を指定することにより」とありますが、パディングの大きさを指定する場合には%とオプション名の間に数値を入れないとダメだと思います。

> 状態情報はオプション名の%の後か前に数字を指定することにより、左寄せまた右寄せにすることができます。 数字が負ならば状態情報を右側に空白を詰めて最小限の幅にし、正の値は左に空白を詰めます。 

## 背景

原本では以下のようになっています：

> Status information may be aligned either left or right by specifying a numeric literal after the % and before the option. 

## 解決方法

以下のように訂正すべきだと思いました：

```
状態情報は%の後かつオプション名の前に数字を指定することにより、左寄せまた右寄せにすることができます。 
```

## 注意点

ありません。

**Comment by noborus** [comment]
報告ありがとうございました。 #2024 で修正を送りました。
