### ISSUE TITLE
翻訳のコミット運営を決める

### ISSUE THREAD

**Issue by KenichiroTanaka** [pgsql-jp/jpug-doc#201]
## 重要度:

高　(9.5翻訳開始前までに決定する)
## 背景

翻訳のコミット運営が曖昧だったため
## 問題点

効率的ではなかったり、曖昧にドキュメントがコミットされる
## 解決方法

方針を明確にする

**Comment by KenichiroTanaka** [comment]
昔MLで議論されたものの、中途半端になっていました。
すでに運営されてしまっていますが、おおよそML(Re: [jpug-doc: 4636] Re: PRコミットのルールなど)で
議論されたとおりに運営されていると思います。

<pre>
1."明確なTYPO"の場合、
　コミッタがレビュー後、コミットする。

2.担当者以外からの"明確なTYPO"以外のPRがあった場合
　2-1.担当者のレビューの後、コミッタがコミットする。
　2-2.担当者が忙しいなどの理由で2,3日コメントができない場合は、コミッタがレビューしコミットする

3.担当者からの"明確なTYPO"以外のPRがあった場合
　担当者以外のコミッタがレビューを行いコミットする

</pre>

**Comment by smatsudajp** [comment]
「担当者」というのが曖昧な概念だと思っています。ファイル毎のオーナーというわけではなく、単に前バージョンからの差分を翻訳しただけのことなので。
TYPOに限らず、明確な誤訳訂正、訳抜け部分の追加翻訳については、担当者云々とは関係なく、コミッタの誰かがレビューすればコミットして良いのではないかと思っています。
訳語変更や翻訳改善レベルのものについて、誰がどう判断すべきかはちょっと微妙かもしれません。私が誤訳訂正のついでに、ちょっとした改善を混ぜたPRをたくさん出している上、翻訳改善をレビューできる人が不足しているので、ルール化しようとするとさらに難しくなってしまうかもしれませんけど。

**Comment by tatsuo-ishii** [comment]
> TYPOに限らず、明確な誤訳訂正、訳抜け部分の追加翻訳については、担当者云々とは関係なく、コミッタの誰か>がレビューすればコミットして良いのではないかと思っています。

+1。

**Comment by KenichiroTanaka** [comment]
松田さん、石井さんコメントありがとうございます。

そうですね。コミットの誰か、が簡単ですし現状に沿っているので良いかもしれません。
コミッタをどう決めるかは別途決めなければいけないですね。

いただいている懸念点を考慮して、シンプルになりますが、以下のような内容でどうでしょうか。

※わざわざ書くほどのものでもない気がしますが、どのように運営するかはどこかに記載して
　おく必要があると思っています。

<pre>
・PRを出した人以外のコミッタがレビューし、コミットする。
</pre>

**Comment by tatsuo-ishii** [comment]
> コミッタをどう決めるかは別途決めなければいけないですね。

PostgreSQLでは、コミッタは、コミッタの誰かが新しいコミッタ候補を推薦し、他のコミッタからの賛同を得て決まります。JPUG-DOCでも、既存のコミッタの間で協議して決める、ということではいかがでしょう？

実際に運用する際には、たぶんjpug-doc以外の非公開のコミッタだけが閲覧できるＭＬが必要になると思います。

**Comment by KenichiroTanaka** [comment]
>JPUG-DOCでも、既存のコミッタの間で協議して決める、ということではいかがでしょう？
はい、こちらの方法で問題無いと思います。（他に適切な方法が思いつきません）

>実際に運用する際には、たぶんjpug-doc以外の非公開のコミッタだけが閲覧できるＭＬが必要に
>なると思います。
そうですね。
用意できるか確認してみます。

**Comment by KenichiroTanaka** [comment]
報告が遅れましたが、jpugにてコミッタ用のMLを作成いただきました。
詳細は翻訳者会議でお知らせします。

**Comment by KenichiroTanaka** [comment]
しばらく対応できていませんでした。
３月に翻訳者会議を実施しましたが、その際、参加いただいた中から以下の方に
コミッタをお願いしました。
石井さん
松田さん
斉藤さん
小泉さん
高塚さん
田中

その上で、今後の運営は以下のように行いたいと思います。
----------------------------------------------------------------------------------------------------
・PRを出した人以外のコミッタがレビューし、コミットする。
・コミッタは現行コミッタが随時推薦し、現行コミッタの賛同が
　取れればコミッタとして任命される。
----------------------------------------------------------------------------------------------------

他にご意見などあればお知らせください。

**Comment by KenichiroTanaka** [comment]
問題ないようですのでひとまずこちらの方針とします。
結論は以下のwikiへ記述しました。

https://github.com/pgsql-jp/jpug-doc/wiki/翻訳文のコミット運営について
