### ISSUE TITLE
glossary.sgml の修正すべき箇所（レビュー用）

### ISSUE THREAD

**Issue by noborus** [pgsql-jp/jpug-doc#2021]
## 問題点

glossary.sgml は分割して進めていて、全体として統一させるためには出揃ってからレビューして修正が必要です。
プルリクエストはマージされてコメントを見直すのが大変なので、こちらにコメントを追記してください。

### 現在わかっている箇所

- [x]  1.ACIDの説明の統一
    * 見出しの形式に統一。英語（日本語）。
    * 〜の性質。同じ言い回しになっているところの統一。 
- [x] 2.他の用語のリンクになっているところglotssterm linkend のタグが抜けている
- [x] 3.「Result set 」の「結果集合」訳で良いか？確認
- [x] 4.見出し（用語）のところが日本語のみで良いのか、英語（日本語）にしたほうが良いのか
- [x] 5.Schemaの用語で翻訳漏れ

**Comment by noborus** [comment]
見出し（用語）のところが日本語のみで良いのか、英語（日本語）にしたほうが良いのかの見直しもあります。

それから、日本語でも別の用語が使用されている場合は、ここで追加しても良いかもしれない。
例：自動バキューム（autovacuum、オートバキューム）

**Comment by noborus** [comment]
「Result set 」の「結果集合」訳で良いか？確認

**Comment by KenichiroTanaka** [comment]
斉藤さん、まとめていただきありがとうございます。

ドキュメントとして優先順位の高いのは「4.見出し（用語）のところが日本語のみで良いのか、英語（日本語）にしたほうが良いのか」でしょうか。

今の所、以下のパターンがあるようです。
A.英語（日本語）
　例）Materialized（マテリアライズド）
B.日本語
　例）分析関数
C日本語（補足）
　例）バックグラウンドワーカ（プロセス）

私は英語でABC順に並んでいるのでAが一番分かりやすいのではないかと思っていますが、皆様どうでしょうか。

@noborus @tatsuo-ishii @koizumistr @harukat 
※最近アクティブに活動いただいている方にメンションさせていただきました

**Comment by noborus** [comment]
https://pgsql-jp.github.io/current/html/glossary.html
で確認していたのですが、

英語（日本語）（補足）になる場合があって、両方同じ丸括弧だと紛らわしいかもしれません。
日本語の訳を併記する場合は丸括弧以外を使うのが良いように思いました。

例えば
英語【日本語】（補足）
のようにするとか。

**Comment by tatsuo-ishii** [comment]
> 英語【日本語】（補足）
賛成に一票です。

**Comment by tatsuo-ishii** [comment]
>「Result set 」の「結果集合」訳で良いか？確認

「結果集合」に一票。
SQL（という関係データベース理論）では、演算は基本的に集合(set)同士で行われ、さらにその結果(result set)もまた集合となります。ですから、result setのときだけわざわざsetを「セット」と訳すのは、一貫性がないように思います。

**Comment by KenichiroTanaka** [comment]
そうですね。
英語【日本語】（補足）
が良いように思います。D案とします。

**Comment by noborus** [comment]
Schema（スキーマ）
の用語のところで、2006行

> Each SQL object must reside in exactly one schema.

に該当する訳が無いようです。

**Comment by noborus** [comment]
一応わかっていたところの修正、確認は済みました。

**Comment by noborus** [comment]
済んでるのでクローズします
