### ISSUE TITLE
indextermの英語をコメントアウトせずに日本語を追加する

### ISSUE THREAD

**Issue by noborus** [pgsql-jp/jpug-doc#2032]
## 問題点

現在 indextermの中も英語をコメントアウトして中に日本語訳を入れていますが、索引として英語もあった方が良く、減らす必要はないので、コメントアウトせずに追加した方が便利です。

## 解決方法

indextermタグ内のコメントをやめて、もう一つindextermを追加します。

```diff
 <indexterm zone="rules-views">
  <primary>view</primary>
  <secondary>implementation through rules</secondary>
 </indexterm>
 
+<indexterm zone="rules-views">
+ <primary>ビュー</primary>
+ <secondary>ルールを使用した実装</secondary>
+</indexterm>
```

現状のindextermは上記のルールであれば機械的に置き換え可能だと思います。

## 注意点

indexterm のタグを増やす形になるので、ここだけ他とは違うことになります。
マージのコンフリクトも起こりにくくなり作業は楽になります、が原文と距離が空いて変更を見逃しやすくなりがちです。

**Comment by tatsuo-ishii** [comment]
賛成です。以前から私も英語の索引があったほうが良いと思っていました。

**Comment by KenichiroTanaka** [comment]
索引は私も気になっていたため、良いように思います。
英語日本語訳が入り乱れて分かりにくくなったりしないかは少し心配です。
