### ISSUE TITLE
PostgreSQL13.4 or PostgreSQL14.0

### ISSUE THREAD

**Issue by KenichiroTanaka** [pgsql-jp/jpug-doc#2034]
## 問題点
14のRC1が出ている中、13.4の翻訳を開始するかスキップするか。

## 背景
皆様のご意見を伺えますでしょうか。

**Comment by koizumistr** [comment]
（すみません。自宅の環境構築のため今まであまり動けてませんでした。NASがぴーぴー言い始めたのとほぼ同時にPCのディスクがマウントできなくなるという、、、、）

(a) 13.2 -> 13.4 
(b) 13.4 -> 14.0
(c) 13.2 -> 14.0
の各差分の量と関係次第かと、、、
 (a)が実はほとんどないとか (a)+(b) = (c) なら13.4をやるのはありだと思います。が、そうではないのではないかと、、、、

**Comment by koizumistr** [comment]
実際にはこんな感じ、、、
(a)
git diff --stat REL_13_2 REL_13_4 doc/src/sgml/
 68 files changed, 3938 insertions(+), 276 deletions(-)

(b)
git diff --stat REL_13_4 REL_14_RC1 doc/src/sgml/
 239 files changed, 18533 insertions(+), 13355 deletions(-)

(c)
git diff --stat REL_13_2 REL_14_RC1 doc/src/sgml/
 251 files changed, 19630 insertions(+), 10790 deletions(-)

**Comment by tatsuo-ishii** [comment]
なぜ13.2なんでしたっけ？翻訳を完了したのは13.1ですよね....
ちなみ13.1だとこんな感じです。
git diff --stat REL_13_1 REL_13_4 doc/src/sgml/
 95 files changed, 6506 insertions(+), 775 deletions(-)

git diff --stat REL_13_1 REL_14_RC1 doc/src/sgml/
259 files changed, 20523 insertions(+), 9614 deletions(-)

**Comment by tatsuo-ishii** [comment]
どちらにしても結論はあまり変わらなそうです。13.4はスキップですかね。

**Comment by noborus** [comment]
今13.4を始めると14のリリースまでに終えられないので、14の翻訳開始が遅れてしまうので14で良いと思います。

**Comment by koizumistr** [comment]
> なぜ13.2なんでしたっけ？翻訳を完了したのは13.1ですよね....

すみません、指摘されるまで13.2を訳したとばかり思ってました、、、、、orz

**Comment by KenichiroTanaka** [comment]
皆様、ありがとうございます。
私も14の開始が遅れそうなので、13.4のスキップで良いと思います。

**Comment by koizumistr** [comment]
14がリリースされましたね。

**Comment by noborus** [comment]
14の準備を始めたいと思いますが提案として、
古い13ブランチ(doc_ja_13)はこれまでバックポートしない方針できましたが、誤訳やミスの指摘があった場合に14の翻訳完了まで反映されないのは、また時間がかかりすぎるのでdoc_ja_13にバックポートして、（月に１回程度で）Webに反映させるようにしたら、どうでしょうか？PullRequestは13用のラベルを用意する等して区別すると良いと思います。

既に13ブランチにPullRequestを3つ出してますが、これはこのまま13ブランチ用として、並行して14ブランチを開始するのが良いと思います。

**Comment by tatsuo-ishii** [comment]
これは13.1の原文はあくまでそのままで、13.2やそれ以降に更新しようという話ではないのですよね？

**Comment by noborus** [comment]
はい。
14が完了した後に13.4のバックポートは考えられるかもしれませんが、それでも難しいと考えてます。

**Comment by noborus** [comment]
14がもう少し掛かりそうなので、そろそろ13の公開版を更新するのはどうでしょうか？

**Comment by koizumistr** [comment]
#2122 については追加の指摘はありません。 
#2031、 #2036 については強い反対・賛成はないです。（改悪にはなっていない、とは思います。）

**Comment by KenichiroTanaka** [comment]
小泉さん
レスありがとうございました。

みなさま
残っていたv13のPRをマージし公開しました。
お気付きの点がありましたらお知らせください。

**Comment by koizumistr** [comment]
#2040 もあることですし、こちらはさすがにcloseしても良いような、、、、

後半で微妙に話題が変わってますが。

**Comment by KenichiroTanaka** [comment]
クローズ忘れです。クローズします。
