### ISSUE TITLE
51章 システムカタログの表タイトル

### ISSUE THREAD

**Issue by nori-shinoda** [pgsql-jp/jpug-doc#2037]
## 重要度: （中）（高/中/低から選んでください）
低

## 問題点
 PostgreSQL 12 までの日本語マニュアルでは、システムカタログの表タイトルは以下の通りでした。
　　例）表51.2 pg_aggregate の列
 PostgreSQL 13 では以下のようになっています。
　　例）表51.2 pg_aggregate Columns

## 解決方法
　どちらでも良いと思いますが、できればこれまで同様に「の列」の方が見やすいと思います。

**Comment by noborus** [comment]
ありがとうございます。
13で表の形式が変わったので以前の翻訳を変換して入れるようにしたのですが、
タイトルは対象としていなかったので、そのままになってました。
修正します。
