### ISSUE TITLE
sgmlで日本語翻訳部に改行を使えるようにする

### ISSUE THREAD

**Issue by KenichiroTanaka** [pgsql-jp/jpug-doc#205]
## 背景

翻訳中やレビュー中にスクロールが発生する。
## 問題点

レビュー効率が落ちる。
## 解決方法

日本語ドキュメントに改行を入れてもhtmlドキュメントに影響が無いようにする
## 注意点

事実関係の確認から。

**Comment by harukat** [comment]
(6/15 翻訳者会議で）
参照する手段の側で解決する方向で対処することとなった。
