### ISSUE TITLE
19.4.6. 非同期動作 のリンク切れ

### ISSUE THREAD

**Issue by nori-shinoda** [pgsql-jp/jpug-doc#2133]
## 問題点
  PostgreSQL 13.1 のマニュアル 19.4.6. 非同期動作 に対する指摘です。
  maintenance_io_concurrency の説明の中でリンクが正しく記載されていません。以下のように表示されています。

- ここから 
サポートしているシステムではデフォルトは10で、それ以外は0です。 この値は同じ名前のテーブル空間パラメータを使って、特定のテーブル空間にあるテーブルのために置き換えることができます。（xref linkend="sql-altertablespace"/>を参照してください。）
- ここまで 

## 解決方法
   xref linkend="sql-altertablespace"/> の部分を正しい記載に修正する。

**Comment by noborus** [comment]
報告ありがとうございます。
ちょうど #2132 と #2122 で修正を出しているところでした。

**Comment by KenichiroTanaka** [comment]
#2132 と #2122 がマージされたので本件クローズします。
ご報告ありがとうございました。
