### ISSUE TITLE
 旧バージョンのリリースノートtypo：「外部結語」

### ISSUE THREAD

**Issue by nuko-yokohama** [pgsql-jp/jpug-doc#2163]
## 問題点

* 旧バージョン(8.4～10)中のリリースノートにtypo：「外部結語」

## 背景

* 旧バージョンのリリースノート確認中に発見

## 解決方法

* release-8-4.html 中の以下のtypo修正：「外部結語」→「外部結合」
* 影響バージョンはPostgreSQL 8.4 からPostgreSQL 10まで。

## 注意点

特になし

**Comment by noborus** [comment]
報告ありがとうございます。
ただ、バージョン 10までとのことなので、修正してもWebの更新はされないのではないかと思います...

**Comment by KenichiroTanaka** [comment]
報告ありがとうございます。
ありがとうございます。致命的なものでなければ旧バージョンへのバックポートはしない方針ですが、
せっかくご報告いただきましたのでバージョン10の最新版のみ修正する方針でどうでしょうか。

**Comment by KenichiroTanaka** [comment]
https://www.postgresql.jp/document/10/html/release-8-4.html

```
外部結合が背後にある副問い合わせの最適化を改良しました。(Tom)
```

修正しましたのでご連絡します。

ご報告いただきありがとうございました。

**Comment by KenichiroTanaka** [comment]
残タスクも無くなりましたのでクローズします。
