### ISSUE TITLE
PostgreSQL 10リリースノートの1項目が日本語翻訳されていない。

### ISSUE THREAD

**Issue by nuko-yokohama** [pgsql-jp/jpug-doc#2164]
## 問題点

* PostgreSQL 10リリースノートの1項目が日本語翻訳されていない。

## 背景

* 旧バージョンのリリースノート確認中に発見

## 解決方法

* release-10.html の"Enable parallelism by default by changing the default setting of max_parallel_workers_per_gather to 2." を日本語に訳す。
* 影響範囲はPostgreSQL 10のみ。

## 注意点

* 特になし。

**Comment by noborus** [comment]
報告ありがとうございます。
ただ、バージョン 10なので、修正してもWebの更新はされないのではないかと思います...

**Comment by KenichiroTanaka** [comment]
こちらも#2163と同じ方針でどうでしょうか。
また、訳としては
```
max_parallel_workers_per_gatherのデフォルト値を2に変更することでデフォルトでパラレルクエリを使えるようにしました。
```
あたりでどうでしょうか。

**Comment by KenichiroTanaka** [comment]
https://www.postgresql.jp/document/10/html/release-10.html
こちらも修正しました。

**Comment by KenichiroTanaka** [comment]
反映が完了したのでクローズします。
