### ISSUE TITLE
pg_replication_originの説明に誤字がある

### ISSUE THREAD

**Issue by HUUTFJ** [pgsql-jp/jpug-doc#2165]
## 問題点

pg_replication_originシステムカタログの説明に誤字があります。`pg_replication_origin`が正しいのではないでしょうか？

> つまりクラスタごとにpg_pg_replication_originの実体は1つだけ存在し、データベースごとに1つではありません。

https://www.postgresql.jp/document/13/html/catalog-pg-replication-origin.html

## 背景

英語版マニュアルは`pg_replication_origin`となっています。

> there is only one copy of pg_replication_origin per cluster, not one per database.

https://www.postgresql.org/docs/14/catalog-pg-replication-origin.html

## 解決方法

`pg_pg_replication_origin`の冒頭3文字を削除するとよいと思います。

## 注意点

ありません。

**Comment by noborus** [comment]
報告ありがとうございます。
修正を #2166 で送りました。
別途13ブランチも修正しようと思います。

**Comment by HUUTFJ** [comment]
ありがとうございました。本issueはcloseします。
