### ISSUE TITLE
「translation」の訳が「翻訳」になっていない箇所がある

### ISSUE THREAD

**Issue by HUUTFJ** [pgsql-jp/jpug-doc#2168]
## 問題点

下記文章内の「変換」は、「翻訳」の誤りではないでしょうか？

> SQLSTATEエラーコードが常にデフォルトになること、メッセージ文字列が変換されないことに注意してください。

https://www.postgresql.jp/document/13/html/error-message-reporting.html

## 背景

英語マニュアルでは「translation」となっています：

> Notice that the SQLSTATE error code is always defaulted, and the message string is not subject to translation. 

https://www.postgresql.org/docs/14/error-message-reporting.html

また対訳表を確認したところ、「translation」は「翻訳」と訳するようです。

https://github.com/pgsql-jp/taiyaku/blob/master/jpug-doc.en.ja.csv#L3356

## 解決方法

下記のように修正すればよいと思います：

SQLSTATEエラーコードが常にデフォルトになること、メッセージ文字列が翻訳されないことに注意してください。

## 注意点

ありません。

**Comment by KenichiroTanaka** [comment]
ご報告ありがとうございます。
ご指摘の通りかと思います。

直前の
```
errmsg_internal(const char *msg, ...)は、そのメッセージ文字列は変換されず、国際化用メッセージ辞書に含まれない点を除き、errmsgと同一です。 これは、おそらく翻訳作業を行う価値がない「発生し得ない」場合用に使用すべきです。
```
 も変換ではなく、翻訳、とすべきですね。

どなたかPRを作成いただくことは可能でしょうか。

**Comment by HUUTFJ** [comment]
PRを出させていただきました。#2172 を確認してください。

**Comment by KenichiroTanaka** [comment]
ありがとうございます!
確認します。

**Comment by KenichiroTanaka** [comment]
問題ありませんでしたのでマージしました。
ご報告及びPRの対応ありがとうございました。
