### ISSUE TITLE
ロジカルレプリケーション 「両者でスキーマ名は完全に同じである必要はない」

### ISSUE THREAD

**Issue by harukat** [pgsql-jp/jpug-doc#2173]
## 問題点

13.x までのロジカルレプリケーションの「31.4 制限事項」で以下のようになっている。

 (Note, however, that there is no need for the schemas to be absolutely the same on both sides.)
（なお、両者でスキーマ名は完全に同じである必要はないことに留意してください。） 

https://pgsql-jp.github.io/current/html/logical-replication-restrictions.html

## 解決方法

実態としては、「スキーマ名.テーブル名」の名前の一致が必要で、定義の中身は完全には一致していなくても良いので、「スキーマ名は完全に同じ・・・」でなく「スキーマは完全に同じ・・・」が良い。

## 注意点

14.x の logical-replication.sgml の翻訳は本報告時点では未着手なのでメモとして記載。

**Comment by KenichiroTanaka** [comment]
すみません、本ISSUESを見落としていてlogical-replication.sgml をマージしてしまいました。
ご指摘の箇所はそのままになっています。

改めて内容を確認していますが、実態を考えるといただいている修正案が良いように思います。

他にご意見ありませんでしたら、いただいている修正方針で進められればと思います。

**Comment by KenichiroTanaka** [comment]
https://github.com/pgsql-jp/jpug-doc/pull/2270

で修正しましたのでクローズします。
