### ISSUE TITLE
訳文の見直し

### ISSUE THREAD

**Issue by pato-taityo** [pgsql-jp/jpug-doc#2184]
## 問題点

https://www.postgresql.jp/document/13/html/textsearch-indexes.html
『全文検索のためにインデックスが必須だと言うわけではないことを言っておかなければなりませんが』
という訳は少しまどろこしく感じました。

『全文検索でインデックスが必須ではありませんが』
とするのはいかがでしょうか。

原文が以下の通りでしたので、修正後でも差し支えないと考えております。
https://www.postgresql.org/docs/14/textsearch-indexes.html
"Note that indexes are not mandatory for full text searching"

問題ないようであればPRを作成させていただきます。

**Comment by KenichiroTanaka** [comment]
反応が遅くなり失礼しました。
そうですね。いただいている案の方がシンプルで良いように思います。
PRの作成をお願いしてもいいでしょうか。

**Comment by KenichiroTanaka** [comment]
PRありがとうございました。
問題ありませんでしたのでマージしました。

ドキュメント改善のご連絡をいただきありがとうございました。
