### ISSUE TITLE
拡張の利点に関する説明に一部誤りがある

### ISSUE THREAD

**Issue by HUUTFJ** [pgsql-jp/jpug-doc#2185]
## 問題点

「関連するオブジェクトを拡張としてパッケージ化」の節に下記の記載があります。

>  もっと有用なことは、pg_dumpが拡張の個々のメンバオブジェクトを削除してはならないことを把握していることです。 代わりにダンプ内にはCREATE EXTENSIONコマンドだけが含まれます。

この中の「個々のメンバオブジェクトを削除してはならない」は、「個々のメンバオブジェクトをダンプしてはならない」の誤りではないでしょうか？

## 背景

公式マニュアルの同様の個所を確認したところ、該当箇所は[should not dump]とされています。

> Even more useful, pg_dump knows that it should not dump the individual member objects of the extension — it will just include a CREATE EXTENSION command in dumps, instead.

公式対訳表を確認したところ、「dump」はそのまま「ダンプ」とするようです。

## 解決方法

下記のように変更するとよいと思います。

 もっと有用なことは、pg_dumpが拡張の個々のメンバオブジェクトをダンプしてはならないことを把握していることです。 

## 注意点

ありません。

**Comment by KenichiroTanaka** [comment]
ご連絡ありがとうございます。
ご指摘の通りかと思います。
また、いただいている修正案が良いように思います。

PRを作成いただくことは可能でしょうか。
（もし、お手間でしたらこちらでも作成できますのでその旨おっしゃってください。）

**Comment by HUUTFJ** [comment]
#2188 にてPRを送らせていただきました。ご確認ください。

**Comment by KenichiroTanaka** [comment]
PRをいただきありがとうございました。
いただいている内容で問題ありません。
マージしました。

ご報告いただきありがとうございました。本ISSUESはクローズします。
