### ISSUE TITLE
矩形データ型の構文について

### ISSUE THREAD

**Issue by mah0x211** [pgsql-jp/jpug-doc#2228]
## 問題点

https://github.com/pgsql-jp/jpug-doc/blob/0509efd1fa357f35ffe94cebd5a0a4c338086741/doc/src/sgml/datatype.sgml#L5155-L5160

## 背景

データ型パーサを作成中に実際の出力と違うことに気づき、英語版を参照して発見しました。

## 解決方法

２番目の構文で出力されるの誤りですね。

## 注意点

過去のバージョンのドキュメントも同様のようです。

**Comment by KenichiroTanaka** [comment]
ご連絡有難うございます。
ご指摘の通り誤りです。

せっかくご報告いただきましたので、もし、よろしければ（gitの使い方にも精通されているようですので）
PRを頂けますとレビュー、マージします。
もちろんこちらで修正PRを出すこともできますので、その方がよろしければ、その旨お知らせください。

**Comment by KenichiroTanaka** [comment]
その後ご連絡が滞り失礼しました。
本件ですが取り急ぎこちらで修正版のPRを作成して対応を進めさせていただきます。
ご報告ありがとうございました。

**Comment by KenichiroTanaka** [comment]
PostgreSQLマニュアルへの名前掲載可否のご連絡です。

PostgreSQLの普及において日本語ドキュメントは極めて重要です。
JPUG-DOCではドキュメントの翻訳運営に貢献いただいた方のお名前を
感謝の意を込めて記載しています。

記載のイメージは以下の通りです。

[https://www.postgresql.jp/document/pg13doc/html/jpug-doc.html](https://www.postgresql.jp/document/pg13doc/html/jpug-doc.html)

そこでJPUG-DOCでは今回いただいた報告も重要な貢献と考え、お名前をマニュアルへ
記載したいと考えています。

もし、よろしければ下記のwikiを直接編集いただくか、本PRへ返信を
いただけませんでしょうか。

・記載するお名前
・会社名を付与される場合は会社名

https://github.com/pgsql-jp/jpug-doc/wiki/%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E7%BF%BB%E8%A8%B3%E6%8B%85%E5%BD%93%E3%83%AA%E3%82%B9%E3%83%8814.0

お忙しいと思いますがお返事をお待ちしています。

以上です。

**Comment by mah0x211** [comment]
すみません、返信が遅くなってしまいました。
多忙なため修正はそのようにして頂けると助かります。ありがとうございます。

名前を記載していただくことは問題ありません。

- 記載する名前：Masatoshi Fukunaga

また何か修正点を発見した際には報告いたします。
ありがとうございます。

**Comment by KenichiroTanaka** [comment]
@mah0x211 さん
ご回答ありがとうございました。
ではいただいた内容でドキュメントへ記載いたします。
ご連絡ありがとうございました。
