### ISSUE TITLE
7.8 WITH Query - Recursive Query Evaluation　日本語訳改善案

### ISSUE THREAD

**Issue by phylobase-web** [pgsql-jp/jpug-doc#223]
下記の日本語訳の意味がわかりにくかったので、修正案を送ります。適切なSGML編集方法がわからず、Pull Requestまでたどり着けませんでした。お手数ですがよろしくお願いします。

https://www.postgresql.jp/document/9.4/html/queries-with.html

（旧訳）
7.8. WITH問い合わせ（共通テーブル式）
再帰的問い合わせの評価
1.	非再帰的表現を評価します。 UNION（しかしUNION ALLではありません）では、重複行を廃棄します。 その再帰的問い合わせの結果の残っているすべての行を盛り込み、同時にそれらを暫定的作業テーブルに置きます。
2.	作業テーブルが空でないのであればこれらの手順を繰り返します。
a.	再帰自己参照に対する作業テーブルの実行中の内容を置換し、再帰的表現を評価します。 UNION（しかしUNION ALLではない）に対し、重複行と前の結果行と重複する行を破棄します。 その再帰的問い合わせの結果の残っているすべての行を盛り込み、同時にそれらを暫定的中間テーブルに置きます。
b.	中間テーブルの内容で作業テーブルの内容を差し替え、中間テーブルを空にします。

（改善案）
7.8. WITH 問い合わせ（CTE; 共通テーブル式）
再帰クエリ評価
1.	Evaluate the non-recursive term. For UNION (but not UNION ALL), discard duplicate rows. Include all remaining rows in the result of the recursive query, and also place them in a temporary working table.
非再帰述語を評価します。UNION (UNION ALLを除く)では重複除外します。残りの行は全て（再帰クエリの結果に含め）（一時）作業テーブルに置きます。
2.	So long as the working table is not empty, repeat these steps:
作業テーブルが空でない限り（空になるまで）、以下のステップを繰り返します。
a.	Evaluate the recursive term, substituting the current contents of the working table for the recursive self-reference. For UNION (but not UNION ALL), discard duplicate rows and rows that duplicate any previous result row. Include all remaining rows in the result of the recursive query, and also place them in a temporary intermediate table.
再帰述語評価では、まず再帰自己参照を作業テーブル内容と置き換えます。UNION (UNION ALLを除く)では、作業テーブルを含め重複除外します。残りの行は全て（一時）中間テーブルに置きます。
b.	Replace the contents of the working table with the contents of the intermediate table, then empty the intermediate table.
作業テーブル内容を中間テーブル内容で置き換え、中間テーブルを空にします。

**Comment by smatsudajp** [comment]
松田です。

ファイルは queries.sgml ですね。

「再帰的表現」vs「再帰述語」といったテクニカルタームの訳語選択は、
他の方に任せたいと思いますが、それ以外の部分についてコメントします。

現状でtemporaryを「暫定的」と訳しているのは「一時」の方が良いと思いますが、
提案された訳が「(一時)」とカッコつきになっている理由はよくわかりません。

「しかしUNION ALLではありません」は、提案通り「UNION ALLを除く」の方が良いですが、
"but"を訳出するなら「ただしUNION ALLは除く」ですかね。

「重複除外します」は、現状の「重複する行を廃棄します」のままで良いかと思います。

"repeat these steps"の"these"は提案通り、「以下の」と訳すべきですが、
"steps"は(好みの問題ですが)「ステップ」よりも「手順」の方が良いと思います。

2aの訳は、提案の訳文よりも、現状の方が原文に忠実で正確だと思います。




2015-11-25 17:05 GMT+09:00 phylobase-web <notifications@github.com>:

**Comment by smatsudajp** [comment]
石井さんからの応答も合わせると、queries.sgmlの指摘部分について、
(1) "temporary"の訳語が「暫定的」となっているのを「一時」に修正(カッコはつけない)
(2) 「しかしUNION ALLではありません」となっているのを「ただしUNION ALLは除く」に修正
(3) 「これらの手順」となっているのを「以下の手順」に修正、
他は現状通りとする、という見解でｊす。
他に意見がなければ、近いうちにPRを出したいと思います。
あるいは、どなたかPRを出していただけると助かります(今週中はPRを出せない環境にいるので…)。

**Comment by phylobase-web** [comment]
修正案では、旧訳の誤りや混乱を招く逐語訳に手を加えることで、意味の明確化を目指しています。
ご指摘の点について見解を説明します。


>「再帰的表現」vs「再帰述語」といったテクニカルタームの訳語選択は、
他の方に任せたいと思いますが、それ以外の部分についてコメントします。

termの単数形を「表現」とするのは誤訳です。この訳語は複数形のもので意味も異なります。また「表現」は本来はexpressionの訳語に当たり混乱しやすい用語です。

>現状でtemporaryを「暫定的」と訳しているのは「一時」の方が良いと思いますが、
提案された訳が「(一時)」とカッコつきになっている理由はよくわかりません。

後続の文では「一時」を使っておらず、日本語表現としては曖昧さがあるためです。英語表現としては曖昧さはありません。

>「しかしUNION ALLではありません」は、提案通り「UNION ALLを除く」の方が良いですが、
"but"を訳出するなら「ただしUNION ALLは除く」ですかね。

「ただし」をつけなくても混乱の可能性はないので省きました。より意味が明確になるという判断なら構いません。

>「重複除外します」は、現状の「重複する行を廃棄します」のままで良いかと思います。

実はここが肝です。本意が読み取れず、原文に当たって初めて意味が通じました。修正案受け入れを強く希望します。

>"repeat these steps"の"these"は提案通り、「以下の」と訳すべきですが、
>"steps"は(好みの問題ですが)「ステップ」よりも「手順」の方が良いと思います。

異論ありません。

>2aの訳は、提案の訳文よりも、現状の方が原文に忠実で正確だと思います。

ここが第２の肝です。
現状の文では意味がほとんどわかりませんでしたので、修正案受け入れを強く希望します。

**Comment by smatsudajp** [comment]
誤訳の訂正や、わかりやすい表現への修正は大歓迎ですが、あくまでも「翻訳」ですので、原文に対して「何も足さない、何も引かない」のが大原則です。原文と違うことを書くのであれば、(それが正しい内容であったとしても)そこには訳注が必要です。
「肝」とされている２つの点については、原文と内容が同等でありませんので、このままでは修正案として受け入れることはできないと考えます。

**Comment by phylobase-web** [comment]
「何も足さない、何も引かない」逐語訳が翻訳として正しいかどうかには議論の余地がありますが、方針は了解しました。
いずれにせよ、現行訳は直訳に固執するあまり理解困難になっているのでなんとかしたいと思ったのですが、受け入れられる余地はないようなので、これにて失礼します。お騒がせしました。

**Comment by koizumistr** [comment]
[ improve Japanese translation #239 ](https://github.com/pgsql-jp/jpug-doc/pull/239)としてPR出しました。上にreferencedって出ているので分かると思いますが。

**Comment by smatsudajp** [comment]
提案のうち、合意できる部分は採り入れたと思うので、クローズします。
