### ISSUE TITLE
長音付けルール変更

### ISSUE THREAD

**Issue by noborus** [pgsql-jp/jpug-doc#2280]
## 問題点

長音付けルールで長音を省くルールにしていても統一されていない単語の変更。
以下の３つを省かないルールにしたい。

* (over) オーバ → オーバー
* (worker)ワーカ → ワーカー
* (super)スーパ → スーパー

## 背景

長音を省くルールの中でも一般用語として普及している単語は、もともと付けるようになっていたが、
PostgreSQLのドキュメントでは省くようにしていた。
一般用語として普及しているため意識しないと長音を付けて書いてしまい、結果として混在している。

MSで、もともと長音を付けるルールとなっているものは付ける側の方が統一しやすい。
https://atmarkit.itmedia.co.jp/news/200807/25/microsoft.html

## 解決方法

一単語ずつ一括変換してPR。

## 注意点

他にも該当する単語はあるけど、一単語ずつが良いと思う。

**Comment by KenichiroTanaka** [comment]
ISSUESありがとうございます。
いただいている方針で異議ありません。
