### ISSUE TITLE
17.5.1. 共有ライブラリ に記載された URL

### ISSUE THREAD

**Issue by nori-shinoda** [pgsql-jp/jpug-doc#2283]
## 問題点
　「17.5.1. 共有ライブラリ」に記載された URL が更新されていません。
　https://www.postgresql.jp/document/14/html/install-post.html#INSTALL-POST-SHLIBS

　現状のURL： http://xahlee.org/UnixResource_dir/_/ldpath.html
　最新のURL： http://xahlee.info/UnixResource_dir/_/ldpath.html

　英語版： https://www.postgresql.org/docs/14/install-post.html#INSTALL-POST-SHLIBS   

## 背景
　下記の修正が反映されていないと思われます。

　https://git.postgresql.org/gitweb/?p=postgresql.git;a=blobdiff;f=doc/src/sgml/installation.sgml;h=fa90e9104aea41a8f7d5a8ea8754d656df2e3255;hp=7a7823b7a30611f0df47d2c22cf7d07edc38a427;hb=a06e56b247feb2812bad5cf60fd9c0128d81f5c0;hpb=1007b0a126c608b530fd2914825f1e6d133cb649

## 解決方法
　doc/src/sgml/installation.sgml のURLを修正します。

**Comment by noborus** [comment]
ありがとうございます。ご指摘通り修正します。
