### ISSUE TITLE
ctid の説明文がデグレードしている

### ISSUE THREAD

**Issue by harukat** [pgsql-jp/jpug-doc#2338]
### 問題の詳細

ddl.sgml ([ddl-system-columns.html](https://pgsql-jp.github.io/current/html/ddl-system-columns.html)) の ctid に関する以下の訳文は、[以前の訳](https://www.postgresql.jp/document/8.4/html/ddl-system-columns.html)の方がPostgreSQL実装に鑑みて正しいと思われます。

     a row's <structfield>ctid</structfield> will change if it is updated or moved by  
    <command>VACUUM FULL</command>. 

    行のctidはVACUUM FULLにより更新あるいは移動させられると変わります。

    （以前の訳）
    行のctidは更新される、あるいはVACUUM FULLで移動させられると変わります。 

もっといえば「UPDATEされる」の方が更に明解です。

### 貢献者として記載可否

以前の記載名を使用

**Comment by tatsuo-ishii** [comment]
今の訳は確かに正しくないです。
元に戻すでもよいですが、ご指摘のように「UPDATE」にしたほうが明確と私も思います。
あと、元の訳の「移動させられる」は単に「移動される」で良いのでは。更に原文の"it"はctidではなくて、行(row)を指しているので、そこを明確にした方が良いでしょう。まとめると以下になります。

行のctidは、行がUPDATEされる、あるいはVACUUM FULLで行が移動されると変わります

**Comment by KenichiroTanaka** [comment]
>「移動させられる」は単に「移動される」で良いのでは

こちらの反映ができていませんでした。いただいている案が良いように思います。
反映できていないバージョンでマージしてしまったので新たにPRを作成しました。
https://github.com/pgsql-jp/jpug-doc/pull/2381

**Comment by noborus** [comment]
見逃しの修正ありがとうございます。クローズします。
