### ISSUE TITLE
ヘッダファイルの表記ゆれ

### ISSUE THREAD

**Issue by koizumistr** [pgsql-jp/jpug-doc#2395]
### 重要度

低

### 問題点

ヘッダファイル、ヘッダーファイルと表記がゆれています（ヘッダファイルの方が多数派）

### 背景

#2358 の確認の過程で見つけました。（コメントとして書いてしまったので埋もれてしまうのでこちらにしました。）

### 解決方法

特別な理由がなければ多数派のヘッダファイルに合わせるべきかと思います。

### 貢献者として記載可否

以前の記載名を使用

**Comment by koizumistr** [comment]
#2280 とちょっと関係あるでしょうか。https://atmarkit.itmedia.co.jp/news/200807/25/microsoft.html をみると header は「ヘッダー」になってますね。が、ここでは「ヘッダファイル」と組み合わせた場合についてだけ言っているつもりです。

**Comment by KenichiroTanaka** [comment]
個人的にはなかなかヘッダーファイルという表記には慣れないです。
ひとまずヘッダファイルで良いように思いますが、皆様どうでしょうか。
@noborus さん
@tatsuo-ishii さん
@harukat さん

**Comment by tatsuo-ishii** [comment]
私はどちらに統一するのでも良いです。

**Comment by KenichiroTanaka** [comment]
コメントありがとうございます。
では、本issuesの対応としては「ヘッダファイルに統一する」で進められればと思います。

**Comment by koizumistr** [comment]
.ng.list に「ヘッダーファイル」が追加されたのでこちらはクローズ、
と思ったですが、ファイルに追記されたもののまだコメントアウト、という状態でしたね、、、

**Comment by noborus** [comment]
まだbki.sgmlにヘッダーファイルが残っているので、そちらを変更してからng.listを有効にする必要があります。
