### ISSUE TITLE
JPUGのドキュメントページからhttps://pgsql-jp.github.io/current/html/ の最新版へのリンクをはる

### ISSUE THREAD

**Issue by noborus** [pgsql-jp/jpug-doc#2467]
### 重要度

中

### 問題点

PostgreSQL日本語ドキュメントの最新版は完了してから https://www.postgresql.jp/document/ に載せられるため、
本家がリリースしてから日本語ドキュメントとして提供されるまで時間が掛かっている。
https://pgsql-jp.github.io/current/html/ は最新を毎日更新しているため、注意付きの最新としてリンクをはるのが良いと思います。

### 背景

15.0から機械翻訳であることがわかるようになった上で、ほとんどの箇所で翻訳が入っているため、最新版でも参照してもらえるようになったため。

### 解決方法

https://www.postgresql.jp/document/ からのリンクをはる

### 注意点

https://pgsql-jp.github.io/current/html/ では他のバージョンへのリンクがないため、代替案を入れるか検討が必要。
誤訳等の報告の近くらへんに https://www.postgresql.jp/document/  へのボタンを付けるとか。

### 貢献者として記載可否

以前の記載名を使用

**Comment by KenichiroTanaka** [comment]
12月の理事会で承認を取るので少しお待ちください。

**Comment by noborus** [comment]
https://pgsql-jp.github.io/current/html/ に15.0でリンクをはると後々ずれてしまうので、
https://pgsql-jp.github.io/jpug-doc/15.0/html/ を用意してリダイレクトするようにしました。
ほんとはsymlinkのようなことをしたかったのですが、Github Pagesでどうすれば良いのかわからなかったため。

**Comment by KenichiroTanaka** [comment]
理事会で報告し、OKとなりました。
進めて大丈夫です。

どこにリンクをつけるかはこの後相談させてください。

**Comment by KenichiroTanaka** [comment]
@noborus さん
すみません、対応が遅くなりました。
リンク位置ですが↓あたりを想像しているのですがイメージはあっているでしょうか。

![current_ins_point](https://user-images.githubusercontent.com/812154/208428581-6db6d08d-2515-4d00-850a-45d513422ffd.png)

ページのトップなので
https://pgsql-jp.github.io/current/html/ 
で良いのではないかと思っています。

**Comment by KenichiroTanaka** [comment]
「翻訳中の最新のバージョン」
という名前のリンクにしようかと思っています。

**Comment by noborus** [comment]
はい。そうです。更新が手間でなければ、PostgreSQL 15.0 日本語マニュアル（翻訳作業中）のように15.0が入っていると良いなと思いました。

**Comment by KenichiroTanaka** [comment]
ちょっと手間ではありますが（更新できる自信が無い）ですが、ぱっと見v１５の日本語があるのは魅力ですよね。
どこかにv15を入れるようにします。

**Comment by KenichiroTanaka** [comment]
https://www.postgresql.jp/document/

リンクを貼りました。いかがでしょうか。

**Comment by noborus** [comment]
良いと思います。

**Comment by noborus** [comment]
実現したのでクローズします。
