### ISSUE TITLE
recovery-config.html/appendix-obsolete-recovery-config.sgmlに、未翻訳と思われる個所がある

### ISSUE THREAD

**Issue by HUUTFJ** [pgsql-jp/jpug-doc#2501]
### 問題の詳細

recovery-config.htmlの末尾に、[Standby Server Operation]と未翻訳で表示されている箇所があります。リンク先のタイトルである「スタンバイサーバの動作」か、「27.2.2」と表示されれるべきではないでしょうか？

```
standby_modeの 設定が削除されました。 代わりに、dataディレクトリ内のstandby.signalファイルが使用されます。 詳細については、[Standby Server Operation](https://www.postgresql.jp/document/14/html/warm-standby.html#STANDBY-SERVER-OPERATION)を参照してください。
```

元になったappendix-obsolete-recovery-config.sgmlでは、下記のようになっています。\<xref>タグではなく、\<link>タグを用いて文字列を指定する必要があるかもしれません。

```
<literal>standby_mode</literal>の
<indexterm>
<primary>standby_mode</primary>
<see>standby.signal</see>
</indexterm>
設定が削除されました。
代わりに、dataディレクトリ内の<filename>standby.signal</filename>ファイルが使用されます。
詳細については、<xref linkend="standby-server-operation"/>を参照してください。
```

### 貢献者として記載可否

以前の記載名を使用

**Comment by noborus** [comment]
ありがとうございます。これはリンク先が` id="standby-server-operation" xreflabel="Standby Server Operation"`のようにxreflabelを指定しているために、そちらのラベルが表示されています。
なので修正するなら、high-availability.sgmlの方をxreflabelの行も翻訳対象にする必要があります。

```diff
-  <sect2 id="standby-server-operation" xreflabel="Standby Server Operation">
 <!--
+  <sect2 id="standby-server-operation" xreflabel="Standby Server Operation">
    <title>Standby Server Operation</title>
 -->
+  <sect2 id="standby-server-operation" xreflabel="スタンバイサーバの動作">
    <title>スタンバイサーバの動作</title>
```

これまで、そこは対象にしていなかったので、方針を決める必要があります。

**Comment by tatsuo-ishii** [comment]
doc/src/sgml/README.linkによれば、xreflabelの使い方は2種類あり、

>- Specific nouns like GUC variables, SQL commands, and contrib modules usually have xreflabels.
> xreflabels added to tags prevent the chapter/section for id's from being referenced;  only the xreflabel is accessible.  Therefore, use xreflabels only when linking is common, and chapter/section information is unneeded.

前者はGUC変数などなので、翻訳するのは無理もしくは不適切で、翻訳するとしたら後者のみでしょう。ただ、それでも数としては数百くらいありそうだし、xreflabelを定義してあっても、実は参照されていないものに関しては翻訳するだけ無駄です。

また、今まではやっていなかったことですから、やるとしても、まずは今までやっていた本体の翻訳に注力し、それが終わってからでも良いと思います。

**Comment by tatsuo-ishii** [comment]
ちなみに、xreflabelの翻訳をしなくて良い、と言っているわけではなくて、上記後者に分類されているもので、参照されているものは、気がついた時に可能な範囲で翻訳していくのは良いと思います。

**Comment by noborus** [comment]
見直したところ、xreflabelに翻訳が必要なところはそれほど多くなさそうなので、必要なところは翻訳していく方針で良さそうです。
気がついたらやってもらって、残りは全体の完了前にやるということで良いと思います。

**Comment by noborus** [comment]
対応済みということクローズします。ありがとうございました。
