### ISSUE TITLE
索引(bookindex)でPG13から同一内容が日本語と英語の2行表示されるようになった(設定パラメータ/configuration parameter, 他にもあり)

### ISSUE THREAD

**Issue by kitayama** [pgsql-jp/jpug-doc#2504]
### 重要度

低

### 問題点

PostgreSQL 13 から索引ページ(bookindex.html)で、同一内容が日本語表記と英語表記の2行、表記されるようになった。
PostgreSQL 12 までは日本語表記の1行だけだった。
気が付いた項目は、
・下記が多数
～ configuration
～の設定
～ configuration parameter
～設定パラメータ
～ storage parameter
～格納パラメータ
・JSONでは
functions and operators
関数と演算子
・jsonbでは
containment
existence
indexes on
上のインデックス
包含
存在

過去に議論があったとか、PostgreSQL 13 から上記の仕様/挙動になったかどうかは確認していません。英語表記もあったほうが嬉しい気持ちも少しあるので既に認識済の仕様/挙動かも？とも思いますが、Issue として挙げさせていただきます(MLはいきてなさそうだし、Slackは GitHub に埋もれて人間が投稿してよさそうな雰囲気でもないので)。

### 背景

PostgreSQL 14 で気付き、過去から同様の表記かどうかを確認したら PostgreSQL 12 の時点では異なったため

### 貢献者として記載可否

記載（貢献者欄に書いてください）

**Comment by noborus** [comment]
これは意図的に英語の索引を残すように変更しました。
#2032 で提案しました。

**Comment by kitayama** [comment]
@noborus さんありがとうございます。明示的に意図的に残すよう変更していたのですね。お騒がせしました。クローズします。
