### ISSUE TITLE
func.sgmlに一部未翻訳と思われる箇所がある

### ISSUE THREAD

**Issue by HUUTFJ** [pgsql-jp/jpug-doc#2505]
### 問題の詳細

関数pg_event_trigger_dropped_objects()が返却する列を述べた箇所に、未翻訳と思われる箇所があります。

``` 
       <row>
        <entry><literal>objsubid</literal></entry>
        <entry><type>integer</type></entry>
        <entry>Sub-object ID (e.g., attribute number for a column)</entry>
       </row>
```

翻訳するとすれば、「サブオブジェクトID (例えば列番号)」でしょうか？

### 貢献者として記載可否

以前の記載名を使用

**Comment by noborus** [comment]
ありがとうございます。これは(12までの）以前のバージョンで訳が入っていたところでした。
e.g. → e.g., の変更が入ったために、引き継がれなくなっていました。
12では、pg_event_trigger_ddl_commandsも同様に抜けていましたが、「オブジェクトのサブID（例：列の属性番号）」「(列の属性番号のような)オブジェクトの副id」と統一されていませんでした。
Sub-object IDもサブオブジェクトIDとオブジェクトのサブIDとなっているところがあり、見直しが必要そうです。

**Comment by noborus** [comment]
#2537 関連でした。

**Comment by noborus** [comment]
対応済みということクローズします。ありがとうございました。
