### ISSUE TITLE
「クロスコンパイル」が「黒須コンパイル」になっている

### ISSUE THREAD

**Issue by pato-taityo** [pgsql-jp/jpug-doc#2539]
### 問題の詳細

https://www.postgresql.jp/document/14/html/install-procedure.html
「黒須コンパイル」とありますが、「クロスコンパイル」の誤りと思われます。

doc_ja_15 でも installation.sgml に誤字が残っているようです。

### 貢献者として記載可否

記載（貢献者欄に書いてください）

### 貢献者名

伊東 貢一

**Comment by pato-taityo** [comment]
#2540 で Pull request しました。

**Comment by koizumistr** [comment]
指摘ならびに修正案ありがとうございました。#2540 をマージしましたのでこちらはクローズします。
