### ISSUE TITLE
メークファイル

### ISSUE THREAD

**Issue by tatsuo-ishii** [pgsql-jp/jpug-doc#2556]
### 問題の詳細

extend.sgmlで"makefile"の訳語として「メークファイル」という言葉が複数ヶ所出てきます。わかりにくいので"makefile"の方が良いと思います。

### 貢献者として記載可否

記載（貢献者欄に書いてください）

### 貢献者名

SRA OSS LLC

**Comment by KenichiroTanaka** [comment]
ご指摘の通りかと思います。
私もmakefileが良いように思います。

**Comment by KenichiroTanaka** [comment]
PRをマージしたのでクローズします。
