### ISSUE TITLE
不審なtag

### ISSUE THREAD

**Issue by tatsuo-ishii** [pgsql-jp/jpug-doc#2598]
### 重要度

低

### 問題点

"REL"というtagが最近追加されたようなのです。私のマージコミットに付けられているようなのですが、誰かこのtagについてご存知の方はいらっしゃいますか？

### 背景

私は付けた覚えがないのですが、もしかしてしらないうちにオペミスしてしまったでしょうか？ちなみに問題のコミットはこれです。

> $ git show REL
> commit 0226b62fb911d4acaf1cf900692d074b1040406e (tag: REL)
> Merge: 3be493bd96 f5926b2eca
> Author: Tatsuo Ishii <ishii@sraoss.co.jp>
> Date:   Thu Mar 23 16:57:28 2023 +0900
> 
>     Merge pull request #2569 from noborus/protocol150
>     
>     protocol.sgmlの15.0対応です

### 貢献者として記載可否

記載（貢献者欄に書いてください）

**Comment by KenichiroTanaka** [comment]
私はこのTAGは認識していません。
REL_XX_XXとdiffするオペレーションで混入してしまった、などでしょうか。
@noborus さん
不要なタグだと思いますが、何かご存じだったりしますでしょうか。

**Comment by noborus** [comment]
https://github.com/pgsql-jp/jpug-doc/tags
にないのでローカルタグだと思います。経緯はわかりませんが、消してしまっても問題ないかと。

**Comment by tatsuo-ishii** [comment]
ありがとうございます。私のミスでローカル環境でtagを作ってしまった可能性が高いですね。削除しておきます。
issueはクローズします。
