### ISSUE TITLE
estimatedが文書全体で統一されていない

### ISSUE THREAD

**Issue by KenichiroTanaka** [pgsql-jp/jpug-doc#2599]
### 重要度

低

### 問題点

https://github.com/pgsql-jp/jpug-doc/pull/2588
で話題に上がった件です。

### 貢献者として記載可否

以前の記載名を使用

**Comment by noborus** [comment]
統一を考えているのは、「estimated cost」です。他のestimatedは文脈により変わる場合があります。

* 見積もりコスト
* 推定コスト
* コスト推定(cost estimateの場合はこれで良いのかも)

**Comment by pato-taityo** [comment]
リレーショナルデータベース入門[第３版]（サイエンス社）
P235 には「推定コスト (estimated cost)」との記載がありました。

https://www.ibm.com/docs/ja/informix-servers/12.10?topic=set_explain_output
「ESTIMATED COST (見積りコスト)」

私としては「推定コスト」が最もしっくりきています（根拠は無くてすみません…）。

**Comment by KenichiroTanaka** [comment]
私も個人的には推定コストがしっくりきています。
OSS-DBの資格対策でも推定コスト、と表現されているようです。
https://oss-db.jp/dojo/dojo_info_10

**Comment by noborus** [comment]
見積もりコスト(jit.sgml4箇所)と見積コスト(config.sgml1箇所)がありましたが、推定コストに統一するなら、これらだけで済みそうです。
