### ISSUE TITLE
カタカナの長音ルール

### ISSUE THREAD

**Issue by tatsuo-ishii** [pgsql-jp/jpug-doc#2617]
### 重要度

高

### 問題点

カタカナの末尾に付ける長音「ー」の有無について、統一されたルールが現状無いようです。その結果、ルールに基づくのではなく、何となくその時に長音有無の多数派に寄せましょう、的なpull requestが乱立し、翻訳のブラッシュアップが終わりの見えない作業になってしまっています。

### 背景

以前はJISに基づく基準で長音の有無を決めていたのでルールの曖昧さはなかったのですが...

### 解決方法

個人の好みや、「多数派に寄せる」といった曖昧なものではなく、ルールの確立が必要だと考えます。

### 貢献者として記載可否

記載（貢献者欄に書いてください）

**Comment by noborus** [comment]
一応ルールはまだ変わっていないという認識です。
長音ルールはいずれ省くのを止めて付けるように変更せざるをえないと考えていますが、未だ合意が取れておらず変更出来ていません。
#2280 は本来省かずにつけておく用語が省かれていたものの修正で、それ以外は長音が無い方にしていると思います。

他のプロジェクトでは長音を付けるように変更されているため、ほっておくとどんどん長音の有る無し両方混在した状態になってしまいますが、
NGリストでチェックできるようになったので、#2395 のように統一できると思います。
15.3が完了すれば最新に追いついて、時間的余裕ができるので統一修正ができると考えています。

それで、省くように統一しても結局は変更せざるをえないので長音を付けるように統一するように合意が取れると解決になるのですが、どうでしょうか？
ルール的には JTF日本語標準スタイルガイド(翻訳用）( https://www.jtf.jp/tips/styleguide ) になると思います。

現在PostgreSQL文書内で使用されている対象の語は以下です。

```
アイデンティティ  アイデンティティー
インジケータ  インジケーター
エディタ  エディター
エントリ  エントリー
オペレータ  オペレーター
カウンタ  カウンター
カテゴリ  カテゴリー
コミュニティ  コミュニティー
コントローラ  コントローラー
コンバータ  コンバーター
コンパイラ  コンパイラー
コンピュータ  コンピューター
サーバ  サーバー
サマリ  サマリー
ジェネレータ  ジェネレーター
ジェネレータプー  ジェネレータープー
スーパーバイザ  スーパーバイザー
スキャナ  スキャナー
セキュリティ  セキュリティー
セパレータ  セパレーター
ディレクトリ  ディレクトリー
ドライバ  ドライバー
ハンドラ  ハンドラー
バイナリ  バイナリー
バッテリ  バッテリー
バッファ  バッファー
パーティ  パーティー
パラメータ  パラメーター
ビューア  ビューアー
ファミリ  ファミリー
フィルタ  フィルター
ブラウザ  ブラウザー
プライマリ  プライマリー
プロセッサ  プロセッサー
プロバイダ  プロバイダー
ヘッダ  ヘッダー
ポインタ  ポインター
マスタ  マスター
マネージャ  マネージャー
メモリ  メモリー
メンバ  メンバー
ユーザ  ユーザー
ユーティリティ  ユーティリティー
ライタ  ライター
ライブラリ  ライブラリー
ラスタ  ラスター
リーダ  リーダー
リポジトリ  リポジトリー
レイヤ  レイヤー
レシーバ  レシーバー
レジストリ  レジストリー
```

**Comment by tatsuo-ishii** [comment]
すべて長音を付けるのはマイクロソフトが言い出したルールで、マイクロソフトの影響力が大きいのでデファクトになってしまった感がありますが、すべてのメーカがそれに追従しているわけではありません。たとえば富士通やNEC、それにAppleは今でも「コンピュータ」です。将来は「長音ルールはいずれ省くのを止めて付けるように変更せざるをえない」かもしれませんし、そうではないかもしれませんが、こうした現状を踏まえると、今すぐルールを変更する必要はないと思います。まあ、ユーザから「コンピューター」が「コンピュータ」になっていないのが気になってしょうがない、みたいな苦情が殺到すれば別ですが。

**Comment by noborus** [comment]
私は、先に一般用語として長音をつけていたけど、IT業界では省くようになっていたのを止めたという認識です。
長音を付けると違和感がある人がいるのは理解しますが、長音をついている語を見たことがないという人はいないと思ってます。

逆に、長音を省くのをPostgreSQLのマニュアルで初めて見たという人が、そろそろ出てくるのではないないかと思ってます。
Windowsを使っていてWordPressを使ってからPostgreSQLを使ってみようとマニュアルを見たら長音を省くのを見る機会がこれまでなくても不思議ではありません。
10年前なら、まだいなかったと思いますが、そういう人は今後も増えていくだろうと考えています。

**Comment by tatsuo-ishii** [comment]
ワープロやその他の個人用のツールのマニュアルなら、長音を省かないカタカナの方が違和感はないでしょう。
しかし、そもそもこのマニュアルを真剣に読むような人は、読者層がかなり違うのではないでしょうか。
おそらく、最低限のITの予備知識があるか、あるいは勉強中で、このマニュアル以外にもIT関係のマニュアルや参考書を読んでいると思います。そういう人が読んでいるであろうものとして、たとえばITパスポートの例題を見てみるとわかりますが、JIS式の長音を省くカタカナが使われています。
https://www.itpassportsiken.com/kakomon/01_sample/q45.html
こうした読者層を考えると、現状ではPostgreSQLのカタカナ表記がまだまだ適切だと思います。

**Comment by noborus** [comment]
> ワープロやその他の個人用のツールのマニュアルなら、長音を省かないカタカナの方が違和感はないでしょう。
> しかし、そもそもこのマニュアルを真剣に読むような人は、読者層がかなり違うのではないでしょうか。
> おそらく、最低限のITの予備知識があるか、あるいは勉強中で、このマニュアル以外にもIT関係のマニュアルや参考書を読んでいると思います。そういう人が読んでいるであろうものとして、たとえばITパスポートの例題を見てみるとわかりますが、JIS式の長音を省くカタカナが使われています。
> https://www.itpassportsiken.com/kakomon/01_sample/q45.html
> こうした読者層を考えると、現状ではPostgreSQLのカタカナ表記がまだまだ適切だと思います。

私もPostgreSQLがそこまで先行する必要はないと考えていましたが、結局変えることになる流れだと思ってます。
ITパスポートはよく知らなかったですが、対象層を考えると既に長音省略の用語が障壁になっていると感じました。
https://youtu.be/aGLT6DANgZ0?t=13
最低限の範囲によるのですが、Ubuntu入れて、なにか言語の本買って学んで、
データベースも使ってみようと考えた人が長音省略になじみがないことがあり得るようになってきたと思います。

**Comment by noborus** [comment]
まず、情報の非対称性があります。
長音ありと長音省略の両方の用語に触れていて、どちらが違和感ないかという前提であれば、多数派をとればよいですが（2010年頃ではそう仮定して問題なかったと思います）、
既に長音省略をほとんど見ていない人が出てきていて、今後さらに増えることが予想されます。
長音省略に違和感がないという人たちが、長音ありをほとんど見たことがないとするのは無理があります。
（長音省略に馴染んでいる方に「長音を付ける書き方があるのです」。といった注意書きは必要ありません）。
つまり違和感のレベルではなく、ITパスポートのように注意書きがないと理解しづらい人たちが存在しているということです。

そして、PostgreSQLマニュアルの読者を想定はしても限定はしていないので、検索エンジンに引っかかったから一部分だけ読むでも構わないですし、
内容によって理解できるところだけ読んでも良いと思ってます。
そういったPostgreSQLマニュアルを一部でも読んだことがある人を対象に広げた場合、長音ありの方が違和感ないという人が多数派になると思います。
それから現在出ているPostgreSQL関連の書籍やRDBMSに関する文書は、PostgreSQLマニュアルの表記に合わせていたり、気にしていると思うので、
そちらがまだだから変えなくて良いというのは流れ的に違うのではないかと思います。

**Comment by tatsuo-ishii** [comment]
> 長音省略に違和感がないという人たちが、長音ありをほとんど見たことがないとするのは無理があります。

私は「長音ありをほとんど見たことがない」とは書いていないのですが。
私が言っているのは、仕事や研究などで見ている文書はJIS式のカタカナ長音表記であろうと言っています。これは自然な仮定だと思いますが、違いますか？

>そういったPostgreSQLマニュアルを一部でも読んだことがある人を対象に広げた場合、長音ありの方が違和感ないという人が多数派になると思います。

PostgreSQLマニュアルの読者層をできるだけ広げてカバーしたいという気持ちはわかりますが、この文書を真剣に読む人（つまり私が言っている読者層）と、検索してちょっと一部だけ読む読者では、どちらを重視あるいは気にかけるべきかは、自ずと違ってくるでしょう。

> RDBMSに関する文書は、PostgreSQLマニュアルの表記に合わせていたり

さすがにそれはないでしょう。単にPostgreSQLマニュアル同様、JIS式表記にあわせている、と考えたほうが自然です。

**Comment by noborus** [comment]
> > 長音省略に違和感がないという人たちが、長音ありをほとんど見たことがないとするのは無理があります。
> 
> 私は「長音ありをほとんど見たことがない」とは書いていないのですが。 私は、仕事や研究などで見ている文書はJIS式のカタカナ長音表記であろうと言っています。これは自然な仮定だと思いますが、違いますか？

書いていたと言いたいわけではなくて、言いたかったことは非対称性だということです。
主に見ている文書が長音省略である人でも長音ありの用語を日常的に見ているはずです。しかしながら、逆はそうではないという非対称性です。
つまり、長音省略に違和感あり vs 長音ありに違和感ありではなく、
長音省略を目にしていない & 長音省略に違和感あり vs 長音ありに違和感あり（長音ありを目にしていない人はいない）
というのが前提となります。

> > そういったPostgreSQLマニュアルを一部でも読んだことがある人を対象に広げた場合、長音ありの方が違和感ないという人が多数派になると思います。
> 
> PostgreSQLマニュアルの読者層をできるだけ広げてカバーしたいという気持ちはわかりますが、この文書を真剣に読む人（つまり私が言っている読者層）と、検索してちょっと一部だけ読む読者では、どちらを重視あるいは気にかけるべきかは、自ずと違ってくるでしょう。
> 
> > RDBMSに関する文書は、PostgreSQLマニュアルの表記に合わせていたり
> 
> さすがにそれはないでしょう。単にPostgreSQLマニュアル同様、JIS式表記にあわせている、と考えたほうが自然です。

さすがにその抜き出し方はないでしょう。
PostgreSQL関連の書籍はPostgreSQLの表記に合わせたり、気にしたりするのが想定されて、
特定のRDBMSに依らない文書を書くときは、主要なデータベースの用語に合わせたり、気にしたりするでしょう。という意味で書きました。

JISの長音省略の根拠はすでに改定されていて、平成3.6.28 内閣告示第2号 によるとされていて、
内閣告示第2号では「ただし,慣用に応じて「ー」を省くことができる。」ということなので、
書く人の慣用かそのジャンルや組織の慣用ということになります。
JIS SQLらへんの実際の文書の表記の意味では長音のありなしは既に参考にしないと思います。古いので。 

PostgreSQL関連の書籍も長音省略なので、慣用が長音省略だからマニュアルも長音省略とするのは逆で、マニュアルが長音省略なので、PostgreSQL入門書を書くときも合わせたと考える方が自然です。

IT関連やソフトウェア業界の慣用が長音省略とするのは既に苦しくなってきているので、
データベース界隈では長音省略が慣用となっているというのは確かにあると思いますが、
PostgreSQLがそれに加担していて、マッチポンプ的な意味合いもあると思います。

ということで、前提としたのをもう一度取り出させてもらうと、
長音省略の方が慣れている人に長音ありにしても解らなくなるといったことはないし、どうせすぐ慣れるし、
うっかり書いてしまうし、レビューでも抜けてしまいますが、
長音ありに慣れている人の中には、長音省略に戸惑う人もいれば、誤植を疑う人もいて、誤植と考えるならまだ良くて、
違う用語ととらえて混乱する人がいる**かも**しれない。
今はいなくてもすぐに出てくる段階に入ったと考えています。

**Comment by tatsuo-ishii** [comment]
> IT関連やソフトウェア業界の慣用が長音省略とするのは既に苦しくなってきているので、

そうなんですか？何か具体的な根拠があれば教えて頂けると助かります。商業出版や、商業ソフトの世界では、利益=読者や顧客が第一なので、そういう状態なのであればとっくに長音ありにしていると思いますが。

> PostgreSQLがそれに加担していて、マッチポンプ的な意味合いもあると思います。

どう考えてもPostgreSQLのマニュアルの影響を受けそうにないOracleのマニュアルもJIS式ですし、最近読んだRDBMS関連の書籍「データ指向アプリケーションデザイン(Martin Keleppmann著、斉藤太郎監訳」、「リレーショナルデータベース入門(斉藤良文)」でも、JIS式でした。
というわけで、私の目には、依然としてRBMS界ではJIS式が主流と見えますし、PostgreSQLマニュアルの影響を受けてこれらの文書がJIS式にしているとも思えません。

**Comment by noborus** [comment]
> > IT関連やソフトウェア業界の慣用が長音省略とするのは既に苦しくなってきているので、
> 
> そうなんですか？何か具体的な根拠があれば教えて頂けると助かります。商業出版や、商業ソフトの世界では、利益=読者や顧客が第一なので、そういう状態なのであればとっくに長音ありにしていると思いますが。

2008年以前は IT関連やソフトウェア業界では長音省略が慣用といって問題なかったですが、それ以降は両方使われるというのが適切だと思います。両方使われるがさらに苦しくなってきたのですが、これは後述します。

> > PostgreSQLがそれに加担していて、マッチポンプ的な意味合いもあると思います。
> 
> どう考えてもPostgreSQLのマニュアルの影響を受けそうにないOracleのマニュアルもJIS式ですし、最近読んだRDBMS関連の書籍「データ指向アプリケーションデザイン(Martin Keleppmann著、斉藤太郎監訳」、「リレーショナルデータベース入門(斉藤良文)」でも、JIS式でした。 というわけで、私の目には、依然としてRBMS界ではJIS式が主流と見えますし、PostgreSQLマニュアルの影響を受けてこれらの文書がJIS式にしているとも思えません。

1行前に「データベース界隈では長音省略が慣用となっているというのは確かにあると思いますが」
と書いてあるのを無視されたら話として成立していないと思いますが、再度詳しく書くと、

PostgreSQL関連本はPostgreSQLの記述に従いますし、Oracleの関連本は、Oracleのドキュメントに従います、特定のデータベースではない、例えばSQL入門の本であっても長音を省略していたら、
それは主要なデータベースが長音省略を採用しているのが影響していると考えてます。
例外はありますし、「リレーショナルデータベース入門」までいくと主要なデータベースのドキュメントがすべて長音ありになっていても作者の慣用により、
長音省略で書き続ける可能性はあるでしょう。

> JISで「長音ありでも良い」と決まったのが2005年、MSが長音付きにすると宣言したのが2008年です。それから20年近く経ってもRDBMS界では依然として長音なしが主流です。
なので、私はRDBMS界の多数が長音付きになるのは、おそらく更に10年以上かかるような気がします。（あるいは10年経ってもそうならない可能性もあるかも）
> 20年経っても変わらない理由は色々あるでしょうが、やはり「本当に困っている人がいない」からではないでしょうか。
> そして、20年続いていたその状態が最近になって急に変わるという理由も見当たらないです。

私の見解は違います。私の見解とGoogleトレンドの傾向が近いので、そのグラフを利用させてもらいます。

2006年から現在までのサーバ、サーバーの比較です。インターネット、通信事業を選択しています。
https://trends.google.co.jp/trends/explore?cat=13&date=2006-04-17%202023-05-17&q=%E3%82%B5%E3%83%BC%E3%83%90,%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC&hl=ja

![Screenshot from 2023-05-17 15-06-50](https://github.com/pgsql-jp/jpug-doc/assets/2296563/4583db10-1f5a-44b4-85a2-291bf8626318)

* [ヘッダ、ヘッダーの比較](https://trends.google.co.jp/trends/explore?cat=13&date=2006-04-17%202023-05-17&q=%E3%83%98%E3%83%83%E3%83%80,%E3%83%98%E3%83%83%E3%83%80%E3%83%BC&hl=ja)
* [ユーザ、ユーザーの比較](https://trends.google.co.jp/trends/explore?cat=13&date=2006-04-17%202023-05-17&q=%E3%83%A6%E3%83%BC%E3%82%B6,%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC&hl=ja)

傾向は根拠有ると思いますが、これから書く解説は個人の見解です。数値はピークが100としたときの相対評価らしいです。

2008年までは長音省略の方が主流でしたが、それ以降は両方ある状態になります。
2010年代は差がつき始めますが、急激下がらずに推移するため長音ありを使う人でも普通に長音省略に触れるために両方あると認識されています。
2008年のマイクロソフトの変更が知られているので、最初はどちらを採用するかと書く人が多かったですが、
2012年ぐらいから、両方あるけどどっちが正しいのか、から調べて「両方正しい」にいきつく人が増えます。
2018年までは差がつきつつも両方認識されています（数値でいうと15）が、
2019年にJISが原則長音あり、長音省略を許容すると解釈されるようになると、長音省略は古いJISであった、一部の方面で使わていると書く人が出てきます。
2020年代で（数値でいうと10を下回るようになると）、2020年以降にインターネット、通信事業業界に入った人の中で認識してない人が出てきます。

私は、調べる前は2010年代と変わらない認識でしたが、どうもしきい値を下回りはじめたようだと考えを変えました。

長音ありへの変更は、エンドユーザーに近いところから変えるだろうと考えていましたので、PostgreSQLが先行する必要はないと思っていましたが、
データベース界隈では先行して良いと考えています。マニュアルの対象者はデータベース開発者ではなくデータベース利用者で、
はじめて使うデータベースがPostgreSQLであって良いと考えているからです。

**Comment by tatsuo-ishii** [comment]
つまり、現在のDBMS界の出版文書(マニュアル、書籍、資格試験の問題文などを含む）で実際のカタカナ長音の記法がどうであれ、インターネットの検索傾向で長音ありが増えているから、率先してPostgreSQLマニュアルを長音ありにしよう、ということですか。
それだとおそらく今後おそらく10年くらいにわたって、現在のDBMS界の出版文書の中で、ほぼPostgreSQLマニュアルだけが長音ありになっている状態が続くと私は予想します。そうすると、斎藤さんの考えは以下のどっちかになるのでしょうか？

1. いや、その予想はあたらない。近いうちに(1-2年?)のうちにDBMS界の出版文書も長音ありが多数派になるはずだ。
2. 今後10年くらいに渡って、RDBMSの文書界隈ではPostgreSQLマニュアルだけが長音ありになるかもしれないが、それでも構わない。

1であると言うならまだわかりますが、2であるとすると、私はちょっと賛同しかねます。
仮にJIS式を止めることになったとして、人からその理由を聞かれても、私には説明ができないです。

**Comment by tatsuo-ishii** [comment]
> リレーショナルデータベース入門」までいくと主要なデータベースのドキュメントがすべて長音ありになっていても作者の慣用により、
> 長音省略で書き続ける可能性はあるでしょう。

これは見逃せないので反論しておきます。データベース研究論文、著作ではほぼ全てでJIS式のカタカナ記法を採用していると思います。その事実を無視して、推測で語るのはいかがなものかと思います。

**Comment by KenichiroTanaka** [comment]
私も長音省略が主流だと信じていましたが、
Oracle,AWSの最新ドキュメントを見てみると長音ありでした。
※ユーザー、クラスターなどの文字を見て長音ありと判断しています。

https://docs.oracle.com/cd/F39414_01/admin/getting-started-with-database-administration.html#GUID-EA8CC987-EF18-4434-B962-01312CD3A8AC

https://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/AuroraUserGuide/CHAP_Aurora.html

もちろんMSも長音有りです。
https://learn.microsoft.com/ja-jp/azure/azure-sql/database/sql-database-paas-overview?view=azuresql

最近のマニュアルではRDBMS業界でも長音有りが普通になってきているのでそろそろPostgreSQLも
追随していいのでは？と思いました。

**Comment by tatsuo-ishii** [comment]
> 私も長音省略が主流だと信じていましたが、
> Oracle,AWSの最新ドキュメントを見てみると長音ありでした。
> ※ユーザー、クラスターなどの文字を見て長音ありと判断しています。

URLのOraleのドキュメントを見てみました。しかし、一方で、「セキュリティ」というのもありますね。（斉藤さん案では「セキュリティー」）。「ユーティリティ 」「コンピュータ」も同様（斉藤さん案では「ユーティリティ ー」「コンピューター」）。必ずしも長音ありではないようです。
MySQL 8.0(たぶん最新バージョン)では、「ユーザー」「クラスタ」「セキュリティー」「ユーティリティ ー」「コンピュータ」でした。微妙にOracleと違う...

**Comment by noborus** [comment]
既に何度も書いていますが、ソフトウェア分野において長音省略は苦しくなっており、JISの原則からも外れています。
今後は、さらに細分化された分野、組織で残っていく可能性はあると思います。
さらに、いくつかの用語は一般にも通用する用語として残りますが、
JISの「2音の用語は長音符号を付け、3音以上の用語の場合は長音符号を省く」というルール自体が「常識とは」されなくなり、
調べないと把握されない状態になっていくと予想しています。

> URLのOraleのドキュメントを見てみました。しかし、一方で、「セキュリティ」というのもありますね。（斉藤さん案では「セキュリティー」）。「ユーティリティ 」「コンピュータ」も同様（斉藤さん案では「ユーティリティ ー」「コンピューター」）。必ずしも長音ありではないようです。
> MySQL 8.0(たぶん最新バージョン)では、「ユーザー」「クラスタ」「セキュリティー」「ユーティリティ ー」「コンピュータ」でした。微妙にOracleと違う...

失礼しました。私が上に上げたのは、「JTF日本語標準スタイルガイド」がベースになっていると思います。
他にベースとなりうるのはマイクロソフトの方針が上がっていて、この２つは違いがあります。
どちらでいくのか、又は一部違うルールでいくのかは、また議論の余地があると思います（セキュリティーよりもセキュリティが一般でも多数派かもしれません）。

この違いがある用語については、今後もどちらを使用して問題ないままだと予想されますが、それ以外は認識されづらくなっていくだろうと予想してます。
「ユーザ」に引っかからなくても「ヘッダ」には？な顔をされるという予測です。
ちなみに私も2019年より前（だいぶサバよみました）からソフトウェア分野でやっていて、長音省略に慣れ親しんでいるので、主観ではなく調べた結果による予測です。

**Comment by tatsuo-ishii** [comment]
> JISの原則からも外れています。

これは誤解を招く言い方ではないですか？JISは「長音は用いても省いても誤りではない」と言っているだけで、「長音を付けるのが原則」とは言っていないです。

MSが巨大企業でユーザが多いからそのルールに従うという考えもあるでしょうが、そもそもMSは長音に関するルールを自分たちの製品の中で使うために決めているだけで、それを世の中の標準にしたいという意図は無いはずです。Oracleやその他の企業もMSルールに右に習えになるところまでくればいわゆるデファクトスタンダードになるので、採用の検討もあり得ると思いますが、そうはなっていないし、将来そうなると言う見通しもないように思えます。
つまり、カタカナの長音ルールは、今後も統一されないまま混乱した状態が続くというのが現実的な予想でしょう。

そうすると、このグループで、MSにせよ、JTFにせよ、独自ルールを決めるにせよ、どれを選んでも業界の他とは違うルールを選ぶことになるわけです。（デファクトスタンダードがないので）それで良いのですかね。

**Comment by noborus** [comment]
> > JISの原則からも外れています。
> 
> これは誤解を招く言い方ではないですか？JISは「長音は用いても省いても誤りではない」と言っているだけで、「長音を付けるのが原則」とは言っていないです。

JIS Z 8301 : 2019）で「外来語の表記は、主として”外来語の表記（平成3.6.28　内閣告示第２号)”による。」
となっていて、https://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kijun/naikaku/gairai/honbun06.html は

> 注3　英語の語末の‐ｅｒ,‐ｏｒ,‐ａｒなどに当たるものは,原則としてア列の長音とし長音符号「ー」を用いて書き表す。ただし,慣用に応じて「ー」を省くことができる。

ということで原則は長音符号をつけると解釈しています。

> MSが巨大企業でユーザが多いからそのルールに従うという考えもあるでしょうが、そもそもMSは長音に関するルールを自分たちの製品の中で使うために決めているだけで、それを世の中の標準にしたいという意図は無いはずです。Oracleやその他の企業もMSルールに右に習えになるところまでくればいわゆるデファクトスタンダードになるので、採用の検討もあり得ると思いますが、そうはなっていないし、将来そうなると言う見通しもないように思えます。 つまり、カタカナの長音ルールは、今後も統一されないまま混乱した状態が続くというのが現実的な予想でしょう。
> 
> そうすると、このグループで、MSにせよ、JTFにせよ、独自ルールを決めるにせよ、どれを選んでも業界の他とは違うルールを選ぶことになるわけです。（デファクトスタンダードがないので）それで良いのですかね。

最初からの主張ですが、長音を付ける用語は違和感があるという人でも避けるのが難しいレベルで目に入るぐらい使用されていて、
長音省略は避けようとしなくても触れないまま通ってこれてしまうレベルで減ってしまった
というのが調べた結果なので、まだ多く使われている語やあいまいな部分を根拠にして全体を長音省略にするのは良いとは思いません。
逆に長音をつけて問題ない語を全部つけてしまっても読むには困らないだろうと思ってます。

書くのは負担なので統一されずに残そうとするのは、止めた方が良いと主張はしていきたい...

**Comment by KenichiroTanaka** [comment]
A.長音をつけることはすでに受け入れらている方向にある
B.ただし統一された規格が無く他とは違うルールになる

という点は共通認識になった理解で合っているでしょうか。
悩ましいところですね。他社、他コミュニティのドキュメントで長音をつけた時にどのような議論がなされたか参考になる情報をお持ちの方はいらっしゃったりしないでしょうか。

あとは、長音ありに変更するとして、OSS-DBSilverを提供しているLPIや各社PostgreSQL関連のサービスを提供しているのドキュメント、教育コンテンツ、GUIツールへの影響の考慮は必要ではないでしょうか。基本はマニュアルに合わせてもらう方向になると思いますが、突然変わるのは困るのではないかと思います。
例えば「バージョン16から変更します」などの予告はあった方が良いのではないかと思います。

**Comment by tatsuo-ishii** [comment]
> A.長音をつけることはすでに受け入れらている方向にある

誰が受け入れているかの主語を明示しないと、一概に言えないという認識です。
https://ja.wikipedia.org/wiki/%E9%95%B7%E9%9F%B3%E7%AC%A6
の「実態」の章参照。

> B.ただし統一された規格が無く他とは違うルールになる

はい、その認識です。

**Comment by noborus** [comment]
> あとは、長音ありに変更するとして、OSS-DBSilverを提供しているLPIや各社PostgreSQL関連のサービスを提供しているのドキュメント、教育コンテンツ、GUIツールへの影響の考慮は必要ではないでしょうか。基本はマニュアルに合わせてもらう方向になると思いますが、突然変わるのは困るのではないかと思います。
> 例えば「バージョン16から変更します」などの予告はあった方が良いのではないかと思います。

まず、バージョンで分けると15と16で対応を変えたりと書き手に負担がかかるので、時期で分けるようにしてこれ以降に更新するものは変更するようにしたほうが良いと思います。
バージョンで変えるとバックポートも困難になります。
それから、対外的にはどちらでも問題ないとしつつ、内部的にはこう決めたという話にしないと、他のものも含めて変更しなければならないプレッシャーがかかります。
また一回で全部変更できるわけではなくて、変更自体は用語単位で変えるので、一部見送ったり戻したりする可能性があります。

ということで、変更できるときに変更して、
〇〇年〇〇月〇〇日に（〜に沿って）長音符を付けるようにしました、それ以前の文書では長音符が省略されている場合があります。
ぐらいの注意書きを足すぐらいにするのが良いと思います。

**Comment by noborus** [comment]
変換準備が整ってきました。

単語を統一するというのは合意されていると思います。
現在長音を省略するようになっているので、長音を付けてしまっている単語を長音無しに変換してNG語に追加すれば、ほとんど統一できます。

対象は以下です。数字は文書内に含まれている数です。１回で変換するのは多いですが、数回に分けてPRを出せば可能な数です。

```
      1 カテゴリー
      1 スーパーバイザー
      1 セキュリティー
      1 バッテリー
      1 バッファー
      2 カウンター
      2 サードパーティー
      2 スキャナー
      3 レイヤー
      3 レシーバー
      4 パラメーター
      5 プライマリー
      6 エントリー
      6 ポインター
      7 ファミリー
      7 ヘッダー
     14 メモリー
     22 サマリー
     31 サーバー
     34 フィルター
     59 メンバー
     67 ユーザー
```

逆に長音を付けるように変更する場合は、数千（万？）箇所の変換になるので、計画立てて実行する必要があります。

**Comment by noborus** [comment]
JTF日本語標準スタイルガイドにあった単語は統一しましたが、その他に長音の統一が出来ていない単語があります。

```
      6 サブスクライバ
    106 サブスクライバー
     18 シグネチャ
      5 シグネチャー
     67 スカラ
     21 スカラー
     56 ダーティ
      1 ダーティー
   1066 トリガ
     64 トリガー
    216 パーサ
      1 パーサー
     29 プレースホルダ
      6 プレースホルダー
      6 ベンダ
      4 ベンダー
      7 ペナルティ
      1 ペナルティー
      9 ランチャ
      5 ランチャー
```

サブスクライバー以外は長音を省くほうが多いので省く方に統一するで良いと思いますが、 サブスクライバーは長音ありで統一する方が良さそうです。
パブリッシャー（こちらは長音ありに統一）と対なので揃っていた方が良さそうです。

**Comment by koizumistr** [comment]
現時点では src/backend/catalog/sql_features.txt.ja は対象外なので、エラーになっていないのですが、「ラッパ」となっているようです。

**Comment by noborus** [comment]
対象を広げて修正します。
以下にしようと思ってます。

```diff
diff --git a/doc/src/sgml/Makefile b/doc/src/sgml/Makefile
@@ -286,7 +286,7 @@ check-tabs:
 # words to avoid as pgsql-jp
 check-ng:
 	@ln -sf $(top_builddir)/.ng.list .ng.list
-	@if git --no-pager grep -E --color=always -f .ng.list *sgml ref/*sgml; \
+	@if git --no-pager grep -E --color=always -f .ng.list $(srcdir)/*.sgml $(srcdir)/ref/*.sgml $(top_builddir)/src/backend/catalog/*.txt.ja; \
 	then \
 	  echo "使用NGな語が見つかりました。";\
 	  false;\
```

**Comment by noborus** [comment]
> 現時点では src/backend/catalog/sql_features.txt.ja は対象外なので、エラーになっていないのですが、「ラッパ」となっているようです。

#3124 で修正しました

**Comment by noborus** [comment]
一応統一の対応が終わって、この後の変更をどするかは #3107 に移動しようと思います。
よければ、こちらはクローズします。
