### ISSUE TITLE
リリース15の誤記修正提案

### ISSUE THREAD

**Issue by pato-taityo** [pgsql-jp/jpug-doc#2681]
### 問題の詳細

release-15.sgml で "123 abc" という記載がありますが、正しくは "123abc" だと思われます（間のスペースが不要）。
原文で間のスペースが無いこと、また挙動としてもスペースが無い場合の説明をしていると思われるため。

### 貢献者として記載可否

以前の記載名を使用

**Comment by tatsuo-ishii** [comment]
ご指摘の通り、翻訳の修正が必要と思われます。

**Comment by pato-taityo** [comment]
早速のご確認をありがとうございました。私が修正を担当させていただきます。
