### ISSUE TITLE
wal.sgmlの翻訳誤り？

### ISSUE THREAD

**Issue by HUUTFJ** [pgsql-jp/jpug-doc#2683]
### 問題の詳細

wal.sgmlファイルに下記の記載がありますが、`<option>--with-wal-segsize</option>`は`<option>-wal-segsize</option>`の誤りではないでしょうか？

```
(ただし、このサイズは<application>initdb</application>の<option>--with-wal-segsize</option>オプションで変更できます)。
```

元の英文は下記のようになっています。

```
(but the size can be changed
   by altering the <option>&#45;-wal-segsize</option> <application>initdb</application> option).
```

また、initdbのマニュアルでは`--wal-segize`となっています[1]。

```
--wal-segsize=size
Set the WAL segment size, in megabytes. This is the size of each individual file in the WAL log. The default size is 16 megabytes. The value must be a power of 2 between 1 and 1024 (megabytes). This option can only be set during initialization, and cannot be changed later.
```

[1]: https://www.postgresql.org/docs/15/app-initdb.html#:~:text=should%20be%20stored.-,%2D%2Dwal%2Dsegsize%3Dsize,-Set%20the%20WAL

### 貢献者として記載可否

以前の記載名を使用

**Comment by noborus** [comment]
おっしゃるとおりです。
10->11で原文が変更されていますが、追随できてなかったようです。
