### ISSUE TITLE
system-views.sgmlの翻訳誤り？

### ISSUE THREAD

**Issue by HUUTFJ** [pgsql-jp/jpug-doc#2685]
### 問題の詳細

system-views.sgmlの下記翻訳は、「この状態はreservedあるいはextendedに戻ることができます」ではないでしょうか？
該当項目はレプリケーションスロットの状態に関して述べたものであり、returnを「返す」と翻訳するのは違和感を覚えます。

```
原文：
This state can return to <literal>reserved</literal> or <literal>extended</literal>.
翻訳：
この状態は<literal>reserved</literal>あるいは<literal>extended</literal>を返します。
```

状態unreservedとはレプリケーションスロットのrestart_lsnとして指定されたWALが削除予定である(まだ削除されてはいない)ことを意味し、次のcheckpointまでにこの値が更新されれば健全な状態へと戻ることができるはずです。
実際、本状態を導入したコミットb8fd4e02には下記の記載があります。

>    (前略) unreserved means the
>    WAL is no longer safe, but checkpoint has not yet removed those files.
>    Such as slot is in imminent danger, but can still continue for a little
>    while and may catch up to the reserved WAL space.

そのため冒頭で示した案の方が適切だと思いました。

### 貢献者として記載可否

以前の記載名を使用

**Comment by noborus** [comment]
ありがとうございます。
確かにその通りだと思います。
