### ISSUE TITLE
PQputCopyEnd の説明の誤訳？

### ISSUE THREAD

**Issue by kubo** [pgsql-jp/jpug-doc#2724]
### 問題の詳細

`PQputCopyEnd` (https://www.postgresql.jp/document/15/html/libpq-copy.html#LIBPQ-PQPUTCOPYEND) の説明は以下のようになっています。

> ```
> int PQputCopyEnd(PGconn *conn,
>                  const char *errormsg);
> ```
> errormsgがNULLの場合は、COPY_IN操作の終了に成功しました。 errormsgがNULLでない場合は、COPYは強制的に失敗させられました。 errormsgが指し示す文字列はエラーメッセージとして使用されます。 （しかし、このエラーメッセージが正しくサーバから返ったものであるとは仮定すべきではありません。 サーバは既に別の原因でCOPYに失敗していた可能性があります。）

「成功しました」「失敗させられました」となっているので、COPY_IN の成否によって errormsg の値が変わるように読み取れます。しかし errormsg の型は `const char *` なので `PQputCopyEnd` が呼び出し側の変数を変えるのは不可能です。

そこで原文 (https://www.postgresql.org/docs/15/libpq-copy.html#LIBPQ-PQPUTCOPYEND) をあたってみたら以下のようになっていました。

> Ends the COPY_IN operation successfully if errormsg is NULL. If errormsg is not NULL then the COPY is forced to fail, with the string pointed to by errormsg used as the error message. (One should not assume that this exact error message will come back from the server, however, as the server might have already failed the COPY for its own reasons.)

errormsg がNULLかどうかで COPY の成否を決めています。

正しくは以下ではないでしょうか。

> errormsgがNULLの場合は、COPY_IN操作を成功として終了させます。 errormsgがNULLでない場合は、errmsgの指し示す文字列をエラーメッセージとして用いてCOPYを強制的に失敗させます。 （しかし、このエラーメッセージがそのままサーバから返ってくると仮定すべきではありません。 サーバは既に別の原因でCOPYに失敗していた可能性があります。）

### 貢献者として記載可否

記載（貢献者欄に書いてください）

### 貢献者名

久保 健洋

**Comment by tatsuo-ishii** [comment]
ご指摘ありがとうございます。仰るとおりで、誤訳ですね。
ところでいただいた改善案ですが、

> errormsgがNULLの場合は、COPY_IN操作を成功として終了させます。

の「場合」は不要ではないでしょうか。

> errormsgがNULLなら、COPY_IN操作を成功として終了させます。

ではいかがでしょう？

**Comment by kubo** [comment]
文体変えないため、元の文章は極力残すようにしていました。「errormsgがNULLの場合は、」は自分だったら「errormsgがNULLの場合、」にしていたと思います。このページの他の場所でも「if ~」を「~の場合」としている箇所が多いので。

「errormsgがNULLなら、」については個人的には口語的すぎるように感じますが、誤解させる表現ではないので、その訳でかまいません。

**Comment by KenichiroTanaka** [comment]
誤訳の報告ありがとうございました。
https://github.com/pgsql-jp/jpug-doc/pull/2727
でPRしています。

シンプルな「errormsgがNULLなら」の方で出していますが、気になるところがありましたらお知らせください。

**Comment by KenichiroTanaka** [comment]
@kubo さん
誤訳の報告をいただきありがとうございました。
#2727がマージされ次第15.4をリリースします。
その際、
https://github.com/pgsql-jp/jpug-doc/pull/2726
で貢献者として掲載させていただきます。ご認識ください。また、もし、問題ありましたらお知らせください。

**Comment by kubo** [comment]
マージ確認しました。修正ありがとうございます。
