### ISSUE TITLE
config.sgml 16機械翻訳

### ISSUE THREAD

**Issue by tatsuo-ishii** [pgsql-jp/jpug-doc#2733]
### 問題の詳細

config.sgmlの4732行目の「マッチ度」の数値が空白になっていますが、これは対応する原文が削除された時にこうなるのでしょうか？

> 《マッチ度[]》可能なら<literal>open_</literal>*オプションも<literal>O_DIRECT</literal>を使用します。

### 貢献者として記載可否

記載（貢献者欄に書いてください）

**Comment by noborus** [comment]
すみません。これはツール側の問題があったのをリカバリしたためです。
基本的に数値が入ってないだけです。

以下はツール側の事情詳細
jpug-doc-toolはpre内の翻訳対象であろう箇所の、まだコメントアウトされていない箇所を対象にしています。
そのため、マッチ度と機械翻訳はセットで入れるようになっています。
「マッチ度」や「機械翻訳」どちらかでも既に入っている場合は対象外です。
今回機械翻訳のAPI制限が厳しくなって１日の制限に引っかかってしまいました。
そこで途中からやり直したところ、類似文として入るはずの文が入っていない箇所が多く出てしまいました。
ツールでどちらかだけやり直せるようになっていなかったため、前ならば一旦リセットしてやり直すのですが、
今回API制限が厳しくなっていて、機械翻訳をやり直すと再度制限に引っかかってしまうため、
機械翻訳を残したままマッチ度の文を入れるため、半手動でリカバリしました。

**Comment by noborus** [comment]
今後はもう出ないようになったのでクローズします。
