### ISSUE TITLE
config.sgml で  (all statements)  が（全てのメッセージ）となっている

### ISSUE THREAD

**Issue by harukat** [pgsql-jp/jpug-doc#2802]
### 問題の詳細

config.sgml の log_statement の説明で以前から「(all statements)」 が「(全てのメッセージ)」となっています。
「(全ての文)」が正しいと思われます。

### 貢献者として記載可否

以前の記載名を使用

**Comment by KenichiroTanaka** [comment]
@harukat さん、ご報告ありがとうごいました。
修正が完了したので本ISSUESはクローズします。
