### ISSUE TITLE
doc/src/sgml/以下でないところではNGリストにあるものが使われている

### ISSUE THREAD

**Issue by koizumistr** [pgsql-jp/jpug-doc#2866]
### 重要度

低

### 問題点

 git grep -f .ng.listをトップディレクトリで（意図せず）実行したところ、doc/src/sgml/\*.sgml doc/src/sgml/ref/\*.sgml 以外のファイルでNGリストにあるものが使われていることが分かりました。具体的には以下の2つのファイルです。

- src/backend/catalog/sql_features.txt.ja
- src/backend/po/ja.po

### 解決方法

src/backend/catalog/sql_features.txt.ja は私たちが管理しているので揃えてしまえば良いと思います。（もしかしてJISの訳に意図的に合わせていたりしますか。）
src/backend/po/ja.po も揃えたいところではありますが、私たちが手を出しているファイルとは別なのでどうしましょう。

### 貢献者として記載可否

以前の記載名を使用

**Comment by KenichiroTanaka** [comment]
PR2864で修正されたのでクローズします。対応ありがとうございました。
