### ISSUE TITLE
version 9.5.1 sql.html typoです

### ISSUE THREAD

**Issue by noborus** [pgsql-jp/jpug-doc#468]
>ここでの内容は、初心者のユーザでも先のページを何度もを参照することなく、

ここでの内容は、初心者のユーザでも先のページを何度も参照することなく、

**Comment by smatsudajp** [comment]
おっと、すみません。今夜にでも修正してPRを出します。

**Comment by smatsudajp** [comment]
PR#469で対応

**Comment by noborus** [comment]
対応ありがとうございました
