### ISSUE TITLE
matchの訳語

### ISSUE THREAD

**Issue by smatsudajp** [pgsql-jp/jpug-doc#480]
## 背景

現状で、matchの訳語として「一致」と「マッチ」が使われているが、使い分けられているわけではなく、大半の箇所では「一致」と訳されている。
## 問題点

2つのデータや文字列の内容が同じである場合は「一致」で良いが、ワイルドカードなどを利用したパターンマッチの場合にも「一致」と訳すのは違和感がある。しかし、現状ではパターンマッチであっても「一致」としているのが大半である。
## 解決方法

文字通り一致している場合、あるいは一致を求められる場合は、現状通り「一致」と訳すが、パターンとの適合検査の場合は「マッチ」と訳す。例えば、
x IN ('ABC', 'DEF')
は、「xがリスト内の要素のどれかに『一致』する」と表現するが、
x LIKE 'AB_'
は、「xが指定のパターンに『マッチ』する」と表現する（『一致する』とはしない）
## 注意点

一括置換できないので、文脈を理解した上で訳し分ける必要がある。どちらかわからない場合は、恐らく『マッチ』に倒しても良い。
現状のものはボランティアベースで逐次修正、今後の追加や差分については、この規則に従って訳す、ということでどうか。

**Comment by KenichiroTanaka** [comment]
上記の方針で問題無いと思います。

特に反対がなければ
[JPUG DOCの翻訳活動のTips](https://github.com/pgsql-jp/jpug-doc/wiki/JPUG-DOCの翻訳活動のTips)
へ記載しておきます。

**Comment by KenichiroTanaka** [comment]
https://github.com/pgsql-jp/jpug-doc/wiki/JPUG-DOCの翻訳活動のTips#matchの訳語について

wikiへ記載しました。

**Comment by smatsudajp** [comment]
他にも「条件にmatchする」という使われ方があることに気付きました。
これは「適合」で良いかと思います。

**Comment by harukat** [comment]
(6/15 翻訳者会議)
本件はケースバイケースの対処とし、統一指針作成は見送るものとなった
