### ISSUE TITLE
巨大なSGMLファイルの取扱い

### ISSUE THREAD

**Issue by smatsudajp** [pgsql-jp/jpug-doc#517]
## 問題点
[jpug-doc:5073]から始まるスレッド。
GitHubの制限事項のため、レビュー時に不便なケースがある。
(a) diffの行数が多い(1500行以上?)と、diffが全く表示されない。
(b) 元のSGMLファイルのサイズが大きい(1MB以上?)と、diffが表示されても、通常はdiffの5-10行程度前にある原文が表示されない。
https://help.github.com/articles/what-are-the-limits-for-viewing-content-and-diffs-in-my-repository/

## 背景
(a)は9.5.0のrelease-9.5.sgmlおよびfunc.sgmlの翻訳時に発生。
(b)はfunc.sgmlで発生。
今のところ、他のファイルでの発生は確認されていない。

## 解決方法
(a)については、PRでのdiffのサイズを小さくする。特に問題になりそうなのは、メジャーリリースのリリースノートだが、例えば、セクション毎に別々に翻訳してPRを作成して回避する、ということをリリースノートの翻訳担当者が意識すれば良い。
(b)はGitHubを使う限り、ファイルを分割するしか回避策がなさそうだが、分割した場合、英文側の変更への追随の方法が課題となる。当面は、func.sgmlについてのみ、分割できれば良い。
作業の手間などを検討の上、なるべく簡単な解決策を見出したい。

## 注意点
英文側が変更された場合、メジャーリリース、マイナーリリースを問わず、
(1) 英文側のdiffを翻訳済ファイルにマージ
(2) 変更があった部分について翻訳
というのが基本手順となっているが、ファイルを分割した場合、(1)が単純にはできなくなることを、どのようにして解決するか、ということに注意。

**Comment by smatsudajp** [comment]
制限が変更されたのか、func.sgmlに関して(b)の問題が発生しなくなったので、クローズします。

**Comment by smatsudajp** [comment]
発生しなくなったわけではなく、発生しないこともある、という程度のようで、引き続き、問題ではあるので、リオープンします。

**Comment by tatsuo-ishii** [comment]
PR#521で、対応方法とその実装を提案しました。
func.sgmlをスクリプトでファイルを自動分割する方式です。運用としては、
1) func.sgmlを修正
2) スクリプトを起動してfunc.sgnlからfunc[0-4].sgmlを生成する
3) commit/pushしてPRを作成
4) func[0-4].sgmlに対してレビューを受ける
4) 修正箇所があれば1に戻って、func.sgmlの該当箇所を修正
という流れになります。英文への追随は分割前のfunc.sgmlに対して今まで同様に行えます。
2でスクリプトを起動しなければならないのが手間ではありますが。

**Comment by tatsuo-ishii** [comment]
PR#521をマージしました。

**Comment by tatsuo-ishii** [comment]
この件に関して特に追加の懸念事項はなさそうなので、クローズします。
