### ISSUE TITLE
HTMLの索引ページにA〜Z(頭文字）のリンクが無くなってしまった

### ISSUE THREAD

**Issue by noborus** [pgsql-jp/jpug-doc#541]
## 問題点

前にあった索引の上部に
Symbols | A | B | C | D .....
のように飛べるリンクが無くなっている。
https://pgsql-jp.github.io/jpug-doc/9.5.1/html/bookindex.html
## 背景

xhtml版でDocBookのスタイルシート(xsl)変更により無くなってしまった。
## 解決方法

リンクを復活させる。

**Comment by smatsudajp** [comment]
勝手ながら、重要度を「中」にしました。
Ctrl+Fという回避策はあるかもしれませんが、今まであったものが、なくなったので。
