### ISSUE TITLE
booleanの訳語

### ISSUE THREAD

**Issue by smatsudajp** [pgsql-jp/jpug-doc#551]
## 問題点

対訳リストで"boolean expression", "boolean value", "boolean"の訳語はそれぞれ「ブール式」「ブール値」「ブーリアン」となっているが、実際にそのように訳されている箇所は少数で、大半の箇所は「論理式」「論理値」などと訳されている。
どちらかに統一するべき。
## 背景

[jpug-doc: 5088]で報告。
三谷さんから「booleanは開発現場でブーリアンと表現する事が多いように思いますが、如何でしょうか。
個人的にはブーリアンの方が馴染みがあります。」という意見もあった。
## 解決方法

好みは人それぞれだろうが、「論理xx」に統一するのが適切と考える。
変数をboolean型で宣言する場合は、「ブーリアン」と呼ぶ場合もあるが、会話の場合がメインであろう。
データベースのマニュアルでboolean expressionなどの用語が使われるのは、ほとんどは"WHERE col1 = 'ABC'"のような表現であり、これを「ブール式」「ブール値」などと訳すのは良くないと考える。
## 注意点

例えば"boolean algebra"は「ブール代数」のまま残すべき。他に「ブール」「ブーリアン」としたい場合があるか？

**Comment by harukat** [comment]
（6/15 翻訳者会議）
引き続き「論理～」に寄せる方針で。
