### ISSUE TITLE
サマリ？サマリー？要約？

### ISSUE THREAD

**Issue by koizumistr** [pgsql-jp/jpug-doc#562]
## 問題点
BRINでsummary ○○という言葉がいくつか出てきますが、以下のようにsummaryの訳がばらばらです。

- summary info	要約情報
- summary data	サマリデータ
- summary index tuple	サマリーインデックスタプル
- summary information	サマリー情報
- summary values	要約値
- summary data	要約データ

サマリ、サマリー、要約があるようです。

また石井さんによると([jpug-doc: 5098] Re: BRINでのsummary)、動詞のsummarizeについても

- 「サマリ済み」
- 「サマリーされません」
- 要約されていない(func.sgml内)

といろいろあるようです。

## 背景
xindex.sgml の翻訳のために、brin.sgmlを参照して気付きました。

## 解決方法
個人的には、

- ブラウザー、フォルダーの時代なのでサマリは却下
- サマリーと言われても要約と言われても、どちらも同程度に私にとっては分からない

ということで、「要約」としたいところです。実際、xindex.sgmlではそうしています。

## 注意点

DB業界では、ここは「サマリー」だよね、というのが有るかもしれません。
ITmediaにも「サマリデータ」http://www.itmedia.co.jp/im/articles/0308/26/news009.html という言葉が載っていますし。（ただし、これは階層が全く違うだろと言われればそうかなとも。）

**Comment by smatsudajp** [comment]
基本的に同意見です。
個人的には、「サマリー」と言われると、頭の中で、「要約」という日本語に置き換えてから、「何をどうまとめたものなのだろう」という推定・推測を始めるので、特定の決まった形式のものを「サマリー」と呼ぶ習慣があるのでなければ、「要約」とするのが良いと考えます。
一方で、「サマリー」という用語自体が日本語に十分に浸透していて、「要約ならわかるが、サマリーだと何のことかわからない」と思う人も少数だと思うので、多数決の結果が「サマリー」なら、それも許容範囲かな、敢えて「サマリー」派の人を説得しようとは思わない、というところです。
なお、動詞のsummarizeについて、「サマリーする」というサ変動詞は、許容限度を超えている（強く反対したい）と考えていて、「要約する」「サマリーを作成する」などと訳すべきと思います。「サマリー済み」は、なぜか「サマリーする」に比べると抵抗感は小さいですが、やはりNGと考えます。

**Comment by KenichiroTanaka** [comment]
感覚的にはサマリーで良いと思いますが、松田さん同様、多数決の結果が「要約」ならばそれも許容範囲であえて「要約派」の人を説得するほど支持していない感じです。

ただ、松田さんから提起いただいているsummarizeの訳を「サマリーする」と訳さないようにするためにも「要約」側に寄せてしまった方が良い気がしています。

サマリーの方が良い、という意見はありますでしょうか。

**Comment by KenichiroTanaka** [comment]
時間も経過していますので、特に反対意見が無いようでしたら"要約"で進めさせて
頂きたいと思います。

**Comment by KenichiroTanaka** [comment]
特に反対意見も無いようですので一旦クローズします。
