### ISSUE TITLE
dimensionの訳語について

### ISSUE THREAD

**Issue by KenichiroTanaka** [pgsql-jp/jpug-doc#584]
## 問題点

dimensionの翻訳表記に揺れがあるため、翻訳方針を定める必要がある。
## 背景

https://github.com/pgsql-jp/jpug-doc/pull/577
## 解決方法

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
・dimensionの翻訳は、基本は”次元”とする。
・ただしdimensionが「多次元配列のN次元目」というときのNを指している場合を「次数」と訳す

例）
returns the number of dimensions of the array
→配列の次元数を返す

　　 関数の実際の挙動）
　　　array_ndims(ARRAY[[1,2,3], [4,5,6]])
　結果：2

returns the length of the requested array dimension
→指定次数での配列の長さを返す

　　関数の実際の挙動）
array_length(array[1,2,3], 1)
結果：3

**Comment by harukat** [comment]
（6/15 翻訳者会議）
本件は配列に対する一部の関数限定の問題と考えられる。
同様の関数については本方針で対応し、新たに dimension等が登場したときには別途判断する。
