### ISSUE TITLE
9.5文書の「44.1. インタフェース関数」にSPIの一覧が表示されていない

### ISSUE THREAD

**Issue by nuko-yokohama** [pgsql-jp/jpug-doc#586]
## 問題点

* 本来、9.5.2文書の「44.1 インタフェース関数」には、SPIの関数名と概要のリストが記載されているが、現状の日本語9.5.2文書では、そのリストが全く表示されていない。
* 英語版の該当ページ
 http://www.postgresql.org/docs/9.5/interactive/spi-interface.html
* 9.4文書には記載されている。
 http://www.postgresql.jp/document/9.4/html/spi-interface.html

なお、類似事象だと思われるが、「第44章 サーバプログラミングインタフェース」に表示されるTOCにも、このSPIの関数名が本来は表示されるはずである。

**Comment by tatsuo-ishii** [comment]
"make html"で生成したバージョンでは問題が起きていないので、"make xslthtml"でhtmlを生成した時の問題なのかもしれません(以下は、"make html"で生成したバージョン。参考までに)
http://tatsuo-ishii.github.io/doc-ja/9.5.2-html/spi-interface.html

**Comment by KenichiroTanaka** [comment]
報告ありがとうございます。
9.5.1でも発生しているので9.5.2固有の問題（今回は私がbuildしたので疑いました）でも
無さそうです。

まだ原因は見えていません。。もう少し調べます。

**Comment by noborus** [comment]
#592 で修正出来たと思います。セクション内の目次のカスタマイズが必要かと思いましたが、
結果的には generate.section.toc.level の変更のみになってます。

**Comment by noborus** [comment]
逆に、sect1/sect2の構成で、前には出ていなかった目次が出るようになってしまってますね。これを元と同じにするには、ひと工夫要りそうです。
https://pgsql-jp.github.io/jpug-doc/9.5.2/html/sql-expressions.html
https://pgsql-jp.github.io/jpug-doc/9.5.3/html/sql-expressions.html

**Comment by smatsudajp** [comment]
今まではなかった(本家にもない)目次が出てしまうのはマイナーな問題かと思います。
それより、44.1など44章の各節で目次がない問題は解決されていますが、44章に目次がない問題は解決できていないようです。
https://pgsql-jp.github.io/jpug-doc/9.5.3/html/spi.html
http://www.postgresql.org/docs/9.5/static/spi.html

**Comment by noborus** [comment]
#592 に続けて修正してみました。

github.ioの方に修正した版で作成して更新しました。
https://pgsql-jp.github.io/jpug-doc/9.5.3/html/spi.html

chapterの目次は出しつつ、sect1の目次はrefentryのみにしてます。

**Comment by smatsudajp** [comment]
思いつく範囲で確認した限りは、良い感じですね。

**Comment by noborus** [comment]
マージされたのでクローズします
