### ISSUE TITLE
subdirectoryの訳

### ISSUE THREAD

**Issue by koizumistr** [pgsql-jp/jpug-doc#588]
## 問題点

subdirectoryの訳として、「副ディレクトリ」としているところがあります。
グーグルで検索すると
「サブディレクトリ」約 224,000 件
である一方、
「副ディレクトリ」約 69 件 
で、さらにその最初の三つはPostgreSQLの日本語マニュアルのものです。
また
 grep "サブディレクトリ" doc/src/sgml/*.sgml doc/src/sgml/ref/*.sgml | wc
      70     201   14113
 grep "副ディレクトリ" doc/src/sgml/*.sgml doc/src/sgml/ref/*.sgml | wc
       5      13    1032
ということで、自分自身の中でも少数派です。

## 背景

9.5.3対応のときに見つけました。

## 解決方法

「副ディレクトリ」を「サブディレクトリ」に一括変換。

## 注意点

意図的に「副ディレクトリ」としている訳ではないと思いますが、何か意図があるならお知らせ下さい。

**Comment by KenichiroTanaka** [comment]
サブディレクトリへの一括変換に１票です。

**Comment by koizumistr** [comment]
#610 で対応中です。

**Comment by koizumistr** [comment]
マージされたのでクローズします。
