### ISSUE TITLE
CREATE TABLESPACEの説明文

### ISSUE THREAD

**Issue by nuko-yokohama** [pgsql-jp/jpug-doc#603]
## 問題点

SQLコマンドのCREATE TABLESPACE
http://www.postgresql.jp/document/9.5/html/sql-createtablespace.html
の2番目の段落

_A tablespace allows superusers to define an alternative location on the file system where the data files containing database objects (such as tables and indexes) can reside._

の翻訳が

_テーブル空間を使用すると、データベースオブジェクト（テーブルやインデックスなど）が入ったデータファイルを格納する、ファイルシステム上の別の場所をスーパーユーザができます。_

となってますが、

テーブル空間はデータベース・オブジェクト（テーブルやインデックスなど）を含むデータファイルが格納できるファイルシステム上の別の場所をスーパーユーザによって定義することができます。

くらいの意味ではないでしょうか。

**Comment by smatsudajp** [comment]
最大の問題点は、なぜか"define"に相当する語が訳文にないこと、それに比べれば軽微ですがもう一つの問題は"can reside"の"can"が訳出されていないこと、ですね。
訳抜けを別にすれば、現状の訳文はあまり悪くないので「テーブル空間を使用すると、データベースオブジェクト(テーブルやインデックスなど)が入ったデータファイルを格納できる、ファイルシステム上の別の場所をスーパーユーザが定義できます」とすれば良いかと思いますが、いかがでしょうか。
別の訳し方としては、『スーパーユーザ』を文頭に持ってきて、「スーパーユーザはテーブル空間を使用することで、データベースオブジェクト(テーブルやインデックスなど)が入ったデータファイルを格納できる、ファイルシステム上の別の場所を定義できます」とするのも良いですかね。こちらの方がわかりやすいような気がします。
現在、9.5.3の翻訳作業中なので、そのリリースまでには修正したいですね。

**Comment by nuko-yokohama** [comment]
回答ありがとうございます。
別訳案のほうが私も良さそうに思います。

個人的にはこの箇所、原文からわかりにくい気がする・・・
* テーブル空間自体の説明
* テーブル空間はスーパユーザでないと定義できない

という2つの話を1つの文にしているから何でしょうかね。

**Comment by smatsudajp** [comment]
PRがマージされたのでクローズします。
ご報告、ありがとうございました。
