### ISSUE TITLE
DROP CONVERSIONとDROP TRANSFORMの概要

### ISSUE THREAD

**Issue by nuko-yokohama** [pgsql-jp/jpug-doc#607]
## 問題点

SQLコマンドのDROP CONVERSIONの概要とDROP TRANSFORMの概要の日本語訳が、両方とも
_変換を削除する_
になっているのが気になります。全く別の機能なので。

例えばDROP CONVERSIONだけでも、「符化方式変換を削除する」みたいに補足することはできるのでしょうか。
原文では、それぞれ
_remove a conversion
remove a transform_
なので、今のようになっているのは理解していますが・・・

**Comment by smatsudajp** [comment]
CREATE CONVERSIONの説明が「新しい符号化方式変換を定義する」なので、DROP CONVERSIONもそれに合わせて訳を修正するのが正しいと思います。
9.5の新機能のTRANSFORMについては、どういう訳語が良いか議論した結果、変換に落ち着いたという経緯があります。

**Comment by smatsudajp** [comment]
確認しました。create conversionでは原文が"encoding conversion"となっているので、「符号化方式変換」と訳していますが、drop conversionでは、原文がconversionとしかなっていないため、単純に「変換」と訳しているのですね。しかも概要だけでなく、説明の中で多数、出てきますね。
説明の一番最初にconversionが出てきた部分について「符号化方式変換(以下、単に「変換」と記す)」という形式にした方が良いかもしれません。一度も"encoding conversion"という表現が出てこないので、そういう意味では対処法は単純です。
create conversionの場合は、最初の方は"encoding conversion"などと記述していますが、途中から原文も単に"conversion"になるので、訳語もそれに合わせて単なる「変換」に変わっています。これはこれでどうするのが良いか、考える必要があるかもしれません。

**Comment by smatsudajp** [comment]
PRがマージされたのでクローズします。
ご報告、ありがとうございました。
