### ISSUE TITLE
「9.26.9. 汎用ファイルアクセス関数」がスーパーユーザのみ使用可能という記述が落ちている

### ISSUE THREAD

**Issue by nuko-yokohama** [pgsql-jp/jpug-doc#617]
## 問題点
「9.26.9. 汎用ファイルアクセス関数」がスーパーユーザのみ使用可能という記述が落ちている。
http://www.postgresql.jp/document/9.5/html/functions-admin.html#functions-admin-genfile

「表9.76 汎用ファイルアクセス関数」直前の文章の末尾は原文だと
https://www.postgresql.org/docs/9.5/static/functions-admin.html#FUNCTIONS-ADMIN-GENFILE
”Use of these functions is restricted to superusers.”
となっているが、日本語文書ではこの一文が欠落している。

このため、汎用ファイルアクセス関数が、一般権限のユーザでも使用可能と誤解される。

**Comment by smatsudajp** [comment]
報告ありがとうございます。func.sgmlですね。
しばらく前に、全面的に翻訳を見直したの部分なのですが、そのときにも見落としていたようです。

**Comment by smatsudajp** [comment]
#618 でPRを作成しました。

**Comment by KenichiroTanaka** [comment]
報告および修正の対応ありがとうございます。
PRをマージしました。

**Comment by noborus** [comment]
マージされているのでCLOSEします
