### ISSUE TITLE
「25.2.8.1. 基本設定」の訳

### ISSUE THREAD

**Issue by nori-shinoda** [pgsql-jp/jpug-doc#619]
## 問題点
25.2.8.1. 基本設定

「synchronous_replicationは個々のユーザによって設定することができます。」の部分、
synchronous_replicationはsynchronous_commitの間違いだと思います。

英文は synchronous_commit can be set by individual users, です。

**Comment by smatsudajp** [comment]
確認しました。high-availability.sgml ですね。

**Comment by noborus** [comment]
マージされているのでCLOSEします
