### ISSUE TITLE
「スーパーユーザ」表記と「スーパユーザ」表記の混在

### ISSUE THREAD

**Issue by nuko-yokohama** [pgsql-jp/jpug-doc#626]
## 問題点
- 9.26. システム管理関数 (http://www.postgresql.jp/document/9.5/html/functions-admin.html) のページ内で、「スーパーユーザ」と「スーパユーザ」の表記が混在している。
- 2箇所だけ「スーパユーザ」表記の箇所がある。他の11箇所は「スーパーユーザ」表記になっている。
- 他のページについては未調査。
## 背景
- スーパーユーザ権限でのみ実行可能な関数の調査中に発見した(文書内を「スーパーユーザ」で検索したところ、引っかかるべき関数で引っかからなかったので気づいた)。

**Comment by noborus** [comment]
#794 #795 で全置き換えされました。

**Comment by noborus** [comment]
9.6.0でリリースされました。 http://www.postgresql.jp/document/9.6/html/
