### ISSUE TITLE
autovacuum_analyze_scale_factorの誤訳

### ISSUE THREAD

**Issue by tom-sato** [pgsql-jp/jpug-doc#630]
## 問題点

「18.10. 自動Vacuum作業」の「[autovacuum_analyze_scale_factor](http://www.postgresql.jp/document/9.5/html/runtime-config-autovacuum.html#guc-autovacuum-analyze-scale-factor)」の説明が以下のようになっていますが、

> ANALYZEをトリガするか否かを決定する場合、autovacuum_vacuum_thresholdに追加するテーブル容量の小部分を指定します。

autovacuum_vacuum_thresholdでなくautovacuum_analyze_thresholdが正しいです。原文でもautovacuum_analyze_thresholdになっています。

自動バキュームが本体に組み込まれた8.1以降、すべてのバージョンで誤っています。

あと、「fraction」の訳ですが、autovacuum_analyze_scale_factorでは「小部分」、autovacuum_vacuum_scale_factorでは「断片」となっていますが、「割合」と訳したほうが適切だと思います。

**Comment by tatsuo-ishii** [comment]
ありがとうございます。Pull requestを出しておきました。

https://github.com/pgsql-jp/jpug-doc/pull/632

**Comment by KenichiroTanaka** [comment]
ありがとうございます。
#632はマージしました。

>autovacuum_vacuum_scale_factorでは「断片」となっていますが
こちらの部分を追って対応します。

**Comment by tatsuo-ishii** [comment]
autovacuum_vacuum_scale_factor、autovacuum_analyze_scale_factor についても、コミット 3e06bebe2 (Tatsuo Ishii       2016-11-21 11:48:27 )で修正されていました。課題は解消されたのでクローズします。
