### ISSUE TITLE
PostgreSQL 9.6.0がリリースされます

### ISSUE THREAD

**Issue by KenichiroTanaka** [pgsql-jp/jpug-doc#654]
## 問題点

9.6がいよいよリリースされます。

**Comment by KenichiroTanaka** [comment]
変更量は以下の通り

$ git diff --stat REL9_5_4 REL9_6_RC1 doc/src/sgml
warning: refname 'REL9_6_RC1' is ambiguous.
 doc/src/sgml/adminpack.sgml                     |  158 +++-
 doc/src/sgml/array.sgml                         |   27 +
 doc/src/sgml/auto-explain.sgml                  |   17 +
 doc/src/sgml/backup.sgml                        |  184 +++-
 doc/src/sgml/bgworker.sgml                      |  110 ++-
 doc/src/sgml/bloom.sgml                         |  268 ++++++
 doc/src/sgml/brin.sgml                          |   38 +-
 doc/src/sgml/catalogs.sgml                      |  524 ++++++-----
 doc/src/sgml/client-auth.sgml                   |  169 +++-
 doc/src/sgml/config.sgml                        |  657 ++++++++++++--
 doc/src/sgml/contrib.sgml                       |    2 +
 doc/src/sgml/cube.sgml                          |  328 +++++--
 doc/src/sgml/custom-scan.sgml                   |   68 +-
 doc/src/sgml/datatype.sgml                      |  119 ++-
 doc/src/sgml/dblink.sgml                        |   18 +-
 doc/src/sgml/ddl.sgml                           |   35 +-
 doc/src/sgml/docguide.sgml                      |    9 +
 doc/src/sgml/ecpg.sgml                          |   10 +-
 doc/src/sgml/extend.sgml                        |   46 +-
 doc/src/sgml/external-projects.sgml             |   26 +-
 doc/src/sgml/fdwhandler.sgml                    |  346 +++++++-
 doc/src/sgml/filelist.sgml                      |    4 +
 doc/src/sgml/func.sgml                          | 1512 +++++++++++++++++++++++++++----
 doc/src/sgml/generate-errcodes-table.pl         |    2 +-
 doc/src/sgml/generic-wal.sgml                   |  160 ++++
 doc/src/sgml/gin.sgml                           |   52 +-
 doc/src/sgml/gist.sgml                          |   75 +-
 doc/src/sgml/high-availability.sgml             |   99 ++-
 doc/src/sgml/hstore.sgml                        |    6 +-
 doc/src/sgml/indexam.sgml                       |  242 +++--
 doc/src/sgml/indices.sgml                       |  201 ++++-
 doc/src/sgml/install-windows.sgml               |   15 +-
 doc/src/sgml/installation.sgml                  |   32 +-
 doc/src/sgml/intarray.sgml                      |   11 +-
 doc/src/sgml/keywords.sgml                      |   16 +-
 doc/src/sgml/libpq.sgml                         |  119 ++-
 doc/src/sgml/lobj.sgml                          |    2 +-
 doc/src/sgml/logicaldecoding.sgml               |   48 +-
 doc/src/sgml/ltree.sgml                         |    2 +-
 doc/src/sgml/maintenance.sgml                   |   99 ++-
 doc/src/sgml/manage-ag.sgml                     |    6 +-
 doc/src/sgml/monitoring.sgml                    | 1016 +++++++++++++++++----
 doc/src/sgml/mvcc.sgml                          |   42 +-
 doc/src/sgml/nls.sgml                           |    2 +-
 doc/src/sgml/pageinspect.sgml                   |   57 +-
 doc/src/sgml/pgcrypto.sgml                      |   17 +-
 doc/src/sgml/pgstandby.sgml                     |    2 +-
 doc/src/sgml/pgstattuple.sgml                   |    8 +-
 doc/src/sgml/pgtrgm.sgml                        |  129 ++-
 doc/src/sgml/pgvisibility.sgml                  |  154 ++++
 doc/src/sgml/plpgsql.sgml                       |   76 +-
 doc/src/sgml/plpython.sgml                      |   75 +-
 doc/src/sgml/pltcl.sgml                         |   76 +-
 doc/src/sgml/postgres-fdw.sgml                  |   78 +-
 doc/src/sgml/postgres.sgml                      |    1 +
 doc/src/sgml/protocol.sgml                      |  109 ++-
 doc/src/sgml/queries.sgml                       |   13 +-
 doc/src/sgml/ref/allfiles.sgml                  |    2 +
 doc/src/sgml/ref/alter_domain.sgml              |    4 +-
 doc/src/sgml/ref/alter_foreign_table.sgml       |    4 +-
 doc/src/sgml/ref/alter_function.sgml            |   37 +-
 doc/src/sgml/ref/alter_index.sgml               |   20 +
 doc/src/sgml/ref/alter_materialized_view.sgml   |   17 +
 doc/src/sgml/ref/alter_operator.sgml            |   34 +-
 doc/src/sgml/ref/alter_role.sgml                |    3 -
 doc/src/sgml/ref/alter_system.sgml              |   10 +-
 doc/src/sgml/ref/alter_table.sgml               |   16 +-
 doc/src/sgml/ref/alter_trigger.sgml             |   20 +-
 doc/src/sgml/ref/alter_user.sgml                |    1 -
 doc/src/sgml/ref/alter_user_mapping.sgml        |    2 +-
 doc/src/sgml/ref/comment.sgml                   |    4 +
 doc/src/sgml/ref/copy.sgml                      |   15 +-
 doc/src/sgml/ref/create_access_method.sgml      |  119 +++
 doc/src/sgml/ref/create_aggregate.sgml          |  118 ++-
 doc/src/sgml/ref/create_extension.sgml          |   42 +
 doc/src/sgml/ref/create_function.sgml           |   61 +-
 doc/src/sgml/ref/create_group.sgml              |    1 -
 doc/src/sgml/ref/create_index.sgml              |    4 +-
 doc/src/sgml/ref/create_opclass.sgml            |    2 +-
 doc/src/sgml/ref/create_role.sgml               |   14 -
 doc/src/sgml/ref/create_schema.sgml             |    2 +-
 doc/src/sgml/ref/create_sequence.sgml           |    2 +-
 doc/src/sgml/ref/create_table.sgml              |   13 +
 doc/src/sgml/ref/create_tablespace.sgml         |   17 +-
 doc/src/sgml/ref/create_type.sgml               |    2 +-
 doc/src/sgml/ref/create_user.sgml               |    1 -
 doc/src/sgml/ref/create_user_mapping.sgml       |    2 +-
 doc/src/sgml/ref/create_view.sgml               |    7 +-
 doc/src/sgml/ref/drop_access_method.sgml        |  111 +++
 doc/src/sgml/ref/drop_aggregate.sgml            |    5 +-
 doc/src/sgml/ref/drop_collation.sgml            |    4 +-
 doc/src/sgml/ref/drop_domain.sgml               |    4 +-
 doc/src/sgml/ref/drop_event_trigger.sgml        |    4 +-
 doc/src/sgml/ref/drop_extension.sgml            |    4 +-
 doc/src/sgml/ref/drop_foreign_data_wrapper.sgml |    6 +-
 doc/src/sgml/ref/drop_foreign_table.sgml        |    3 +-
 doc/src/sgml/ref/drop_function.sgml             |    4 +-
 doc/src/sgml/ref/drop_index.sgml                |    4 +-
 doc/src/sgml/ref/drop_language.sgml             |    4 +-
 doc/src/sgml/ref/drop_materialized_view.sgml    |    4 +-
 doc/src/sgml/ref/drop_opclass.sgml              |    4 +-
 doc/src/sgml/ref/drop_operator.sgml             |    4 +-
 doc/src/sgml/ref/drop_opfamily.sgml             |    4 +-
 doc/src/sgml/ref/drop_owned.sgml                |    4 +-
 doc/src/sgml/ref/drop_policy.sgml               |   14 +-
 doc/src/sgml/ref/drop_rule.sgml                 |    4 +-
 doc/src/sgml/ref/drop_schema.sgml               |   15 +-
 doc/src/sgml/ref/drop_sequence.sgml             |    4 +-
 doc/src/sgml/ref/drop_server.sgml               |    4 +-
 doc/src/sgml/ref/drop_table.sgml                |    4 +-
 doc/src/sgml/ref/drop_transform.sgml            |    6 +-
 doc/src/sgml/ref/drop_trigger.sgml              |    4 +-
 doc/src/sgml/ref/drop_tsconfig.sgml             |    4 +-
 doc/src/sgml/ref/drop_tsdictionary.sgml         |    4 +-
 doc/src/sgml/ref/drop_tsparser.sgml             |    4 +-
 doc/src/sgml/ref/drop_tstemplate.sgml           |    4 +-
 doc/src/sgml/ref/drop_type.sgml                 |    4 +-
 doc/src/sgml/ref/drop_user_mapping.sgml         |    2 +-
 doc/src/sgml/ref/drop_view.sgml                 |    4 +-
 doc/src/sgml/ref/grant.sgml                     |   14 +-
 doc/src/sgml/ref/notify.sgml                    |    7 +-
 doc/src/sgml/ref/pg_basebackup.sgml             |   27 +-
 doc/src/sgml/ref/pg_dump.sgml                   |   28 +-
 doc/src/sgml/ref/pg_resetxlog.sgml              |  222 +++--
 doc/src/sgml/ref/pg_restore.sgml                |   49 +-
 doc/src/sgml/ref/pg_rewind.sgml                 |   96 +-
 doc/src/sgml/ref/pg_xlogdump.sgml               |    2 +-
 doc/src/sgml/ref/pgarchivecleanup.sgml          |    2 +-
 doc/src/sgml/ref/pgbench.sgml                   |  487 ++++++----
 doc/src/sgml/ref/pgtesttiming.sgml              |   32 +-
 doc/src/sgml/ref/pgupgrade.sgml                 |    4 +-
 doc/src/sgml/ref/postgres-ref.sgml              |   45 +-
 doc/src/sgml/ref/prepare.sgml                   |   48 +-
 doc/src/sgml/ref/psql-ref.sgml                  |  451 ++++++++--
 doc/src/sgml/ref/revoke.sgml                    |    2 +-
 doc/src/sgml/ref/select.sgml                    |   34 +-
 doc/src/sgml/ref/set_role.sgml                  |    4 +-
 doc/src/sgml/ref/set_session_auth.sgml          |    2 +-
 doc/src/sgml/ref/vacuum.sgml                    |   21 +-
 doc/src/sgml/ref/values.sgml                    |    3 +-
 doc/src/sgml/reference.sgml                     |    2 +
 doc/src/sgml/regress.sgml                       |   12 +-
 doc/src/sgml/release-9.6.sgml                   | 3708 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 doc/src/sgml/release.sgml                       |    1 +
 doc/src/sgml/rules.sgml                         |   52 +-
 doc/src/sgml/runtime.sgml                       |  104 ++-
 doc/src/sgml/seg.sgml                           |    6 +-
 doc/src/sgml/sepgsql.sgml                       |    2 +-
 doc/src/sgml/sources.sgml                       |  116 ++-
 doc/src/sgml/spgist.sgml                        |   74 +-
 doc/src/sgml/spi.sgml                           |   17 +-
 doc/src/sgml/sslinfo.sgml                       |   21 +-
 doc/src/sgml/start.sgml                         |   11 +-
 doc/src/sgml/storage.sgml                       |   21 +-
 doc/src/sgml/stylesheet-man.xsl                 |    7 +
 doc/src/sgml/stylesheet.css                     |    2 +
 doc/src/sgml/syntax.sgml                        |   10 +-
 doc/src/sgml/tablefunc.sgml                     |    8 +
 doc/src/sgml/textsearch.sgml                    |  384 +++++++-
 doc/src/sgml/trigger.sgml                       |    6 +-
 doc/src/sgml/unaccent.sgml                      |    7 +-
 doc/src/sgml/user-manag.sgml                    |   53 +-
 doc/src/sgml/wal.sgml                           |   11 +
 doc/src/sgml/xaggr.sgml                         |  100 ++-
 doc/src/sgml/xfunc.sgml                         |   33 +-
 doc/src/sgml/xindex.sgml                        |    2 +-
 doc/src/sgml/xml2.sgml                          |    2 +-
 doc/src/sgml/xplang.sgml                        |    2 +-

**Comment by KenichiroTanaka** [comment]
9.6のリリースを確認しました。
マージします。

**Comment by noborus** [comment]
完了したのでクローズします。
