### ISSUE TITLE
nested loop(join)の訳

### ISSUE THREAD

**Issue by noborus** [pgsql-jp/jpug-doc#776]
## 問題点

nested loop (nested-loop)の訳が統一されていない。
* 入れ子ループ
* 入れ子状ループ
* ネストループ
* ネステッドループ

## 背景

explainで「Nested Loop」が出力されるので、同じ用語と認識されることが望ましい。
入れ子ループ、入れ子状ループは、nested loopのことを指していると認識しづらい。

## 解決方法

ネストループかネステッドループに統一したい。

## 注意点

「Nested Loop」と表記されている場合は、Explainの表記を使用しているため、訳さず「Nested Loop」のままにする。

**Comment by smatsudajp** [comment]
取り敢えず、ネストループに1票、入れておきます。

**Comment by KenichiroTanaka** [comment]
好みの問題ということであれば「ネステッドループ」に１票です。

**Comment by noborus** [comment]
このままだと決まらなそうなので、試しに投票的にしてみましょうか？松田さんと田中さんに :+1: で入れてもらうよう呼びかけてみます

**Comment by noborus** [comment]
ご意見ありがとうございました。
ネステッドループの方が多数だったので、ネステッドループに統一しようと思います。
