### ISSUE TITLE
原文中のハイフンの処理

### ISSUE THREAD

**Issue by smatsudajp** [pgsql-jp/jpug-doc#788]
## 問題点

原文中の－－を単純にコメントアウトするとコンパイルエラーになるため、それらを「＆＃０４５；」で置換する必要があるが、一部のファイルでなぜか「＆＃０５５；」で置換されている。
ビルドされる日本語マニュアルには影響ないので重要度は低いが、新参者が同じ間違いを起こす、混乱する、という可能性がある。

## 背景

該当するファイルは以下。
isn.sgml
lobj.sgml
release-7.4.sgml
release-8.0.sgml
release-8.1.sgml
release-8.2.sgml
release-old.sgml
tablefunc.sgml
ref/clusterdb.sgml
ref/create_aggregate.sgml
ref/create_conversion.sgml
ref/createlang.sgml
ref/droplang.sgml
ref/fetch.sgml
ref/initdb.sgml
ref/insert.sgml
ref/lock.sgml
ref/pg_config-ref.sgml
ref/pg_ctl-ref.sgml
ref/pg_dump.sgml
ref/pg_dumpall.sgml
ref/unlisten.sgml
ref/update.sgml

## 解決方法

一括置換する。

## 注意点

なお、release-9.3.sgmlには「＆＃４５；」というのもあるが、１０進数で、３桁にする必然性はないので、これは修正しなくても良い。
８進数と誤解される可能性を考えると、むしろ「＆＃４５；」を推奨するという考え方もあるが、「０４５」の件数が非常に多いので、手間や効果を考えると、０４５のままで運用する方が良いだろう。

**Comment by koizumistr** [comment]
ちょっと違うのですがddl.sgmlに
＆＃０４５
（後の;がない）というのも見つけました。合わせて直してもらえると。

あと、045と45の扱いはそれでいいと思います。

**Comment by koizumistr** [comment]
＆＃０４５ をproblems.sgmlにも見つけました。

**Comment by smatsudajp** [comment]
既知の箇所はすべて修正したのでクローズします。
