### ISSUE TITLE
version 9.6.0 config-setting.html

### ISSUE THREAD

**Issue by smatsudajp** [pgsql-jp/jpug-doc#790]
## 問題点

19.1.2. 設定ファイルによるパラメータ操作
にかなり重大な誤訳を見つけました。
To embed a single quote in a parameter value, write either two quotes (preferred) or backslash-quote.
パラメータ値の中に単一引用符を埋め込む場合、二重引用符（推奨）もしくはバックスラッシュ-引用符で括ります。

## 背景

"two quotes"は「引用符を2つ」ですが「二重引用符」と誤訳されています。
また、文の終わりの「で括ります」も間違いで「を使います」です。

## 解決方法

後でPRを出します。
どなたか対応して下さるなら、それでも構いません。私がレビューしてマージします。
今、PRを出せる環境にいないので、取り急ぎ、Issueとしました。

## 注意点

9.6.0の翻訳がほとんど終わっていますが、リリース前に直したいですね。

**Comment by smatsudajp** [comment]
既存部分なので、過去のマニュアルにも同じ誤訳があります。

**Comment by tatsuo-ishii** [comment]
これ、私が翻訳した部分ですね。責任を取って私がPRを出すので、レビューよろしくお願いします。

**Comment by tatsuo-ishii** [comment]
どうも私が翻訳したところではなかったようですが、PRを出しました。よろしくお願いします。

**Comment by smatsudajp** [comment]
修正されたのでクローズします。
