### ISSUE TITLE
signalの訳語

### ISSUE THREAD

**Issue by smatsudajp** [pgsql-jp/jpug-doc#808]
## 問題点

SIGHUPなどのsignalの訳語として、大半の箇所では「シグナル」が使われているが、一部の箇所で「信号」と訳している。
技術用語なので「シグナル」とするべきだろう。

## 背景

config.sgmlやclient-auth.sgmlを読んでいて「SIGHUP信号」という記述が出てきてちょっとビックリした。
実際に「SIGHUP 信号」でググると、出てくるのは中国語のページばかり(変に納得)。

## 解決方法

単純に訳語を置換する。
grep -l 信号 ＊.sgml ref/＊.sgml
した結果は
client-auth.sgml
config.sgml
func.sgml
func4.sgml
ref/notify.sgml

**Comment by tatsuo-ishii** [comment]
「シグナル」はひどすぎですね:-) 一括置換に賛成です。

**Comment by smatsudajp** [comment]
修正がマージされたのでクローズします。
