### ISSUE TITLE
tzdata release 201xyの訳し方

### ISSUE THREAD

**Issue by koizumistr** [pgsql-jp/jpug-doc#814]
## 問題点
tzdata release 201xy
ですが、訳では
tzdata release 201xy
そのままのものと
tzdataリリース201xy
となっているものが混在しています。

## 背景
以前は「tzdataリリース201xy」だったが最近「tzdata release 201xy」とするようにしたらしいです。
が、統一してあった方が望ましいと考えられます。

## 解決方法
（このマニュアル内に限らず世間一般で）良く使われている方に合わせて、一挙に置換。

## 注意点
間違って無関係なrelease/リリースを置換しないこと

**Comment by noborus** [comment]
古いリリースノートが含まれなくなったので、最新では統一されているため、これはクローズします。
