### ISSUE TITLE
NO FORCE/FORCE ROW LEVEL SECURITYの原文が残っている

### ISSUE THREAD

**Issue by tom-sato** [pgsql-jp/jpug-doc#821]
## 問題点

[「ALTER TABLE](http://www.postgresql.jp/document/9.6/html/sql-altertable.html)」の「NO FORCE/FORCE ROW LEVEL SECURITY」の原文の説明が残っています。

**Comment by smatsudajp** [comment]
報告ありがとうございます。
確認の上、対応します。

**Comment by smatsudajp** [comment]
修正がマージされたでクローズします。
