### ISSUE TITLE
「64.3. 拡張性」の説明に原文が残っている

### ISSUE THREAD

**Issue by tom-sato** [pgsql-jp/jpug-doc#822]
## 問題点

「[64.3. 拡張性](http://www.postgresql.jp/document/9.6/html/brin-extensibility.html)」の説明の最後から2段落目に原文が残っています。

**Comment by KenichiroTanaka** [comment]
ご報告ありがとうございます。
コメントの付け損ねです。

修正しておきます。

**Comment by KenichiroTanaka** [comment]
https://github.com/pgsql-jp/jpug-doc/pull/824
にてPRを出しました。

**Comment by smatsudajp** [comment]
修正がマージされたでクローズします。
