### ISSUE TITLE
replica identityの訳がレプリカエンティティ(replica entity)になっている

### ISSUE THREAD

**Issue by tom-sato** [pgsql-jp/jpug-doc#823]
## 問題点

「[第47章 ロジカルデコーディング](http://www.postgresql.jp/document/9.6/html/logicaldecoding.html)」の最後から2段落目の最後の説明で原文の「replica identity」の訳が「レプリカエンティティ(replica entity)」になっています。

> UPDATEとDELETEによって古いバージョンの行へのアクセスが可能かどうかは、 レプリカエンティティ(replica entity)の設定によって決まります(REPLICA IDENTITY参照)。 

意図してそうしているわけではなさそうなので、単に「identity」を「entity」と取り違えているようです。

**Comment by smatsudajp** [comment]
logicaldecoding.sgmlの48行目ですね。

**Comment by KenichiroTanaka** [comment]
ご報告ありがとうございます。

取り急ぎ
https://github.com/pgsql-jp/jpug-doc/pull/827
にてPRを出しました。

**Comment by KenichiroTanaka** [comment]
2重にPRが出ていましたので827はクローズします。

**Comment by KenichiroTanaka** [comment]
https://github.com/pgsql-jp/jpug-doc/pull/826
がマージされたので本件クローズします。

ご報告ありがとうございました。
