### ISSUE TITLE
postgres コマンドオプション誤訳

### ISSUE THREAD

**Issue by yugo-n** [pgsql-jp/jpug-doc#910]
## 問題点

postgres コマンドの -W オプションが誤訳と思われます。
https://www.postgresql.jp/document/9.6/html/app-postgres.html

-W seconds

    新規サーバプロセスが起動するときに指定した秒数の遅延が発生します。 認証手続きはこの後で行われます。 サーバプロセスにデバッガを接続する時間を提供することが目的です。 

    A delay of this many seconds occurs when a new server process is started, after it conducts the authentication procedure. This is intended to give an opportunity to attach to the server process with a debugger.

「認証手続きはこの後で行われます。 」とありますが、-W は post_auth_delay に対応するもので、実際には認証手続きの後に遅延が発生します。

## 背景

（参考）
PostmasterMain() のオプション解析部のソースコードは以下のようになっています。
https://doxygen.postgresql.org/postmaster_8c_source.html

 case 'W':
    SetConfigOption("post_auth_delay", optarg, PGC_POSTMASTER, PGC_S_ARGV);
    break;

## 解決方法

以下のような感じでしょうか。

    新規サーバプロセスが起動するとき、認証手続きが行われた後に、指定した秒数の遅延が発生します。 サーバプロセスにデバッガを接続する時間を提供することが目的です。 

## 注意点

（注意点、懸念事項を書いてください）

**Comment by smatsudajp** [comment]
報告ありがとうございます。
確認しました。"after"の意味に関する単純な誤訳ですね。
重要度を「中」としました。

**Comment by smatsudajp** [comment]
#911 で修正＆マージされたのでクローズします。
