### ISSUE TITLE
recovery_min_apply_delay の誤訳

### ISSUE THREAD

**Issue by KondoYuta** [pgsql-jp/jpug-doc#914]
## 問題点

recovery_min_apply_delay の説明において、 (doc/src/sgml/recovery-config.sgml)

"This parameter allows you to delay recovery by a fixed period of time,
measured in milliseconds if no unit is specified."
が、
「...単位を指定しない場合、マイクロ秒で測定されます。」
と訳されていますが、「マイクロ秒」ではなく「ミリ秒」です。

また、同文の「測定されます」も、「評価されます」の方が良いです。

## 解決方法

「...単位を指定しない場合、マイクロ秒で測定されます。」
↓
「...単位を指定しない場合、ミリ秒で評価されます。」

**Comment by smatsudajp** [comment]
報告ありがとうございます。
確認しました。確かにミリ秒とすべきものをマイクロ秒としていて、またmeasureの訳語も不適切ですね。ちょっと意訳になりますが「単位を省略した場合は、ミリ秒で指定したものと見なされます」などとするのがわかりやすいかもしれません。
今週中に9.6.3がリリースされる予定なので、その翻訳と合わせて修正することになると思います。担当は小泉さんかな。

**Comment by KenichiroTanaka** [comment]
KondoYutaさん

こんにちわ
田中@JPUG-DOCです。

PostgreSQLの普及において日本語ドキュメントは極めて重要です。
JPUG-DOCではPostgreSQL9.6のドキュメント翻訳より日本語
ドキュメントの翻訳運営に貢献いただいた方のお名前を感謝の意を
込めて記載する方針としました。

記載のイメージは以下の通りです。
https://www.postgresql.jp/document/pg962doc/html/jpug-doc.html

JPUG-DOCではTYPOの報告も重要な貢献と考え、お名前をマニュアルへ
記載したいと考えています。

もし、よろしければ下記のwikiを直接編集いただくか、本メールへ返信を
いただけませんでしょうか。

・記載するお名前
・会社名を付与される場合は会社名

https://github.com/pgsql-jp/jpug-doc/wiki/ドキュメント翻訳担当リスト9.6#貢献者リスト

会社名を付与する場合は会社への確認も併せてお願いします。

お忙しいと思いますがお返事をお待ちしています。

以上です。
