### ISSUE TITLE
libpqの環境変数項目に存在しない"PGREALM"が残っている

### ISSUE THREAD

**Issue by ester41** [pgsql-jp/jpug-doc#937]
## 問題点
ソースコード上では、2005/06/27 時点に環境変数"PGREALM"が削除されていますが、
ドキュメント上に該当環境変数が残っております。

## 背景
ソースコードから環境変数を確認していたところ、ドキュメントにのみ記載がある該当変数を発見しました。
Gitハッシュ値: a159ad30489acb7aeb35d95de805f81c64d07966
該当ファイル : src\interfaces\libpq\fe-auth.c
https://github.com/postgres/postgres/commit/a159ad30489acb7aeb35d95de805f81c64d07966#diff-246f2b1e61578115293a145eb7de97d9L141

## 解決方法
doc\src\sgml\libpq.sgml の"PGREALM"項目の削除

## 注意点
本家ドキュメントにも該当記述が残っております。
https://github.com/postgres/postgres/blob/master/doc/src/sgml/libpq.sgml#L7012

**Comment by smatsudajp** [comment]
本家に報告しておきました。
https://www.postgresql.org/message-id/20170526033128.30704.52229%40wrigleys.postgresql.org

重要度が高い問題なら、翻訳版で先取りして修正することも可能ですが、少しばかり余分な作業が発生することになるので、本家側の正式な修正を待って翻訳版も修正、ということにしたいと思います。

**Comment by ester41** [comment]
お礼が遅くなりましたが、ご報告ありがとうございます。
先ほど本家を確認したところ、削除対応が入ったみたいです。

**Comment by KenichiroTanaka** [comment]
ester41さん

こんにちわ
田中@JPUG-DOCです。

PostgreSQL日本語ドキュメントのISSUESの登録をいただき
ありがとうございました。

PostgreSQLの普及において日本語ドキュメントは極めて重要です。
JPUG-DOCではPostgreSQL9.6のドキュメント翻訳より日本語
ドキュメントの翻訳運営に貢献いただいた方のお名前を感謝の意を
込めて記載する方針としました。

記載のイメージは以下の通りです。

https://www.postgresql.jp/document/pg962doc/html/jpug-doc.html

そこでJPUG-DOCではTYPOの報告も重要な貢献と考え、お名前をマニュアルへ
記載したいと考えています。

もし、よろしければ下記のwikiを直接編集いただくか、ISSUESへ返信を
いただけませんでしょうか。

・記載するお名前
・会社名を付与される場合は会社名

https://github.com/pgsql-jp/jpug-doc/wiki/ドキュメント翻訳担当リスト9.6#貢献者リスト

会社名を付与する場合は会社への確認も併せてお願いします。

お忙しいと思いますがお返事をお待ちしています。

以上です。

**Comment by ester41** [comment]
田中@jpug-docさん
ありがとうございます。
Wikiを修正しましたので、ご確認よろしくお願いします。

**Comment by KenichiroTanaka** [comment]
早速の対応ありがとうございました。
wikiにいただいている内容で掲載させていただきます。

今後ともよろしくお願いします。

**Comment by noborus** [comment]
対応終了してますので、クローズします
