### ISSUE TITLE
doc_ja_9_4_utf8 の Amazon Linux でのビルドエラー

### ISSUE THREAD

**Issue by koyhoge** [pgsql-jp/jpug-doc#95]
doc_ja_9_4_utf8 ブランチを早速手元でビルドしてみようと思いましたが、以下のエラーでうまくいきませんでした。

Amazon LInux で openjade のバージョンは 1.3.2-36.5.amzn1 です。

```
openjade:postgres.sgml:18:28:E: 非SGML数字 25991
openjade:postgres.sgml:18:29:E: 非SGML数字 26360
openjade:postgres.sgml:24:24:E: 非SGML数字 12464
openjade:postgres.sgml:24:25:E: 非SGML数字 12525
openjade:postgres.sgml:24:26:E: 非SGML数字 12540
openjade:postgres.sgml:24:27:E: 非SGML数字 12496
openjade:postgres.sgml:24:28:E: 非SGML数字 12523
openjade:postgres.sgml:24:29:E: 非SGML数字 38283
openjade:postgres.sgml:24:30:E: 非SGML数字 30330
openjade:postgres.sgml:24:31:E: 非SGML数字 12464
openjade:postgres.sgml:24:32:E: 非SGML数字 12523
openjade:postgres.sgml:24:33:E: 非SGML数字 12540
openjade:postgres.sgml:24:34:E: 非SGML数字 12503
(以下延々とエラーが続く)
```

**Comment by tatsuo-ishii** [comment]
私も同じエラーでうまくいきませんでした。
CentOS 6.6です。

**Comment by oknj** [comment]
Debian Jessie(testing)だと、うまくmake htmlできました。
openjadeは、1.4develです。
<pre>
$ openjade --version
openjade:I: "OpenJade" version "1.4devel"
openjade:I: "OpenSP" version "1.5.2"
</pre>

**Comment by noborus** [comment]
Debian/Ubuntuとの違いを比較してみました。
 /etc/sgml/catalogから辿って
/usr/share/sgml/docbook/sgml-dtd-*/catalog で docbook.dcl の指定があると、このファイルを読み込んだかどうかで動作に影響があるようです。

ここをコメントアウトするとCentOSでも通るようになりました。

```
sed -i -e 's/^SGMLDECL "docbook.dcl"/  -- SGMLDECL "docbook.dcl" --/' /usr/share/sgml/docbook/sgml-dtd-*/catalog
```

**Comment by KenichiroTanaka** [comment]
oknjさん
ありがとうございます。openjade1.4develを試そうと思いましたがOELでのmakeにちょっと躓きました。

noborusさん
ありがとうございます。OELですがいただいたsedでエラーを回避できました！

**Comment by koyhoge** [comment]
@noborus さんの sed スクリプトで該当行をコメントアウトしたところ、自分の作業環境の Amazon Linux でも無事に html が生成できました。ありがとうございました。

**Comment by KenichiroTanaka** [comment]
回避できたためCLOSEします。

**Comment by koyhoge** [comment]
Wiki を更新しておきましたw
