### ISSUE TITLE
version 9.6.3 config-setting.html  "separators"の訳

### ISSUE THREAD

**Issue by smatsudajp** [pgsql-jp/jpug-doc#960]
## 問題点

数値型のパラメータの記述方法について「1000の位取りには使わないでください」とあるが、主語が存在せず、意味が通じない。

## 背景

原文は"Do not use thousands separators"で、直訳するなら「1000の区切り文字を使わないでください」という感じなので、現状の「位取り『には』」は誤訳。「位取り『は』」とすれば誤訳ではないが、わかりやすいとは言えない。

## 解決方法

直訳もわかりやすさの点では今一つ。
現行訳を活かして"separators"を「位取りの区切り文字」と訳し、「1000の位取りの区切り文字は使わないでください」とするのがわかりやすいと思う。

**Comment by smatsudajp** [comment]
同じファイルの直後の場所に重大な誤訳を見つけたので、区別できるようタイトルを修正しました。

**Comment by KenichiroTanaka** [comment]
いただいた訳でとてもわかりやすくなったと思います。マージしました。

**Comment by KenichiroTanaka** [comment]
マージしたのでクローズします。
