### ISSUE TITLE
version 9.6.3 config-setting.html 単位付きの数値

### ISSUE THREAD

**Issue by smatsudajp** [pgsql-jp/jpug-doc#961]
## 問題点

単位付きの数値の説明で「単位の名称は大文字小文字を区別しません」とあるが、原文は"The unit name is case-sensitive"であり、正しくは「大文字小文字を区別する」という重大な誤訳。

**Comment by smatsudajp** [comment]
その直後にある「列挙型の値は大文字小文字を区別しません」は"Enum parameter values are case-insensitive"なので正しいです。念のため。

**Comment by KenichiroTanaka** [comment]
真逆の誤訳ですね。PRをマージしました。

**Comment by KenichiroTanaka** [comment]
マージしたのでクローズします。
