### ISSUE TITLE
PostgreSQL 9.4のリリースノートの項目に不要なリンクがある。

### ISSUE THREAD

**Issue by nuko-yokohama** [pgsql-jp/jpug-doc#963]
## 問題点

 PostgreSQL 9.4のリリースノートの以下の項目に不要なリンクがある。

> work_memとmaintenance_work_mem のデフォルト設定値を４倍に増やしました。 maintenance_work_mem (Bruce Momjian)

maintenance_work_mem へのリンクが2箇所あるが、2つ目のリンクは不要です。
(本家の箇所を確認したところ、2つ目のリンクはありませんでした)

## 解決方法

https://github.com/pgsql-jp/jpug-doc/blob/pg940doc/doc/src/sgml/release-9.4.sgml
のリリースノート内の該当箇所にある、2つ目のリンク 
`<xref linkend="guc-maintenance-work-mem"> `
を削除する。

**Comment by koizumistr** [comment]
#964 で対応中です。

**Comment by KenichiroTanaka** [comment]
ご報告、対応ありがとうございました。
マージ済みなのでクローズします。
