### ISSUE TITLE
pgbenchの「優れた実践」内のtypo

### ISSUE THREAD

**Issue by nuko-yokohama** [pgsql-jp/jpug-doc#971]
## 問題点

pgbenchユーティリティの説明「優れた実践」の中の文章にtypoがある。

* (誤) また、前トランザクションはその内の1つを更新しようとします。 
* (正) また、全トランザクションはその内の1つを更新しようとします。

原文では"every transaction ..."となっている。

この問題はPostgreSQL 8.3文書以降全て共通。

## 解決方法

jpug-doc/doc/src/sgml/ref/pgbench.sgml の該当箇所を修正する。

**Comment by KenichiroTanaka** [comment]
ご報告ありがとうございます。
9.6.4で対応しました。
※誤って直接リポジトリを更新してしまったためPRがありません。

**Comment by KenichiroTanaka** [comment]
基本的にはバックポートは行わない方針ですので、他に議論がなければ本対応でクローズさせてください。
