### ISSUE TITLE
9.6文書：19.8.5. プロセスの表題 の先頭の一文が翻訳されていない

### ISSUE THREAD

**Issue by nuko-yokohama** [pgsql-jp/jpug-doc#987]
## 問題点

PostgreSQL 9.6文書：19.8.5. プロセスの表題 の先頭の一文が翻訳されていない。
先頭の一文が

> These settings control how process titles of server processes are modified. Process titles are typically viewed using programs like ps or, on Windows, Process Explorer. See 28.1. 標準的なUnixツール for details.

になっている。PostgreSQL 9.5文書の該当箇所「18.8.5. プロセスの表題」では

> これらの設定項目は、psで見えるプロセスの表題を変更します。 詳細については、27.1. 標準的なUnixツールを参照してください。

と翻訳されている。

## 解決方法

PostgreSQL 9.5文書と同じ翻訳に差し替える。

**Comment by smatsudajp** [comment]
config.sgmlですね。
ちゃんと対訳になっているのですが、なぜか翻訳の方がコメントアウトされています。
